package com.tfs.irp.template.dao.impl;

import com.tfs.irp.template.dao.IrpTemplateDAO;
import com.tfs.irp.template.entity.IrpTemplate;
import com.tfs.irp.template.entity.IrpTemplateExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpTemplateDAOImpl  extends SqlMapClientDaoSupport  implements IrpTemplateDAO {

	

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_TEMPLATE
	 * @ibatorgenerated  Wed Jul 02 10:43:37 CST 2014
	 */
	public int countByExample(IrpTemplateExample example) throws SQLException {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"IRP_TEMPLATE.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_TEMPLATE
	 * @ibatorgenerated  Wed Jul 02 10:43:37 CST 2014
	 */
	public int deleteByExample(IrpTemplateExample example) throws SQLException {
		int rows = getSqlMapClientTemplate().delete(
				"IRP_TEMPLATE.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_TEMPLATE
	 * @ibatorgenerated  Wed Jul 02 10:43:37 CST 2014
	 */
	public int deleteByPrimaryKey(Long tid) throws SQLException {
		IrpTemplate key = new IrpTemplate();
		key.setTid(tid);
		int rows = getSqlMapClientTemplate().delete(
				"IRP_TEMPLATE.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_TEMPLATE
	 * @ibatorgenerated  Wed Jul 02 10:43:37 CST 2014
	 */
	public void insert(IrpTemplate record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_TEMPLATE.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_TEMPLATE
	 * @ibatorgenerated  Wed Jul 02 10:43:37 CST 2014
	 */
	public void insertSelective(IrpTemplate record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_TEMPLATE.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_TEMPLATE
	 * @ibatorgenerated  Wed Jul 02 10:43:37 CST 2014
	 */
	@SuppressWarnings("unchecked")
	public List<IrpTemplate> selectByExampleWithBLOBs(IrpTemplateExample example)
			throws SQLException {
		List<IrpTemplate> list = getSqlMapClientTemplate().queryForList(
				"IRP_TEMPLATE.ibatorgenerated_selectByExampleWithBLOBs",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_TEMPLATE
	 * @ibatorgenerated  Wed Jul 02 10:43:37 CST 2014
	 */
	@SuppressWarnings("unchecked")
	public List<IrpTemplate> selectByExampleWithoutBLOBs(
			IrpTemplateExample example) throws SQLException {
		List<IrpTemplate> list = getSqlMapClientTemplate().queryForList(
				"IRP_TEMPLATE.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_TEMPLATE
	 * @ibatorgenerated  Wed Jul 02 10:43:37 CST 2014
	 */
	public IrpTemplate selectByPrimaryKey(Long tid) throws SQLException {
		IrpTemplate key = new IrpTemplate();
		key.setTid(tid);
		IrpTemplate record = (IrpTemplate) getSqlMapClientTemplate().queryForObject(
				"IRP_TEMPLATE.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_TEMPLATE
	 * @ibatorgenerated  Wed Jul 02 10:43:37 CST 2014
	 */
	public int updateByExampleSelective(IrpTemplate record,
			IrpTemplateExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_TEMPLATE.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_TEMPLATE
	 * @ibatorgenerated  Wed Jul 02 10:43:37 CST 2014
	 */
	public int updateByExampleWithBLOBs(IrpTemplate record,
			IrpTemplateExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_TEMPLATE.ibatorgenerated_updateByExampleWithBLOBs", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_TEMPLATE
	 * @ibatorgenerated  Wed Jul 02 10:43:37 CST 2014
	 */
	public int updateByExampleWithoutBLOBs(IrpTemplate record,
			IrpTemplateExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_TEMPLATE.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_TEMPLATE
	 * @ibatorgenerated  Wed Jul 02 10:43:37 CST 2014
	 */
	public int updateByPrimaryKeySelective(IrpTemplate record)
			throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"IRP_TEMPLATE.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_TEMPLATE
	 * @ibatorgenerated  Wed Jul 02 10:43:37 CST 2014
	 */
	public int updateByPrimaryKeyWithBLOBs(IrpTemplate record)
			throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"IRP_TEMPLATE.ibatorgenerated_updateByPrimaryKeyWithBLOBs",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_TEMPLATE
	 * @ibatorgenerated  Wed Jul 02 10:43:37 CST 2014
	 */
	public int updateByPrimaryKeyWithoutBLOBs(IrpTemplate record)
			throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"IRP_TEMPLATE.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table IRP_TEMPLATE
	 * @ibatorgenerated  Wed Jul 02 10:43:37 CST 2014
	 */
	private static class UpdateByExampleParms extends IrpTemplateExample {
		private Object record;

		public UpdateByExampleParms(Object record, IrpTemplateExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}


	@Override
	public List<IrpTemplate> selectByExampleWithBLOBs(
			IrpTemplateExample example, PageUtil _pageUtil) throws SQLException {
		// TODO Auto-generated method stub
		
	    List<IrpTemplate> list = getSqlMapClientTemplate().queryForList("IRP_TEMPLATE.ibatorgenerated_selectByExampleWithBLOBs", example,_pageUtil.getPageIndex(),_pageUtil.getPageSize());
		
		return list;
	}
}