package com.tfs.irp.documentmap.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.tfs.irp.documentmap.dao.IrpDocumentMapDAO;
import com.tfs.irp.documentmap.entity.IrpDocumentMap;
import com.tfs.irp.documentmap.entity.IrpDocumentMapExample;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpDocumentMapDAOImpl extends SqlMapClientDaoSupport implements IrpDocumentMapDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_document_map
     *
     * @ibatorgenerated Thu Feb 13 09:31:55 CST 2014
     */
    public int countByExample(IrpDocumentMapExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("irp_document_map.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_document_map
     *
     * @ibatorgenerated Thu Feb 13 09:31:55 CST 2014
     */
    public int deleteByExample(IrpDocumentMapExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("irp_document_map.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_document_map
     *
     * @ibatorgenerated Thu Feb 13 09:31:55 CST 2014
     */
    public int deleteByPrimaryKey(Long mid) throws SQLException {
        IrpDocumentMap key = new IrpDocumentMap();
        key.setMid(mid);
        int rows = getSqlMapClientTemplate().delete("irp_document_map.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_document_map
     *
     * @ibatorgenerated Thu Feb 13 09:31:55 CST 2014
     */
    public void insert(IrpDocumentMap record) throws SQLException {
    	getSqlMapClientTemplate().insert("irp_document_map.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_document_map
     *
     * @ibatorgenerated Thu Feb 13 09:31:55 CST 2014
     */
    public void insertSelective(IrpDocumentMap record) throws SQLException {
    	getSqlMapClientTemplate().insert("irp_document_map.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_document_map
     *
     * @ibatorgenerated Thu Feb 13 09:31:55 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<IrpDocumentMap> selectByExample(IrpDocumentMapExample example) throws SQLException {
        List<IrpDocumentMap> list = getSqlMapClientTemplate().queryForList("irp_document_map.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_document_map
     *
     * @ibatorgenerated Thu Feb 13 09:31:55 CST 2014
     */
    public IrpDocumentMap selectByPrimaryKey(Long mid) throws SQLException {
        IrpDocumentMap key = new IrpDocumentMap();
        key.setMid(mid);
        IrpDocumentMap record = (IrpDocumentMap) getSqlMapClientTemplate().queryForObject("irp_document_map.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_document_map
     *
     * @ibatorgenerated Thu Feb 13 09:31:55 CST 2014
     */
    public int updateByExampleSelective(IrpDocumentMap record, IrpDocumentMapExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_document_map.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_document_map
     *
     * @ibatorgenerated Thu Feb 13 09:31:55 CST 2014
     */
    public int updateByExample(IrpDocumentMap record, IrpDocumentMapExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_document_map.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_document_map
     *
     * @ibatorgenerated Thu Feb 13 09:31:55 CST 2014
     */
    public int updateByPrimaryKeySelective(IrpDocumentMap record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("irp_document_map.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_document_map
     *
     * @ibatorgenerated Thu Feb 13 09:31:55 CST 2014
     */
    public int updateByPrimaryKey(IrpDocumentMap record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("irp_document_map.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table irp_document_map
     *
     * @ibatorgenerated Thu Feb 13 09:31:55 CST 2014
     */
    private static class UpdateByExampleParms extends IrpDocumentMapExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpDocumentMapExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
    @Override
    public List<Long> selectDociIdsByExample(IrpDocumentMapExample example) throws SQLException {
        List<Long> list = getSqlMapClientTemplate().queryForList("irp_document_map.ibatorgenerated_selectDocidsByExample", example);
        return list;
    }
}