package com.tfs.irp.role.dao.impl;

import com.tfs.irp.role.dao.IrpUserroleLinkDAO;
import com.tfs.irp.role.entity.IrpUserroleLink;
import com.tfs.irp.role.entity.IrpUserroleLinkExample;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpUserroleLinkDAOImpl extends SqlMapClientDaoSupport implements IrpUserroleLinkDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USERROLE_LINK
     *
     * @ibatorgenerated Wed Mar 13 10:43:31 CST 2013
     */
    public int countByExample(IrpUserroleLinkExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_USERROLE_LINK.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USERROLE_LINK
     *
     * @ibatorgenerated Wed Mar 13 10:43:31 CST 2013
     */
    public int deleteByExample(IrpUserroleLinkExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_USERROLE_LINK.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USERROLE_LINK
     *
     * @ibatorgenerated Wed Mar 13 10:43:31 CST 2013
     */
    public int deleteByPrimaryKey(Long userroleid) throws SQLException {
        IrpUserroleLink key = new IrpUserroleLink();
        key.setUserroleid(userroleid);
        int rows = getSqlMapClientTemplate().delete("IRP_USERROLE_LINK.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USERROLE_LINK
     *
     * @ibatorgenerated Wed Mar 13 10:43:31 CST 2013
     */
    public void insert(IrpUserroleLink record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_USERROLE_LINK.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USERROLE_LINK
     *
     * @ibatorgenerated Wed Mar 13 10:43:31 CST 2013
     */
    public void insertSelective(IrpUserroleLink record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_USERROLE_LINK.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USERROLE_LINK
     *
     * @ibatorgenerated Wed Mar 13 10:43:31 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<IrpUserroleLink> selectByExample(IrpUserroleLinkExample example) throws SQLException {
        List<IrpUserroleLink> list = getSqlMapClientTemplate().queryForList("IRP_USERROLE_LINK.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USERROLE_LINK
     *
     * @ibatorgenerated Wed Mar 13 10:43:31 CST 2013
     */
    public IrpUserroleLink selectByPrimaryKey(Long userroleid) throws SQLException {
        IrpUserroleLink key = new IrpUserroleLink();
        key.setUserroleid(userroleid);
        IrpUserroleLink record = (IrpUserroleLink) getSqlMapClientTemplate().queryForObject("IRP_USERROLE_LINK.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USERROLE_LINK
     *
     * @ibatorgenerated Wed Mar 13 10:43:31 CST 2013
     */
    public int updateByExampleSelective(IrpUserroleLink record, IrpUserroleLinkExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_USERROLE_LINK.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USERROLE_LINK
     *
     * @ibatorgenerated Wed Mar 13 10:43:31 CST 2013
     */
    public int updateByExample(IrpUserroleLink record, IrpUserroleLinkExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_USERROLE_LINK.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USERROLE_LINK
     *
     * @ibatorgenerated Wed Mar 13 10:43:31 CST 2013
     */
    public int updateByPrimaryKeySelective(IrpUserroleLink record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_USERROLE_LINK.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USERROLE_LINK
     *
     * @ibatorgenerated Wed Mar 13 10:43:31 CST 2013
     */
    public int updateByPrimaryKey(IrpUserroleLink record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_USERROLE_LINK.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table IRP_USERROLE_LINK
     *
     * @ibatorgenerated Wed Mar 13 10:43:31 CST 2013
     */
    private static class UpdateByExampleParms extends IrpUserroleLinkExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpUserroleLinkExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
    @SuppressWarnings("unchecked")
    @Override
    public List<Long> findRoleIdByUserId(Long _nUserId) throws SQLException {
    	return getSqlMapClientTemplate().queryForList("IRP_USERROLE_LINK.findRoleIdByUserId", _nUserId);
	}
}