package com.tfs.irp.forum.entity;

import java.util.Date;

public class IrpForum {
    /**
     *  对象表名
     */
    public final static String TABLE_NAME = "IRP_FORUM";
    
    /**
     * 主键字段名称
     */
    public final static String ID_FIELD_NAME = "FORUMID";
    
    /**
     * 帖子状态：正常
     */
    public final static int STATUS_NORMAL = 1;
    
    /**
     * 帖子状态：被举报
     */
    public final static int STATUS_UNUSUAL = 2;
    
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_FORUM.FORUMID
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    private Long forumid;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_FORUM.FORUMCONTENT
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    private String forumcontent;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_FORUM.FORUMCRUSERID
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    private Long forumcruserid;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_FORUM.FORUMCRTIME
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    private Date forumcrtime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_FORUM.FORUMSTATUS
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    private Integer forumstatus;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_FORUM.FORUMVIEWCOUNT
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    private Long forumviewcount;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_FORUM.FORUMTITLE
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    private String forumtitle;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_FORUM.FORUMCATEGORYID
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    private Long forumcategoryid;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_FORUM.FORUMID
     * @return  the value of IRP_FORUM.FORUMID
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public Long getForumid() {
        return forumid;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_FORUM.FORUMID
     * @param forumid  the value for IRP_FORUM.FORUMID
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public void setForumid(Long forumid) {
        this.forumid = forumid;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_FORUM.FORUMCONTENT
     * @return  the value of IRP_FORUM.FORUMCONTENT
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public String getForumcontent() {
        return forumcontent;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_FORUM.FORUMCONTENT
     * @param forumcontent  the value for IRP_FORUM.FORUMCONTENT
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public void setForumcontent(String forumcontent) {
        this.forumcontent = forumcontent;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_FORUM.FORUMCRUSERID
     * @return  the value of IRP_FORUM.FORUMCRUSERID
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public Long getForumcruserid() {
        return forumcruserid;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_FORUM.FORUMCRUSERID
     * @param forumcruserid  the value for IRP_FORUM.FORUMCRUSERID
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public void setForumcruserid(Long forumcruserid) {
        this.forumcruserid = forumcruserid;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_FORUM.FORUMCRTIME
     * @return  the value of IRP_FORUM.FORUMCRTIME
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public Date getForumcrtime() {
        return forumcrtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_FORUM.FORUMCRTIME
     * @param forumcrtime  the value for IRP_FORUM.FORUMCRTIME
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public void setForumcrtime(Date forumcrtime) {
        this.forumcrtime = forumcrtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_FORUM.FORUMSTATUS
     * @return  the value of IRP_FORUM.FORUMSTATUS
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public Integer getForumstatus() {
        return forumstatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_FORUM.FORUMSTATUS
     * @param forumstatus  the value for IRP_FORUM.FORUMSTATUS
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public void setForumstatus(Integer forumstatus) {
        this.forumstatus = forumstatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_FORUM.FORUMVIEWCOUNT
     * @return  the value of IRP_FORUM.FORUMVIEWCOUNT
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public Long getForumviewcount() {
        return forumviewcount;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_FORUM.FORUMVIEWCOUNT
     * @param forumviewcount  the value for IRP_FORUM.FORUMVIEWCOUNT
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public void setForumviewcount(Long forumviewcount) {
        this.forumviewcount = forumviewcount;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_FORUM.FORUMTITLE
     * @return  the value of IRP_FORUM.FORUMTITLE
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public String getForumtitle() {
        return forumtitle;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_FORUM.FORUMTITLE
     * @param forumtitle  the value for IRP_FORUM.FORUMTITLE
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public void setForumtitle(String forumtitle) {
        this.forumtitle = forumtitle;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_FORUM.FORUMCATEGORYID
     * @return  the value of IRP_FORUM.FORUMCATEGORYID
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public Long getForumcategoryid() {
        return forumcategoryid;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_FORUM.FORUMCATEGORYID
     * @param forumcategoryid  the value for IRP_FORUM.FORUMCATEGORYID
     * @ibatorgenerated  Thu Oct 19 16:27:58 CST 2017
     */
    public void setForumcategoryid(Long forumcategoryid) {
        this.forumcategoryid = forumcategoryid;
    }
}