package com.tfs.irp.asseroomapply.dao.impl;

import com.tfs.irp.asseroomapply.dao.IrpAsseroomapplyDAO;
import com.tfs.irp.asseroomapply.entity.IrpAsseroomapply;
import com.tfs.irp.asseroomapply.entity.IrpAsseroomapplyExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpAsseroomapplyDAOImpl extends SqlMapClientDaoSupport implements IrpAsseroomapplyDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_ASSEROOMAPPLY
     *
     * @ibatorgenerated Tue Sep 06 10:14:48 CST 2016
     */
    public IrpAsseroomapplyDAOImpl() {
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_ASSEROOMAPPLY
     *
     * @ibatorgenerated Tue Sep 06 10:14:48 CST 2016
     */
    public int countByExample(IrpAsseroomapplyExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_ASSEROOMAPPLY.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_ASSEROOMAPPLY
     *
     * @ibatorgenerated Tue Sep 06 10:14:48 CST 2016
     */
    public int deleteByExample(IrpAsseroomapplyExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_ASSEROOMAPPLY.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_ASSEROOMAPPLY
     *
     * @ibatorgenerated Tue Sep 06 10:14:48 CST 2016
     */
    public int deleteByPrimaryKey(Long asseroomapplyid) throws SQLException {
        IrpAsseroomapply key = new IrpAsseroomapply();
        key.setAsseroomapplyid(asseroomapplyid);
        int rows = getSqlMapClientTemplate().delete("IRP_ASSEROOMAPPLY.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_ASSEROOMAPPLY
     *
     * @ibatorgenerated Tue Sep 06 10:14:48 CST 2016
     */
    public void insert(IrpAsseroomapply record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_ASSEROOMAPPLY.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_ASSEROOMAPPLY
     *
     * @ibatorgenerated Tue Sep 06 10:14:48 CST 2016
     */
    public void insertSelective(IrpAsseroomapply record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_ASSEROOMAPPLY.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_ASSEROOMAPPLY
     *
     * @ibatorgenerated Tue Sep 06 10:14:48 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<IrpAsseroomapply> selectByExample(IrpAsseroomapplyExample example) throws SQLException {
        List<IrpAsseroomapply> list = getSqlMapClientTemplate().queryForList("IRP_ASSEROOMAPPLY.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_ASSEROOMAPPLY
     *
     * @ibatorgenerated Tue Sep 06 10:14:48 CST 2016
     */
    public IrpAsseroomapply selectByPrimaryKey(Long asseroomapplyid) throws SQLException {
        IrpAsseroomapply key = new IrpAsseroomapply();
        key.setAsseroomapplyid(asseroomapplyid);
        IrpAsseroomapply record = (IrpAsseroomapply) getSqlMapClientTemplate().queryForObject("IRP_ASSEROOMAPPLY.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_ASSEROOMAPPLY
     *
     * @ibatorgenerated Tue Sep 06 10:14:48 CST 2016
     */
    public int updateByExampleSelective(IrpAsseroomapply record, IrpAsseroomapplyExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_ASSEROOMAPPLY.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_ASSEROOMAPPLY
     *
     * @ibatorgenerated Tue Sep 06 10:14:48 CST 2016
     */
    public int updateByExample(IrpAsseroomapply record, IrpAsseroomapplyExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_ASSEROOMAPPLY.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_ASSEROOMAPPLY
     *
     * @ibatorgenerated Tue Sep 06 10:14:48 CST 2016
     */
    public int updateByPrimaryKeySelective(IrpAsseroomapply record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_ASSEROOMAPPLY.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_ASSEROOMAPPLY
     *
     * @ibatorgenerated Tue Sep 06 10:14:48 CST 2016
     */
    public int updateByPrimaryKey(IrpAsseroomapply record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_ASSEROOMAPPLY.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table IRP_ASSEROOMAPPLY
     *
     * @ibatorgenerated Tue Sep 06 10:14:48 CST 2016
     */
    private static class UpdateByExampleParms extends IrpAsseroomapplyExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpAsseroomapplyExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<IrpAsseroomapply> selectByExample(
			IrpAsseroomapplyExample example, PageUtil page) throws SQLException {
		 List<IrpAsseroomapply> list = getSqlMapClientTemplate().queryForList("IRP_ASSEROOMAPPLY.ibatorgenerated_selectByExample", example,page.getPageIndex(),page.getPageSize());
	        return list;
	}
}