package com.tfs.irp.doctransmite.dao;

import com.tfs.irp.doctransmite.entity.IrpDocumentTransmite;
import com.tfs.irp.doctransmite.entity.IrpDocumentTransmiteExample;
import java.sql.SQLException;
import java.util.List;

public interface IrpDocumentTransmiteDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DOCUMENT_TRANSMITE
	 * @ibatorgenerated  Fri May 03 14:08:55 CST 2013
	 */
	int countByExample(IrpDocumentTransmiteExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DOCUMENT_TRANSMITE
	 * @ibatorgenerated  Fri May 03 14:08:55 CST 2013
	 */
	int deleteByExample(IrpDocumentTransmiteExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DOCUMENT_TRANSMITE
	 * @ibatorgenerated  Fri May 03 14:08:55 CST 2013
	 */
	void insert(IrpDocumentTransmite record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DOCUMENT_TRANSMITE
	 * @ibatorgenerated  Fri May 03 14:08:55 CST 2013
	 */
	void insertSelective(IrpDocumentTransmite record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DOCUMENT_TRANSMITE
	 * @ibatorgenerated  Fri May 03 14:08:55 CST 2013
	 */
	List<IrpDocumentTransmite> selectByExample(
			IrpDocumentTransmiteExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DOCUMENT_TRANSMITE
	 * @ibatorgenerated  Fri May 03 14:08:55 CST 2013
	 */
	int updateByExampleSelective(IrpDocumentTransmite record,
			IrpDocumentTransmiteExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DOCUMENT_TRANSMITE
	 * @ibatorgenerated  Fri May 03 14:08:55 CST 2013
	 */
	int updateByExample(IrpDocumentTransmite record,
			IrpDocumentTransmiteExample example) throws SQLException;
}