package com.tfs.irp.projectsharetask.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.tfs.irp.projectsharetask.dao.IrpProjectShareTaskDAO;
import com.tfs.irp.projectsharetask.entity.IrpProjectShareTask;
import com.tfs.irp.projectsharetask.entity.IrpProjectShareTaskExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpProjectShareTaskDAOImpl extends SqlMapClientDaoSupport implements IrpProjectShareTaskDAO {


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_SHARE_TASK
     *
     * @ibatorgenerated Tue Aug 26 16:50:34 CST 2014
     */
    public int countByExample(IrpProjectShareTaskExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_PROJECT_SHARE_TASK.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_SHARE_TASK
     *
     * @ibatorgenerated Tue Aug 26 16:50:34 CST 2014
     */
    public int deleteByExample(IrpProjectShareTaskExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_PROJECT_SHARE_TASK.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_SHARE_TASK
     *
     * @ibatorgenerated Tue Aug 26 16:50:34 CST 2014
     */
    public int deleteByPrimaryKey(Long sharetaskid) throws SQLException {
        IrpProjectShareTask key = new IrpProjectShareTask();
        key.setSharetaskid(sharetaskid);
        int rows = getSqlMapClientTemplate().delete("IRP_PROJECT_SHARE_TASK.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_SHARE_TASK
     *
     * @ibatorgenerated Tue Aug 26 16:50:34 CST 2014
     */
    public void insert(IrpProjectShareTask record) throws SQLException {
    	getSqlMapClientTemplate().insert("IRP_PROJECT_SHARE_TASK.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_SHARE_TASK
     *
     * @ibatorgenerated Tue Aug 26 16:50:34 CST 2014
     */
    public void insertSelective(IrpProjectShareTask record) throws SQLException {
    	getSqlMapClientTemplate().insert("IRP_PROJECT_SHARE_TASK.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_SHARE_TASK
     *
     * @ibatorgenerated Tue Aug 26 16:50:34 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<IrpProjectShareTask> selectByExampleWithBLOBs(IrpProjectShareTaskExample example) throws SQLException {
        List<IrpProjectShareTask> list = getSqlMapClientTemplate().queryForList("IRP_PROJECT_SHARE_TASK.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_SHARE_TASK
     *
     * @ibatorgenerated Tue Aug 26 16:50:34 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<IrpProjectShareTask> selectByExample(IrpProjectShareTaskExample example) throws SQLException {
        List<IrpProjectShareTask> list = getSqlMapClientTemplate().queryForList("IRP_PROJECT_SHARE_TASK.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_SHARE_TASK
     *
     * @ibatorgenerated Tue Aug 26 16:50:34 CST 2014
     */
    public IrpProjectShareTask selectByPrimaryKey(Long sharetaskid) throws SQLException {
        IrpProjectShareTask key = new IrpProjectShareTask();
        key.setSharetaskid(sharetaskid);
        IrpProjectShareTask record = (IrpProjectShareTask) getSqlMapClientTemplate().queryForObject("IRP_PROJECT_SHARE_TASK.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_SHARE_TASK
     *
     * @ibatorgenerated Tue Aug 26 16:50:34 CST 2014
     */
    public int updateByExampleSelective(IrpProjectShareTask record, IrpProjectShareTaskExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_PROJECT_SHARE_TASK.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_SHARE_TASK
     *
     * @ibatorgenerated Tue Aug 26 16:50:34 CST 2014
     */
    public int updateByExampleWithBLOBs(IrpProjectShareTask record, IrpProjectShareTaskExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_PROJECT_SHARE_TASK.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_SHARE_TASK
     *
     * @ibatorgenerated Tue Aug 26 16:50:34 CST 2014
     */
    public int updateByExampleWithoutBLOBs(IrpProjectShareTask record, IrpProjectShareTaskExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_PROJECT_SHARE_TASK.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_SHARE_TASK
     *
     * @ibatorgenerated Tue Aug 26 16:50:34 CST 2014
     */
    public int updateByPrimaryKeySelective(IrpProjectShareTask record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_PROJECT_SHARE_TASK.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_SHARE_TASK
     *
     * @ibatorgenerated Tue Aug 26 16:50:34 CST 2014
     */
    public int updateByPrimaryKeyWithBLOBs(IrpProjectShareTask record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_PROJECT_SHARE_TASK.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_SHARE_TASK
     *
     * @ibatorgenerated Tue Aug 26 16:50:34 CST 2014
     */
    public int updateByPrimaryKeyWithoutBLOBs(IrpProjectShareTask record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_PROJECT_SHARE_TASK.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table IRP_PROJECT_SHARE_TASK
     *
     * @ibatorgenerated Tue Aug 26 16:50:34 CST 2014
     */
    private static class UpdateByExampleParms extends IrpProjectShareTaskExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpProjectShareTaskExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
	@SuppressWarnings("unchecked")
	@Override
	public List<IrpProjectShareTask> selectByExample(
			IrpProjectShareTaskExample example,PageUtil pageUtil) throws SQLException {
		List<IrpProjectShareTask> list = getSqlMapClientTemplate().queryForList(
				"IRP_PROJECT_SHARE_TASK.ibatorgenerated_selectByExample",
				example,pageUtil.getPageIndex(),pageUtil.getPageSize());
		return list;
	}


}