package com.tfs.irp.category.entity;

import java.util.Date;

import com.tfs.irp.base.IrpBaseObj;

public class IrpCategory extends IrpBaseObj{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column irp_category.ID
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    private Long categoryid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column irp_category.CPARENTID
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    private Long cparentid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column irp_category.CNAME
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    private String cname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column irp_category.CDESC
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    private String cdesc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column irp_category.CTYPE
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    private Integer ctype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column irp_category.CATEGORYORDER
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    private Long categoryorder;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column irp_category.STATUS
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column irp_category.LINKURL
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    private String linkurl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column irp_category.CATEGORYPIC
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    private String categorypic;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column irp_category.CRUSERID
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    private Long cruserid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column irp_category.CRTIME
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    private Date crtime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column irp_category.ID
     *
     * @return the value of irp_category.ID
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public Long getCategoryid() {
		return categoryid;
	}

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column irp_category.ID
     *
     * @param id the value for irp_category.ID
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public void setCategoryid(Long categoryid) {
		this.categoryid = categoryid;
	}

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column irp_category.CPARENTID
     *
     * @return the value of irp_category.CPARENTID
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public Long getCparentid() {
        return cparentid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column irp_category.CPARENTID
     *
     * @param cparentid the value for irp_category.CPARENTID
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public void setCparentid(Long cparentid) {
        this.cparentid = cparentid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column irp_category.CNAME
     *
     * @return the value of irp_category.CNAME
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column irp_category.CNAME
     *
     * @param cname the value for irp_category.CNAME
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column irp_category.CDESC
     *
     * @return the value of irp_category.CDESC
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public String getCdesc() {
        return cdesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column irp_category.CDESC
     *
     * @param cdesc the value for irp_category.CDESC
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public void setCdesc(String cdesc) {
        this.cdesc = cdesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column irp_category.CTYPE
     *
     * @return the value of irp_category.CTYPE
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public Integer getCtype() {
        return ctype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column irp_category.CTYPE
     *
     * @param ctype the value for irp_category.CTYPE
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public void setCtype(Integer ctype) {
        this.ctype = ctype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column irp_category.CATEGORYORDER
     *
     * @return the value of irp_category.CATEGORYORDER
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public Long getCategoryorder() {
        return categoryorder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column irp_category.CATEGORYORDER
     *
     * @param categoryorder the value for irp_category.CATEGORYORDER
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public void setCategoryorder(Long categoryorder) {
        this.categoryorder = categoryorder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column irp_category.STATUS
     *
     * @return the value of irp_category.STATUS
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column irp_category.STATUS
     *
     * @param status the value for irp_category.STATUS
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column irp_category.LINKURL
     *
     * @return the value of irp_category.LINKURL
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public String getLinkurl() {
        return linkurl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column irp_category.LINKURL
     *
     * @param linkurl the value for irp_category.LINKURL
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public void setLinkurl(String linkurl) {
        this.linkurl = linkurl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column irp_category.CATEGORYPIC
     *
     * @return the value of irp_category.CATEGORYPIC
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public String getCategorypic() {
        return categorypic;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column irp_category.CATEGORYPIC
     *
     * @param categorypic the value for irp_category.CATEGORYPIC
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public void setCategorypic(String categorypic) {
        this.categorypic = categorypic;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column irp_category.CRUSERID
     *
     * @return the value of irp_category.CRUSERID
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public Long getCruserid() {
        return cruserid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column irp_category.CRUSERID
     *
     * @param cruserid the value for irp_category.CRUSERID
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public void setCruserid(Long cruserid) {
        this.cruserid = cruserid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column irp_category.CRTIME
     *
     * @return the value of irp_category.CRTIME
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public Date getCrtime() {
        return crtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column irp_category.CRTIME
     *
     * @param crtime the value for irp_category.CRTIME
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public void setCrtime(Date crtime) {
        this.crtime = crtime;
    }

    /** 对象表名 **/
    public final static String TABLE_NAME = "IRP_CATEGORY";
    /** 主键字段名 **/
    public final static String ID_FIELD_NAME = "CATEGORYID";
    
    public final static Long CATEGORY_TYPE_QUESTION = 1L;
    public final static Long STATUS_START = 1L;
    public final static Long STATUS_FORBID = 0L;
	
	public static final String CATEGORY_QUESTION = "CATEGORY_QUESTION";
	
	/**
	 * 百科分类
	 * @return
	 */
	public static final String CALEGORYTERM = "CALEGORYTERM";
	/**
	 * 词条模版分类
	 * @return
	 */
	public static final String CALEGORYTMPLATE = "CALEGORYTMPLATE";
	/**
	 * 题库模版分类
	 * @return 
	 */
	public static final String CALEGORYQBANK = "CALEGORYQBANK";
	/**
	 * 试卷分类
	 * @return
	 */
	public static final String CATETESTPAPER = "CATETESTPAPER";
	/**
	 * 考试管理分类id
	 * @return
	 */
	public static final String EXAMCATEMANAGER = "EXAMCATEMANAGER";
	
	
	/**
	 * 表单分类
	 * @return
	 */
	public static final String FORMCATE = "FORMCATE";
	
	/**
	 * 知识模版分类
	 * @return
	 */
	public static final String KNOWLEDGECATEMB = "KNOWLEDGECATEMB";
	
	public static final String MEDAL = "MEDAL";
	
	public static final String GOODS = "GOODS";
	@Override
	public Long getId() {
		return this.categoryid;
	}

	@Override
	public String getName() {
		return this.cname;
	}

	@Override
	public String getTableName() {
		return TABLE_NAME;
	}

	@Override
	public String getIdFieldName() {
		return ID_FIELD_NAME;
	}
	
	
}