package com.tfs.irp.motetread.dao.impl;

import com.tfs.irp.motetread.dao.IrpMostTreadDAO;
import com.tfs.irp.motetread.entity.IrpMostTread;
import com.tfs.irp.motetread.entity.IrpMostTreadExample;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpMostTreadDAOImpl extends SqlMapClientDaoSupport  implements IrpMostTreadDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MOST_TREAD
	 * @ibatorgenerated  Tue Sep 24 09:40:23 CST 2013
	 */
	public int countByExample(IrpMostTreadExample example) throws SQLException {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"IRP_MOST_TREAD.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MOST_TREAD
	 * @ibatorgenerated  Tue Sep 24 09:40:23 CST 2013
	 */
	public int deleteByExample(IrpMostTreadExample example) throws SQLException {
		int rows = getSqlMapClientTemplate().delete(
				"IRP_MOST_TREAD.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MOST_TREAD
	 * @ibatorgenerated  Tue Sep 24 09:40:23 CST 2013
	 */
	public void insert(IrpMostTread record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_MOST_TREAD.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MOST_TREAD
	 * @ibatorgenerated  Tue Sep 24 09:40:23 CST 2013
	 */
	public void insertSelective(IrpMostTread record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_MOST_TREAD.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MOST_TREAD
	 * @ibatorgenerated  Tue Sep 24 09:40:23 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<IrpMostTread> selectByExample(IrpMostTreadExample example)
			throws SQLException {
		List<IrpMostTread> list = getSqlMapClientTemplate().queryForList(
				"IRP_MOST_TREAD.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MOST_TREAD
	 * @ibatorgenerated  Tue Sep 24 09:40:23 CST 2013
	 */
	public int updateByExampleSelective(IrpMostTread record,
			IrpMostTreadExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_MOST_TREAD.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MOST_TREAD
	 * @ibatorgenerated  Tue Sep 24 09:40:23 CST 2013
	 */
	public int updateByExample(IrpMostTread record, IrpMostTreadExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_MOST_TREAD.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table IRP_MOST_TREAD
	 * @ibatorgenerated  Tue Sep 24 09:40:23 CST 2013
	 */
	private static class UpdateByExampleParms extends IrpMostTreadExample {
		private Object record;

		public UpdateByExampleParms(Object record, IrpMostTreadExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}