package com.tfs.irp.config.dao.impl;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.tfs.irp.config.dao.IrpConfigDAO;
import com.tfs.irp.config.entity.IrpConfig;
import com.tfs.irp.config.entity.IrpConfigExample;
import com.tfs.irp.util.PageUtil;

public class IrpConfigDAOImpl extends SqlMapClientDaoSupport implements IrpConfigDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG
     *
     * @ibatorgenerated Thu Mar 21 15:25:53 CST 2013
     */
    public int countByExample(IrpConfigExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_IRP_CONFIG.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG
     *
     * @ibatorgenerated Thu Mar 21 15:25:53 CST 2013
     */
    public int deleteByExample(IrpConfigExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_IRP_CONFIG.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG
     *
     * @ibatorgenerated Thu Mar 21 15:25:53 CST 2013
     */
    public int deleteByPrimaryKey(Long configid){
        IrpConfig key = new IrpConfig();
        key.setConfigid(configid);
        int rows = getSqlMapClientTemplate().delete("IRP_IRP_CONFIG.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG
     *
     * @ibatorgenerated Thu Mar 21 15:25:53 CST 2013
     */
    public void insert(IrpConfig record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_IRP_CONFIG.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG
     *
     * @ibatorgenerated Thu Mar 21 15:25:53 CST 2013
     */
    public void insertSelective(IrpConfig record){
        getSqlMapClientTemplate().insert("IRP_IRP_CONFIG.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG
     *
     * @ibatorgenerated Thu Mar 21 15:25:53 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<IrpConfig> selectByExample(IrpConfigExample example) throws SQLException {
        List<IrpConfig> list = getSqlMapClientTemplate().queryForList("IRP_IRP_CONFIG.ibatorgenerated_selectByExample", example);
        return list;
    }
	@Override
	public List<IrpConfig> selectByExample(IrpConfigExample example,
			PageUtil pageUtil) throws SQLException {
		List<IrpConfig> list = getSqlMapClientTemplate().queryForList("IRP_IRP_CONFIG.ibatorgenerated_selectByExample", example,pageUtil.getPageIndex(),pageUtil.getPageSize());
        return list;
	}
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG
     *
     * @ibatorgenerated Thu Mar 21 15:25:53 CST 2013
     */
    public IrpConfig selectByPrimaryKey(Long configid) throws SQLException {
        IrpConfig key = new IrpConfig();
        key.setConfigid(configid);
        IrpConfig record = (IrpConfig) getSqlMapClientTemplate().queryForObject("IRP_IRP_CONFIG.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG
     *
     * @ibatorgenerated Thu Mar 21 15:25:53 CST 2013
     */
    public int updateByExampleSelective(IrpConfig record, IrpConfigExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_IRP_CONFIG.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG
     *
     * @ibatorgenerated Thu Mar 21 15:25:53 CST 2013
     */
    public int updateByExample(IrpConfig record, IrpConfigExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_IRP_CONFIG.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG
     *
     * @ibatorgenerated Thu Mar 21 15:25:53 CST 2013
     */
    public int updateByPrimaryKeySelective(IrpConfig record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_IRP_CONFIG.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG
     *
     * @ibatorgenerated Thu Mar 21 15:25:53 CST 2013
     */
    public int updateByPrimaryKey(IrpConfig record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_IRP_CONFIG.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table IRP.IRP_CONFIG
     *
     * @ibatorgenerated Thu Mar 21 15:25:53 CST 2013
     */
    private static class UpdateByExampleParms extends IrpConfigExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpConfigExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public String selectCValueByCKey(String _sCKey) throws SQLException {
		String sCValue = "";
		List<String> list = getSqlMapClientTemplate().queryForList("IRP_IRP_CONFIG.selectValueByKey", _sCKey);
		if(list!=null && list.size()>0){
			sCValue = list.get(0);
		}
		return sCValue;
	}


}