package com.tfs.irp.job.dao.impl;

import com.tfs.irp.job.dao.IrpJobDAO;
import com.tfs.irp.job.entity.IrpJob;
import com.tfs.irp.job.entity.IrpJobExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpJobDAOImpl extends SqlMapClientDaoSupport implements IrpJobDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRP_JOB
     *
     * @mbggenerated Sat Nov 02 17:39:20 CST 2013
     */
    public int countByExample(IrpJobExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_JOB.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRP_JOB
     *
     * @mbggenerated Sat Nov 02 17:39:20 CST 2013
     */
    public int deleteByExample(IrpJobExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_JOB.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRP_JOB
     *
     * @mbggenerated Sat Nov 02 17:39:20 CST 2013
     */
    public int deleteByPrimaryKey(Long jobid) throws SQLException {
        IrpJob _key = new IrpJob();
        _key.setJobid(jobid);
        int rows = getSqlMapClientTemplate().delete("IRP_JOB.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRP_JOB
     *
     * @mbggenerated Sat Nov 02 17:39:20 CST 2013
     */
    public void insert(IrpJob record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_JOB.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRP_JOB
     *
     * @mbggenerated Sat Nov 02 17:39:20 CST 2013
     */
    public void insertSelective(IrpJob record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_JOB.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRP_JOB
     *
     * @mbggenerated Sat Nov 02 17:39:20 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<IrpJob> selectByExample(IrpJobExample example) throws SQLException {
        List<IrpJob> list = getSqlMapClientTemplate().queryForList("IRP_JOB.selectByExample", example);
        return list;
    }
    
    @SuppressWarnings("unchecked")
    public List<IrpJob> selectByExample(IrpJobExample example, PageUtil pageUtil) throws SQLException {
        List<IrpJob> list = getSqlMapClientTemplate().queryForList("IRP_JOB.selectByExample", example, pageUtil.getPageIndex(), pageUtil.getPageSize());
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRP_JOB
     *
     * @mbggenerated Sat Nov 02 17:39:20 CST 2013
     */
    public IrpJob selectByPrimaryKey(Long jobid) throws SQLException {
        IrpJob _key = new IrpJob();
        _key.setJobid(jobid);
        IrpJob record = (IrpJob) getSqlMapClientTemplate().queryForObject("IRP_JOB.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRP_JOB
     *
     * @mbggenerated Sat Nov 02 17:39:20 CST 2013
     */
    public int updateByExampleSelective(IrpJob record, IrpJobExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_JOB.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRP_JOB
     *
     * @mbggenerated Sat Nov 02 17:39:20 CST 2013
     */
    public int updateByExample(IrpJob record, IrpJobExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_JOB.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRP_JOB
     *
     * @mbggenerated Sat Nov 02 17:39:20 CST 2013
     */
    public int updateByPrimaryKeySelective(IrpJob record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_JOB.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IRP_JOB
     *
     * @mbggenerated Sat Nov 02 17:39:20 CST 2013
     */
    public int updateByPrimaryKey(IrpJob record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_JOB.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table IRP_JOB
     *
     * @mbggenerated Sat Nov 02 17:39:20 CST 2013
     */
    protected static class UpdateByExampleParms extends IrpJobExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpJobExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}