package com.tfs.irp.doctransmite.dao.impl;

import com.tfs.irp.doctransmite.dao.IrpDocumentTransmiteDAO;
import com.tfs.irp.doctransmite.entity.IrpDocumentTransmite;
import com.tfs.irp.doctransmite.entity.IrpDocumentTransmiteExample;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpDocumentTransmiteDAOImpl extends SqlMapClientDaoSupport  implements IrpDocumentTransmiteDAO {
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DOCUMENT_TRANSMITE
	 * @ibatorgenerated  Fri May 03 14:08:55 CST 2013
	 */
	public int countByExample(IrpDocumentTransmiteExample example)
			throws SQLException {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"IRP_DOCUMENT_TRANSMITE.ibatorgenerated_countByExample",
				example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DOCUMENT_TRANSMITE
	 * @ibatorgenerated  Fri May 03 14:08:55 CST 2013
	 */
	public int deleteByExample(IrpDocumentTransmiteExample example)
			throws SQLException {
		int rows = getSqlMapClientTemplate().delete(
				"IRP_DOCUMENT_TRANSMITE.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DOCUMENT_TRANSMITE
	 * @ibatorgenerated  Fri May 03 14:08:55 CST 2013
	 */
	public void insert(IrpDocumentTransmite record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_DOCUMENT_TRANSMITE.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DOCUMENT_TRANSMITE
	 * @ibatorgenerated  Fri May 03 14:08:55 CST 2013
	 */
	public void insertSelective(IrpDocumentTransmite record)
			throws SQLException {
		getSqlMapClientTemplate().insert(
				"IRP_DOCUMENT_TRANSMITE.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DOCUMENT_TRANSMITE
	 * @ibatorgenerated  Fri May 03 14:08:55 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<IrpDocumentTransmite> selectByExample(
			IrpDocumentTransmiteExample example) throws SQLException {
		List<IrpDocumentTransmite> list = getSqlMapClientTemplate().queryForList(
				"IRP_DOCUMENT_TRANSMITE.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DOCUMENT_TRANSMITE
	 * @ibatorgenerated  Fri May 03 14:08:55 CST 2013
	 */
	public int updateByExampleSelective(IrpDocumentTransmite record,
			IrpDocumentTransmiteExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("IRP_DOCUMENT_TRANSMITE.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DOCUMENT_TRANSMITE
	 * @ibatorgenerated  Fri May 03 14:08:55 CST 2013
	 */
	public int updateByExample(IrpDocumentTransmite record,
			IrpDocumentTransmiteExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("IRP_DOCUMENT_TRANSMITE.ibatorgenerated_updateByExample",
						parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table IRP_DOCUMENT_TRANSMITE
	 * @ibatorgenerated  Fri May 03 14:08:55 CST 2013
	 */
	private static class UpdateByExampleParms extends
			IrpDocumentTransmiteExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				IrpDocumentTransmiteExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}