package com.tfs.irp.projectsharetask.entity;

import java.util.Date;
import java.util.List;

import com.tfs.irp.base.IrpBaseObj;
import java.math.BigDecimal;

public class IrpProjectShareTask extends IrpBaseObj{
	private String prname;
	
	public String getPrname() {
		return prname;
	}

	public void setPrname(String prname) {
		this.prname = prname;
	}
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.SHARETASKID
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private Long sharetaskid;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.PROJECTID
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private Long projectid;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.CRUSERID
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private Long cruserid;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.CRTIME
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private Date crtime;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.STARTTIME
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private Date starttime;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.UPDATETIME
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private Date updatetime;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.ENDTIME
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private Date endtime;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.OFFPERSONID
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private Long offpersonid;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.ISCALLMESSAGE
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private Long iscallmessage;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.SHAREDESC
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private String sharedesc;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.TASKDESC
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private String taskdesc;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.PARENTID
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private Long parentid;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.ISVISIBLE
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private Long isvisible;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.ISCLOSED
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private Long isclosed;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.ISSTATE
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private Long isstate;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.PROSTATUS
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private Long prostatus;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.THEMETYPE
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private Long themetype;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_PROJECT_SHARE_TASK.THEMETEXT
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	private String themetext;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.SHARETASKID
	 * @return  the value of IRP_PROJECT_SHARE_TASK.SHARETASKID
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public Long getSharetaskid() {
		return sharetaskid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.SHARETASKID
	 * @param sharetaskid  the value for IRP_PROJECT_SHARE_TASK.SHARETASKID
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setSharetaskid(Long sharetaskid) {
		this.sharetaskid = sharetaskid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.PROJECTID
	 * @return  the value of IRP_PROJECT_SHARE_TASK.PROJECTID
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public Long getProjectid() {
		return projectid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.PROJECTID
	 * @param projectid  the value for IRP_PROJECT_SHARE_TASK.PROJECTID
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setProjectid(Long projectid) {
		this.projectid = projectid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.CRUSERID
	 * @return  the value of IRP_PROJECT_SHARE_TASK.CRUSERID
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public Long getCruserid() {
		return cruserid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.CRUSERID
	 * @param cruserid  the value for IRP_PROJECT_SHARE_TASK.CRUSERID
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setCruserid(Long cruserid) {
		this.cruserid = cruserid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.CRTIME
	 * @return  the value of IRP_PROJECT_SHARE_TASK.CRTIME
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public Date getCrtime() {
		return crtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.CRTIME
	 * @param crtime  the value for IRP_PROJECT_SHARE_TASK.CRTIME
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setCrtime(Date crtime) {
		this.crtime = crtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.STARTTIME
	 * @return  the value of IRP_PROJECT_SHARE_TASK.STARTTIME
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public Date getStarttime() {
		return starttime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.STARTTIME
	 * @param starttime  the value for IRP_PROJECT_SHARE_TASK.STARTTIME
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.UPDATETIME
	 * @return  the value of IRP_PROJECT_SHARE_TASK.UPDATETIME
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.UPDATETIME
	 * @param updatetime  the value for IRP_PROJECT_SHARE_TASK.UPDATETIME
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.ENDTIME
	 * @return  the value of IRP_PROJECT_SHARE_TASK.ENDTIME
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public Date getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.ENDTIME
	 * @param endtime  the value for IRP_PROJECT_SHARE_TASK.ENDTIME
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.OFFPERSONID
	 * @return  the value of IRP_PROJECT_SHARE_TASK.OFFPERSONID
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public Long getOffpersonid() {
		return offpersonid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.OFFPERSONID
	 * @param offpersonid  the value for IRP_PROJECT_SHARE_TASK.OFFPERSONID
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setOffpersonid(Long offpersonid) {
		this.offpersonid = offpersonid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.ISCALLMESSAGE
	 * @return  the value of IRP_PROJECT_SHARE_TASK.ISCALLMESSAGE
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public Long getIscallmessage() {
		return iscallmessage;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.ISCALLMESSAGE
	 * @param iscallmessage  the value for IRP_PROJECT_SHARE_TASK.ISCALLMESSAGE
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setIscallmessage(Long iscallmessage) {
		this.iscallmessage = iscallmessage;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.SHAREDESC
	 * @return  the value of IRP_PROJECT_SHARE_TASK.SHAREDESC
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public String getSharedesc() {
		return sharedesc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.SHAREDESC
	 * @param sharedesc  the value for IRP_PROJECT_SHARE_TASK.SHAREDESC
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setSharedesc(String sharedesc) {
		this.sharedesc = sharedesc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.TASKDESC
	 * @return  the value of IRP_PROJECT_SHARE_TASK.TASKDESC
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public String getTaskdesc() {
		return taskdesc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.TASKDESC
	 * @param taskdesc  the value for IRP_PROJECT_SHARE_TASK.TASKDESC
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setTaskdesc(String taskdesc) {
		this.taskdesc = taskdesc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.PARENTID
	 * @return  the value of IRP_PROJECT_SHARE_TASK.PARENTID
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public Long getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.PARENTID
	 * @param parentid  the value for IRP_PROJECT_SHARE_TASK.PARENTID
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setParentid(Long parentid) {
		this.parentid = parentid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.ISVISIBLE
	 * @return  the value of IRP_PROJECT_SHARE_TASK.ISVISIBLE
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public Long getIsvisible() {
		return isvisible;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.ISVISIBLE
	 * @param isvisible  the value for IRP_PROJECT_SHARE_TASK.ISVISIBLE
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setIsvisible(Long isvisible) {
		this.isvisible = isvisible;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.ISCLOSED
	 * @return  the value of IRP_PROJECT_SHARE_TASK.ISCLOSED
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public Long getIsclosed() {
		return isclosed;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.ISCLOSED
	 * @param isclosed  the value for IRP_PROJECT_SHARE_TASK.ISCLOSED
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setIsclosed(Long isclosed) {
		this.isclosed = isclosed;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.ISSTATE
	 * @return  the value of IRP_PROJECT_SHARE_TASK.ISSTATE
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public Long getIsstate() {
		return isstate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.ISSTATE
	 * @param isstate  the value for IRP_PROJECT_SHARE_TASK.ISSTATE
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setIsstate(Long isstate) {
		this.isstate = isstate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.PROSTATUS
	 * @return  the value of IRP_PROJECT_SHARE_TASK.PROSTATUS
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public Long getProstatus() {
		return prostatus;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.PROSTATUS
	 * @param prostatus  the value for IRP_PROJECT_SHARE_TASK.PROSTATUS
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setProstatus(Long prostatus) {
		this.prostatus = prostatus;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.THEMETYPE
	 * @return  the value of IRP_PROJECT_SHARE_TASK.THEMETYPE
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public Long getThemetype() {
		return themetype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.THEMETYPE
	 * @param themetype  the value for IRP_PROJECT_SHARE_TASK.THEMETYPE
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setThemetype(Long themetype) {
		this.themetype = themetype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_PROJECT_SHARE_TASK.THEMETEXT
	 * @return  the value of IRP_PROJECT_SHARE_TASK.THEMETEXT
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public String getThemetext() {
		return themetext;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_PROJECT_SHARE_TASK.THEMETEXT
	 * @param themetext  the value for IRP_PROJECT_SHARE_TASK.THEMETEXT
	 * @ibatorgenerated  Tue Aug 26 16:50:34 CST 2014
	 */
	public void setThemetext(String themetext) {
		this.themetext = themetext;
	}
	/** �?��人可�? 
	 */
	public static final Long PUBLIC_TO_SEE=0L; 
	
	/**
	 * 3 仅任务成员可�? */
	public static final Long TASK_PERSON=3L;
	/**
	 * 2 项目中人可见
	 */
	public static final Long PROJECT_PERSON=2L;
	/**
	 * 短信通知
	 */
	public static final Long IS_CALL=1L;
	/**
	 * 不短信�?�?
	 * 
	 */
	public static final Long NO_CALL=2L;
	/**
	 * 表名irp_project_share_task
	 */
	public final static String TABLE_NAME = "IRP_PROJECT_SHARE_TASK";
	
	/**
     * 主键字段名称
     */
	public final static String ID_FIELD_NAME = "SHARETASKID";
	
	@Override
	public Long getId() {
		// TODO Auto-generated method stub 
		return sharetaskid;
	}

	@Override
	public String getName() {
		// TODO Auto-generated method stub
		return TABLE_NAME;
	}

	@Override
	public String getTableName() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getIdFieldName() {
		// TODO Auto-generated method stub
		return null;
	}
	public String userPicUrl;
	
	public String userName;

	
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPicUrl() {
		return userPicUrl;
	}


	public void setUserPicUrl(String userPicUrl) {
		this.userPicUrl = userPicUrl;
	}
	public List<IrpProjectShareTask> replayShareTaskList;
	public List<IrpProjectShareTask> replayShareTaskLists;

	public List<IrpProjectShareTask> getReplayShareTaskList() {
		return replayShareTaskList;
	}

	public void setReplayShareTaskList(List<IrpProjectShareTask> replayShareTaskList) {
		this.replayShareTaskList = replayShareTaskList;
	}
	

	public List<IrpProjectShareTask> getReplayShareTaskLists() {
		return replayShareTaskLists;
	}

	public void setReplayShareTaskLists(List<IrpProjectShareTask> replayShareTaskLists) {
		this.replayShareTaskLists = replayShareTaskLists;
	}
	/**
	 * 动�?的附件集�?
	 */
	public List attachedList;
	 
	public List getAttachedList() {
		return attachedList;
	}

	public void setAttachedList(List attachedList) {
		this.attachedList = attachedList;
	}
	/**
	 * 数据为任务状�?
	 */
	 public static Long IS_TASK_STATE=2L;
	
	/**
	 * 
	 * 数据位动态状�?
	 */
	public static Long IS_SHARE_STATE=1L;
	/**
	 *任务�?��状�?
	 */
	public static Long NOT_CLOSED=1L;
	
	/**
	 * 任务关闭状�?
	 */
	public static Long IS_CLOSED=2L;
	
	/**
	 * 任务不存在提�?
	 */
	public static String TASK_NOT_SAVE="您查找的任务不存�?";
}