package com.tfs.irp.leavechecker.entity;

import java.util.Date;

public class IrpCheckerLink {
	
	private Integer leavemarking;
    public Integer getLeavemarking() {
		return leavemarking;
	}

	public void setLeavemarking(Integer leavemarking) {
		this.leavemarking = leavemarking;
	}
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IRP_CHECKER_LINK.CHECKERLINKID
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    private Long checkerlinkid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IRP_CHECKER_LINK.LEAVEAPPLYID
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    private Long leaveapplyid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IRP_CHECKER_LINK.CRTIME
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    private Date crtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IRP_CHECKER_LINK.OPINION
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    private String opinion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IRP_CHECKER_LINK.NEXTUSERID
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    private Long nextuserid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IRP_CHECKER_LINK.STATUS
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IRP_CHECKER_LINK.CRUSERID
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    private Long cruserid;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IRP_CHECKER_LINK.CHECKERLINKID
     *
     * @return the value of IRP_CHECKER_LINK.CHECKERLINKID
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    public Long getCheckerlinkid() {
        return checkerlinkid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IRP_CHECKER_LINK.CHECKERLINKID
     *
     * @param checkerlinkid the value for IRP_CHECKER_LINK.CHECKERLINKID
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    public void setCheckerlinkid(Long checkerlinkid) {
        this.checkerlinkid = checkerlinkid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IRP_CHECKER_LINK.LEAVEAPPLYID
     *
     * @return the value of IRP_CHECKER_LINK.LEAVEAPPLYID
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    public Long getLeaveapplyid() {
        return leaveapplyid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IRP_CHECKER_LINK.LEAVEAPPLYID
     *
     * @param leaveapplyid the value for IRP_CHECKER_LINK.LEAVEAPPLYID
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    public void setLeaveapplyid(Long leaveapplyid) {
        this.leaveapplyid = leaveapplyid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IRP_CHECKER_LINK.CRTIME
     *
     * @return the value of IRP_CHECKER_LINK.CRTIME
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    public Date getCrtime() {
        return crtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IRP_CHECKER_LINK.CRTIME
     *
     * @param crtime the value for IRP_CHECKER_LINK.CRTIME
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    public void setCrtime(Date crtime) {
        this.crtime = crtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IRP_CHECKER_LINK.OPINION
     *
     * @return the value of IRP_CHECKER_LINK.OPINION
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    public String getOpinion() {
        return opinion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IRP_CHECKER_LINK.OPINION
     *
     * @param opinion the value for IRP_CHECKER_LINK.OPINION
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    public void setOpinion(String opinion) {
        this.opinion = opinion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IRP_CHECKER_LINK.NEXTUSERID
     *
     * @return the value of IRP_CHECKER_LINK.NEXTUSERID
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    public Long getNextuserid() {
        return nextuserid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IRP_CHECKER_LINK.NEXTUSERID
     *
     * @param nextuserid the value for IRP_CHECKER_LINK.NEXTUSERID
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    public void setNextuserid(Long nextuserid) {
        this.nextuserid = nextuserid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IRP_CHECKER_LINK.STATUS
     *
     * @return the value of IRP_CHECKER_LINK.STATUS
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IRP_CHECKER_LINK.STATUS
     *
     * @param status the value for IRP_CHECKER_LINK.STATUS
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IRP_CHECKER_LINK.CRUSERID
     *
     * @return the value of IRP_CHECKER_LINK.CRUSERID
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    public Long getCruserid() {
        return cruserid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IRP_CHECKER_LINK.CRUSERID
     *
     * @param cruserid the value for IRP_CHECKER_LINK.CRUSERID
     *
     * @ibatorgenerated Fri Sep 09 10:50:25 CST 2016
     */
    public void setCruserid(Long cruserid) {
        this.cruserid = cruserid;
    }
    
	/**
	 * 表名
	 */
	public static final String TABLENAME="IRP_CHECKER_LINK";
	
	
	/**
	 * 审核人审核状态的变更
	 */
	/**
	 * 已同意
	 */
	public static final Integer PASS=10;
	/**
	 * 未审核
	 */
	public static final Integer UNPASS=20;
	
	/**
	 * 拒绝
	 */
	public static final Integer REFUSE=30;
}