package com.tfs.irp.userapp.entity;

public class IrpUserapp {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_USER_APP.USERID
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	private Long userid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_USER_APP.APPLISTID
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	private Long applistid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_USER_APP.ISDISPLAY
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	private Integer isdisplay;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_USER_APP.USERID
	 * @return  the value of IRP_USER_APP.USERID
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_USER_APP.USERID
	 * @param userid  the value for IRP_USER_APP.USERID
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_USER_APP.APPLISTID
	 * @return  the value of IRP_USER_APP.APPLISTID
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	public Long getApplistid() {
		return applistid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_USER_APP.APPLISTID
	 * @param applistid  the value for IRP_USER_APP.APPLISTID
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	public void setApplistid(Long applistid) {
		this.applistid = applistid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_USER_APP.ISDISPLAY
	 * @return  the value of IRP_USER_APP.ISDISPLAY
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	public Integer getIsdisplay() {
		return isdisplay;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_USER_APP.ISDISPLAY
	 * @param isdisplay  the value for IRP_USER_APP.ISDISPLAY
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	public void setIsdisplay(Integer isdisplay) {
		this.isdisplay = isdisplay;
	}
}