package com.tfs.irp.termeditlog.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.tfs.irp.termeditlog.dao.IrpTermeditLogDAO;
import com.tfs.irp.termeditlog.entity.IrpTermeditLog;
import com.tfs.irp.termeditlog.entity.IrpTermeditLogExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.List;

public class IrpTermeditLogDAOImpl implements IrpTermeditLogDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table IRP_TERMEDIT_LOG
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_TERMEDIT_LOG
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public IrpTermeditLogDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_TERMEDIT_LOG
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public int countByExample(IrpTermeditLogExample example) throws SQLException {
        Integer count = (Integer) sqlMapClient.queryForObject("IRP_TERMEDIT_LOG.ibatorgenerated_countByExample",
                example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_TERMEDIT_LOG
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public int deleteByExample(IrpTermeditLogExample example) throws SQLException {
        int rows = sqlMapClient.delete("IRP_TERMEDIT_LOG.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_TERMEDIT_LOG
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public int deleteByPrimaryKey(Long termeditlogid) throws SQLException {
        IrpTermeditLog key = new IrpTermeditLog();
        key.setTermeditlogid(termeditlogid);
        int rows = sqlMapClient.delete("IRP_TERMEDIT_LOG.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_TERMEDIT_LOG
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public void insert(IrpTermeditLog record) throws SQLException {
        sqlMapClient.insert("IRP_TERMEDIT_LOG.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_TERMEDIT_LOG
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public void insertSelective(IrpTermeditLog record) throws SQLException {
        sqlMapClient.insert("IRP_TERMEDIT_LOG.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_TERMEDIT_LOG
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<IrpTermeditLog> selectByExample(IrpTermeditLogExample example, PageUtil pageUtil) throws SQLException {
        List<IrpTermeditLog> list = sqlMapClient.queryForList("IRP_TERMEDIT_LOG.ibatorgenerated_selectByExample",
                example, pageUtil.getPageIndex(), pageUtil.getPageSize());
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_TERMEDIT_LOG
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public IrpTermeditLog selectByPrimaryKey(Long termeditlogid) throws SQLException {
        IrpTermeditLog key = new IrpTermeditLog();
        key.setTermeditlogid(termeditlogid);
        IrpTermeditLog record = (IrpTermeditLog) sqlMapClient.queryForObject(
                "IRP_TERMEDIT_LOG.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_TERMEDIT_LOG
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public int updateByExampleSelective(IrpTermeditLog record, IrpTermeditLogExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("IRP_TERMEDIT_LOG.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_TERMEDIT_LOG
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public int updateByExample(IrpTermeditLog record, IrpTermeditLogExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("IRP_TERMEDIT_LOG.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_TERMEDIT_LOG
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public int updateByPrimaryKeySelective(IrpTermeditLog record) throws SQLException {
        int rows = sqlMapClient.update("IRP_TERMEDIT_LOG.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_TERMEDIT_LOG
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public int updateByPrimaryKey(IrpTermeditLog record) throws SQLException {
        int rows = sqlMapClient.update("IRP_TERMEDIT_LOG.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table IRP_TERMEDIT_LOG
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    private static class UpdateByExampleParms extends IrpTermeditLogExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpTermeditLogExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}