package com.tfs.irp.category.dao;

import com.tfs.irp.category.entity.IrpCategory;
import com.tfs.irp.category.entity.IrpCategoryExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

public interface IrpCategoryDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    int countByExample(IrpCategoryExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    int deleteByExample(IrpCategoryExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    int deleteByPrimaryKey(Long categoryid) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    void insert(IrpCategory record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    void insertSelective(IrpCategory record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    List<IrpCategory> selectByExample(IrpCategoryExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    IrpCategory selectByPrimaryKey(Long categoryid) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    int updateByExampleSelective(IrpCategory record, IrpCategoryExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    int updateByExample(IrpCategory record, IrpCategoryExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    int updateByPrimaryKeySelective(IrpCategory record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    int updateByPrimaryKey(IrpCategory record) throws SQLException;

    /**
     * 分页查询
     * @param example
     * @param page
     * @return
     */
    public List<IrpCategory> findCategoryByPage(IrpCategoryExample example, PageUtil page);

    /**
     * 调序
     * @param map
     */
    public void updateCategoryOrder(Map<String, Long> map);

    /**
     * 获得专家的分类集合
     * @param _nExpertId
     * @return
     */
    public List<IrpCategory> findCategoryByExpertId(Long _nExpertId);

    /** 
     * selectChildCategoryList:查询当前分类下的子分类. <br/> 
     * 
     * @author Administrator 
     * @param conditionIdList 当前的分类Id列表
     * @return 所有子分类
     * @since JDK 1.8 
     */
    List<IrpCategory> selectChildCategoryList(List<Long> conditionIdList) throws SQLException;

	List<IrpCategory> findAllCategoryByExpertId(String sql);
}