package com.tfs.irp.grouptestpaper.dao.impl;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.tfs.irp.grouptestpaper.dao.IrpGroupTestpaperDAO;
import com.tfs.irp.grouptestpaper.entity.IrpGroupTestpaper;
import com.tfs.irp.grouptestpaper.entity.IrpGroupTestpaperExample;
import com.tfs.irp.util.PageUtil;

public class IrpGroupTestpaperDAOImpl extends SqlMapClientDaoSupport implements IrpGroupTestpaperDAO {
  
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_group_testpaper
     *
     * @ibatorgenerated Mon Oct 13 14:34:08 CST 2014
     */
    public int countByExample(IrpGroupTestpaperExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("irp_group_testpaper.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_group_testpaper
     *
     * @ibatorgenerated Mon Oct 13 14:34:08 CST 2014
     */
    public int deleteByExample(IrpGroupTestpaperExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("irp_group_testpaper.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_group_testpaper
     *
     * @ibatorgenerated Mon Oct 13 14:34:08 CST 2014
     */
    public int deleteByPrimaryKey(Long grouptpaperid) throws SQLException {
        IrpGroupTestpaper key = new IrpGroupTestpaper();
        key.setGrouptpaperid(grouptpaperid);
        int rows = getSqlMapClientTemplate().delete("irp_group_testpaper.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_group_testpaper
     *
     * @ibatorgenerated Mon Oct 13 14:34:08 CST 2014
     */
    public void insert(IrpGroupTestpaper record) throws SQLException {
        getSqlMapClientTemplate().insert("irp_group_testpaper.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_group_testpaper
     *
     * @ibatorgenerated Mon Oct 13 14:34:08 CST 2014
     */
    public void insertSelective(IrpGroupTestpaper record) throws SQLException {
        getSqlMapClientTemplate().insert("irp_group_testpaper.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_group_testpaper
     *
     * @ibatorgenerated Mon Oct 13 14:34:08 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<IrpGroupTestpaper> selectByExample(IrpGroupTestpaperExample example) throws SQLException {
        List<IrpGroupTestpaper> list = getSqlMapClientTemplate().queryForList("irp_group_testpaper.ibatorgenerated_selectByExample", example);
        return list;
    }
    public List<IrpGroupTestpaper> selectByExample(IrpGroupTestpaperExample example,PageUtil _pageutil) throws SQLException {
        List<IrpGroupTestpaper> list = getSqlMapClientTemplate().queryForList("irp_group_testpaper.ibatorgenerated_selectByExample", example,_pageutil.getPageIndex(),_pageutil.getPageSize());
        return list;
    }
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_group_testpaper
     *
     * @ibatorgenerated Mon Oct 13 14:34:08 CST 2014
     */
    public IrpGroupTestpaper selectByPrimaryKey(Long grouptpaperid) throws SQLException {
        IrpGroupTestpaper key = new IrpGroupTestpaper();
        key.setGrouptpaperid(grouptpaperid);
        IrpGroupTestpaper record = (IrpGroupTestpaper) getSqlMapClientTemplate().queryForObject("irp_group_testpaper.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_group_testpaper
     *
     * @ibatorgenerated Mon Oct 13 14:34:08 CST 2014
     */
    public int updateByExampleSelective(IrpGroupTestpaper record, IrpGroupTestpaperExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_group_testpaper.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_group_testpaper
     *
     * @ibatorgenerated Mon Oct 13 14:34:08 CST 2014
     */
    public int updateByExample(IrpGroupTestpaper record, IrpGroupTestpaperExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_group_testpaper.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_group_testpaper
     *
     * @ibatorgenerated Mon Oct 13 14:34:08 CST 2014
     */
    public int updateByPrimaryKeySelective(IrpGroupTestpaper record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("irp_group_testpaper.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_group_testpaper
     *
     * @ibatorgenerated Mon Oct 13 14:34:08 CST 2014
     */
    public int updateByPrimaryKey(IrpGroupTestpaper record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("irp_group_testpaper.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table irp_group_testpaper
     *
     * @ibatorgenerated Mon Oct 13 14:34:08 CST 2014
     */
    private static class UpdateByExampleParms extends IrpGroupTestpaperExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpGroupTestpaperExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}