package com.tfs.irp.forumcomment.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.tfs.irp.forumcomment.dao.IrpForumCommentDAO;
import com.tfs.irp.forumcomment.entity.IrpForumComment;
import com.tfs.irp.forumcomment.entity.IrpForumCommentExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.List;

public class IrpForumCommentDAOImpl implements IrpForumCommentDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table IRP_FORUM_COMMENT
     *
     * @ibatorgenerated Tue Sep 26 15:06:31 CST 2017
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_FORUM_COMMENT
     *
     * @ibatorgenerated Tue Sep 26 15:06:31 CST 2017
     */
    public IrpForumCommentDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_FORUM_COMMENT
     *
     * @ibatorgenerated Tue Sep 26 15:06:31 CST 2017
     */
    public int countByExample(IrpForumCommentExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("IRP_FORUM_COMMENT.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_FORUM_COMMENT
     *
     * @ibatorgenerated Tue Sep 26 15:06:31 CST 2017
     */
    public int deleteByExample(IrpForumCommentExample example) throws SQLException {
        int rows = sqlMapClient.delete("IRP_FORUM_COMMENT.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_FORUM_COMMENT
     *
     * @ibatorgenerated Tue Sep 26 15:06:31 CST 2017
     */
    public int deleteByPrimaryKey(Long fcid) throws SQLException {
        IrpForumComment key = new IrpForumComment();
        key.setFcid(fcid);
        int rows = sqlMapClient.delete("IRP_FORUM_COMMENT.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_FORUM_COMMENT
     *
     * @ibatorgenerated Tue Sep 26 15:06:31 CST 2017
     */
    public void insert(IrpForumComment record) throws SQLException {
        sqlMapClient.insert("IRP_FORUM_COMMENT.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_FORUM_COMMENT
     *
     * @ibatorgenerated Tue Sep 26 15:06:31 CST 2017
     */
    public void insertSelective(IrpForumComment record) throws SQLException {
        sqlMapClient.insert("IRP_FORUM_COMMENT.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_FORUM_COMMENT
     *
     * @ibatorgenerated Tue Sep 26 15:06:31 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<IrpForumComment> selectByExample(IrpForumCommentExample example, PageUtil pageUtil) throws SQLException {
        List<IrpForumComment> list = sqlMapClient.queryForList("IRP_FORUM_COMMENT.ibatorgenerated_selectByExample", example, pageUtil.getPageIndex(), pageUtil.getPageSize());
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_FORUM_COMMENT
     *
     * @ibatorgenerated Tue Sep 26 15:06:31 CST 2017
     */
    public IrpForumComment selectByPrimaryKey(Long fcid) throws SQLException {
        IrpForumComment key = new IrpForumComment();
        key.setFcid(fcid);
        IrpForumComment record = (IrpForumComment) sqlMapClient.queryForObject("IRP_FORUM_COMMENT.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_FORUM_COMMENT
     *
     * @ibatorgenerated Tue Sep 26 15:06:31 CST 2017
     */
    public int updateByExampleSelective(IrpForumComment record, IrpForumCommentExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("IRP_FORUM_COMMENT.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_FORUM_COMMENT
     *
     * @ibatorgenerated Tue Sep 26 15:06:31 CST 2017
     */
    public int updateByExample(IrpForumComment record, IrpForumCommentExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("IRP_FORUM_COMMENT.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_FORUM_COMMENT
     *
     * @ibatorgenerated Tue Sep 26 15:06:31 CST 2017
     */
    public int updateByPrimaryKeySelective(IrpForumComment record) throws SQLException {
        int rows = sqlMapClient.update("IRP_FORUM_COMMENT.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_FORUM_COMMENT
     *
     * @ibatorgenerated Tue Sep 26 15:06:31 CST 2017
     */
    public int updateByPrimaryKey(IrpForumComment record) throws SQLException {
        int rows = sqlMapClient.update("IRP_FORUM_COMMENT.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table IRP_FORUM_COMMENT
     *
     * @ibatorgenerated Tue Sep 26 15:06:31 CST 2017
     */
    private static class UpdateByExampleParms extends IrpForumCommentExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpForumCommentExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}