package com.tfs.irp.logs.dao.impl;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.tfs.irp.logs.dao.IrpLogsDAO;
import com.tfs.irp.logs.entity.IrpLogs;
import com.tfs.irp.logs.entity.IrpLogsExample;
import com.tfs.irp.util.PageUtil;

public class IrpLogsDAOImpl extends SqlMapClientDaoSupport implements IrpLogsDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGS
	 * @ibatorgenerated  Mon Mar 25 09:27:48 CST 2013
	 */
	public int countByExample(IrpLogsExample example) throws SQLException {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"IRP_LOGS.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGS
	 * @ibatorgenerated  Mon Mar 25 09:27:48 CST 2013
	 */
	public int deleteByExample(IrpLogsExample example) throws SQLException {
		int rows = getSqlMapClientTemplate().delete(
				"IRP_LOGS.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGS
	 * @ibatorgenerated  Mon Mar 25 09:27:48 CST 2013
	 */
	public int deleteByPrimaryKey(Long logid) throws SQLException {
		IrpLogs key = new IrpLogs();
		key.setLogid(logid);
		int rows = getSqlMapClientTemplate().delete(
				"IRP_LOGS.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGS
	 * @ibatorgenerated  Mon Mar 25 09:27:48 CST 2013
	 */
	public void insert(IrpLogs record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_LOGS.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGS
	 * @ibatorgenerated  Mon Mar 25 09:27:48 CST 2013
	 */
	public void insertSelective(IrpLogs record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_LOGS.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGS
	 * @ibatorgenerated  Mon Mar 25 09:27:48 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<IrpLogs> selectByExample(IrpLogsExample example)
			throws SQLException {
		List<IrpLogs> list = getSqlMapClientTemplate().queryForList(
				"IRP_LOGS.ibatorgenerated_selectByExample", example);
		return list;
	}
	@Override
	public List<Long> selectUserIdsByExample(IrpLogsExample example) throws SQLException {
		List<Long> list = getSqlMapClientTemplate().queryForList(
				"IRP_LOGS.ibatorgenerated_selectUserIdsByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGS
	 * @ibatorgenerated  Mon Mar 25 09:27:48 CST 2013
	 */
	public IrpLogs selectByPrimaryKey(Long logid) throws SQLException {
		IrpLogs key = new IrpLogs();
		key.setLogid(logid);
		IrpLogs record = (IrpLogs) getSqlMapClientTemplate().queryForObject(
				"IRP_LOGS.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGS
	 * @ibatorgenerated  Mon Mar 25 09:27:48 CST 2013
	 */
	public int updateByExampleSelective(IrpLogs record, IrpLogsExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_LOGS.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGS
	 * @ibatorgenerated  Mon Mar 25 09:27:48 CST 2013
	 */
	public int updateByExample(IrpLogs record, IrpLogsExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_LOGS.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGS
	 * @ibatorgenerated  Mon Mar 25 09:27:48 CST 2013
	 */
	public int updateByPrimaryKeySelective(IrpLogs record) throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"IRP_LOGS.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGS
	 * @ibatorgenerated  Mon Mar 25 09:27:48 CST 2013
	 */
	public int updateByPrimaryKey(IrpLogs record) throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"IRP_LOGS.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table IRP_LOGS
	 * @ibatorgenerated  Mon Mar 25 09:27:48 CST 2013
	 */
	private static class UpdateByExampleParms extends IrpLogsExample {
		private Object record;

		public UpdateByExampleParms(Object record, IrpLogsExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@SuppressWarnings("unchecked")
    public List<IrpLogs> selectByExample(IrpLogsExample example,PageUtil pageUtil) throws SQLException {
		List<IrpLogs> list =null;
		if(pageUtil!=null){
			 list = getSqlMapClientTemplate().queryForList("IRP_LOGS.ibatorgenerated_selectByExample", example,pageUtil.getPageIndex(),pageUtil.getPageSize());
		}else{
			 list = getSqlMapClientTemplate().queryForList( "IRP_LOGS.ibatorgenerated_selectByExample", example);
		}
       return list;
    }

}