package com.tfs.irp.career.dao;

import com.tfs.irp.career.entity.IrpCareer;
import com.tfs.irp.career.entity.IrpCareerExample;
import java.sql.SQLException;
import java.util.List;

public interface IrpCareerDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    int countByExample(IrpCareerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    int deleteByExample(IrpCareerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    int deleteByPrimaryKey(Long careerid) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    void insert(IrpCareer record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    void insertSelective(IrpCareer record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    List<IrpCareer> selectByExample(IrpCareerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    IrpCareer selectByPrimaryKey(Long careerid) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    int updateByExampleSelective(IrpCareer record, IrpCareerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    int updateByExample(IrpCareer record, IrpCareerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    int updateByPrimaryKeySelective(IrpCareer record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    int updateByPrimaryKey(IrpCareer record) throws SQLException;
}