package com.tfs.irp.asseroomsb.entity;

import java.util.Date;

import com.tfs.irp.base.IrpBaseObj;

public class IrpAsseroomsb extends IrpBaseObj{

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_ASSEROOMSB.ASSEROOMSBID
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	private Long asseroomsbid;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_ASSEROOMSB.ASSEROOMSBNAME
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	private String asseroomsbname;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_ASSEROOMSB.ASSEROOMSBDESC
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	private String asseroomsbdesc;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_ASSEROOMSB.ASSEROOMSBUSE
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	private String asseroomsbuse;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_ASSEROOMSB.ASSEROOMSBTYPE
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	private String asseroomsbtype;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_ASSEROOMSB.ASSEROOMSBSTATUS
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	private Integer asseroomsbstatus;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_ASSEROOMSB.CRTIME
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	private Date crtime;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_ASSEROOMSB.CRUSERID
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	private Long cruserid;
	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_ASSEROOMSB.ASSEROOMSBID
	 * @return  the value of IRP_ASSEROOMSB.ASSEROOMSBID
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public Long getAsseroomsbid() {
		return asseroomsbid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_ASSEROOMSB.ASSEROOMSBID
	 * @param asseroomsbid  the value for IRP_ASSEROOMSB.ASSEROOMSBID
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public void setAsseroomsbid(Long asseroomsbid) {
		this.asseroomsbid = asseroomsbid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_ASSEROOMSB.ASSEROOMSBNAME
	 * @return  the value of IRP_ASSEROOMSB.ASSEROOMSBNAME
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public String getAsseroomsbname() {
		return asseroomsbname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_ASSEROOMSB.ASSEROOMSBNAME
	 * @param asseroomsbname  the value for IRP_ASSEROOMSB.ASSEROOMSBNAME
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public void setAsseroomsbname(String asseroomsbname) {
		this.asseroomsbname = asseroomsbname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_ASSEROOMSB.ASSEROOMSBDESC
	 * @return  the value of IRP_ASSEROOMSB.ASSEROOMSBDESC
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public String getAsseroomsbdesc() {
		return asseroomsbdesc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_ASSEROOMSB.ASSEROOMSBDESC
	 * @param asseroomsbdesc  the value for IRP_ASSEROOMSB.ASSEROOMSBDESC
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public void setAsseroomsbdesc(String asseroomsbdesc) {
		this.asseroomsbdesc = asseroomsbdesc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_ASSEROOMSB.ASSEROOMSBUSE
	 * @return  the value of IRP_ASSEROOMSB.ASSEROOMSBUSE
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public String getAsseroomsbuse() {
		return asseroomsbuse;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_ASSEROOMSB.ASSEROOMSBUSE
	 * @param asseroomsbuse  the value for IRP_ASSEROOMSB.ASSEROOMSBUSE
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public void setAsseroomsbuse(String asseroomsbuse) {
		this.asseroomsbuse = asseroomsbuse;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_ASSEROOMSB.ASSEROOMSBTYPE
	 * @return  the value of IRP_ASSEROOMSB.ASSEROOMSBTYPE
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public String getAsseroomsbtype() {
		return asseroomsbtype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_ASSEROOMSB.ASSEROOMSBTYPE
	 * @param asseroomsbtype  the value for IRP_ASSEROOMSB.ASSEROOMSBTYPE
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public void setAsseroomsbtype(String asseroomsbtype) {
		this.asseroomsbtype = asseroomsbtype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_ASSEROOMSB.ASSEROOMSBSTATUS
	 * @return  the value of IRP_ASSEROOMSB.ASSEROOMSBSTATUS
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public Integer getAsseroomsbstatus() {
		return asseroomsbstatus;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_ASSEROOMSB.ASSEROOMSBSTATUS
	 * @param asseroomsbstatus  the value for IRP_ASSEROOMSB.ASSEROOMSBSTATUS
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public void setAsseroomsbstatus(Integer asseroomsbstatus) {
		this.asseroomsbstatus = asseroomsbstatus;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_ASSEROOMSB.CRTIME
	 * @return  the value of IRP_ASSEROOMSB.CRTIME
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public Date getCrtime() {
		return crtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_ASSEROOMSB.CRTIME
	 * @param crtime  the value for IRP_ASSEROOMSB.CRTIME
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public void setCrtime(Date crtime) {
		this.crtime = crtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_ASSEROOMSB.CRUSERID
	 * @return  the value of IRP_ASSEROOMSB.CRUSERID
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public Long getCruserid() {
		return cruserid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_ASSEROOMSB.CRUSERID
	 * @param cruserid  the value for IRP_ASSEROOMSB.CRUSERID
	 * @ibatorgenerated  Tue Aug 23 14:25:05 CST 2016
	 */
	public void setCruserid(Long cruserid) {
		this.cruserid = cruserid;
	}

	/** 对象表名 **/
    public final static String TABLE_NAME = "IRP_ASSEROOMSB";
    
    /** 主键字段�?**/
    public final static String ID_FIELD_NAME = "ASSEROOMSBID";
	@Override
	public Long getId() {
		// TODO Auto-generated method stub
		return asseroomsbid;
	}

	@Override
	public String getName() {
		// TODO Auto-generated method stub
		return asseroomsbname;
	}

	@Override
	public String getTableName() {
		// TODO Auto-generated method stub
		return TABLE_NAME;
	}

	@Override
	public String getIdFieldName() {
		// TODO Auto-generated method stub
		return ID_FIELD_NAME;
	}
}