package com.tfs.irp.questionbank.dao;

import java.sql.SQLException;
import java.util.List;

import com.tfs.irp.questionbank.entity.IrpQuestionBank;
import com.tfs.irp.questionbank.entity.IrpQuestionBankExample;
import com.tfs.irp.util.PageUtil;

public interface IrpQuestionBankDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_question_bank
	 * @ibatorgenerated  Fri Sep 05 10:59:05 CST 2014
	 */
	int countByExample(IrpQuestionBankExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_question_bank
	 * @ibatorgenerated  Fri Sep 05 10:59:05 CST 2014
	 */
	int deleteByExample(IrpQuestionBankExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_question_bank
	 * @ibatorgenerated  Fri Sep 05 10:59:05 CST 2014
	 */
	int deleteByPrimaryKey(Long qbankid) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_question_bank
	 * @ibatorgenerated  Fri Sep 05 10:59:05 CST 2014
	 */
	void insert(IrpQuestionBank record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_question_bank
	 * @ibatorgenerated  Fri Sep 05 10:59:05 CST 2014
	 */
	void insertSelective(IrpQuestionBank record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_question_bank
	 * @ibatorgenerated  Fri Sep 05 10:59:05 CST 2014
	 */
	List<IrpQuestionBank> selectByExample(IrpQuestionBankExample example)
			throws SQLException;
	List<IrpQuestionBank> selectByExample(IrpQuestionBankExample example,PageUtil pageUtil)
			throws SQLException;
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_question_bank
	 * @ibatorgenerated  Fri Sep 05 10:59:05 CST 2014
	 */
	IrpQuestionBank selectByPrimaryKey(Long qbankid) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_question_bank
	 * @ibatorgenerated  Fri Sep 05 10:59:05 CST 2014
	 */
	int updateByExampleSelective(IrpQuestionBank record,
			IrpQuestionBankExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_question_bank
	 * @ibatorgenerated  Fri Sep 05 10:59:05 CST 2014
	 */
	int updateByExample(IrpQuestionBank record, IrpQuestionBankExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_question_bank
	 * @ibatorgenerated  Fri Sep 05 10:59:05 CST 2014
	 */
	int updateByPrimaryKeySelective(IrpQuestionBank record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_question_bank
	 * @ibatorgenerated  Fri Sep 05 10:59:05 CST 2014
	 */
	int updateByPrimaryKey(IrpQuestionBank record) throws SQLException;
	/**
	 * 随机选择指定数量和类型的题型
	 * @param Qtype
	 * @param Num
	 * @return
	 * @throws SQLException
	 * @author   npz
	 * @date 2017年8月3日
	 */
	List<IrpQuestionBank> randomtestpaper(Integer qtype,int num) throws SQLException;
}