package com.tfs.irp.file.dao.impl;

import com.tfs.irp.file.dao.IrpUserFileDAO;
import com.tfs.irp.file.entity.IrpUserFile;
import com.tfs.irp.file.entity.IrpUserFileExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpUserFileDAOImpl extends SqlMapClientDaoSupport implements IrpUserFileDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USER_FILE
     *
     * @ibatorgenerated Thu May 16 10:06:59 CST 2013
     */
    public int countByExample(IrpUserFileExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_USER_FILE.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USER_FILE
     *
     * @ibatorgenerated Thu May 16 10:06:59 CST 2013
     */
    public int deleteByExample(IrpUserFileExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_USER_FILE.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USER_FILE
     *
     * @ibatorgenerated Thu May 16 10:06:59 CST 2013
     */
    public int deleteByPrimaryKey(Long userfileid) throws SQLException {
        IrpUserFile key = new IrpUserFile();
        key.setUserfileid(userfileid);
        int rows = getSqlMapClientTemplate().delete("IRP_USER_FILE.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USER_FILE
     *
     * @ibatorgenerated Thu May 16 10:06:59 CST 2013
     */
    public void insert(IrpUserFile record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_USER_FILE.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USER_FILE
     *
     * @ibatorgenerated Thu May 16 10:06:59 CST 2013
     */
    public void insertSelective(IrpUserFile record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_USER_FILE.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USER_FILE
     *
     * @ibatorgenerated Thu May 16 10:06:59 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<IrpUserFile> selectByExample(IrpUserFileExample example) throws SQLException {
        List<IrpUserFile> list = getSqlMapClientTemplate().queryForList("IRP_USER_FILE.ibatorgenerated_selectByExample", example);
        return list;
    }
    @Override
    public List<IrpUserFile> selectByExample(IrpUserFileExample example,PageUtil pageUtil) throws SQLException {
        List<IrpUserFile> list = getSqlMapClientTemplate().queryForList("IRP_USER_FILE.ibatorgenerated_selectByExample", example,pageUtil.getPageIndex(),pageUtil.getPageSize());
        return list;
    }
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USER_FILE
     *
     * @ibatorgenerated Thu May 16 10:06:59 CST 2013
     */
    public IrpUserFile selectByPrimaryKey(Long userfileid) throws SQLException {
        IrpUserFile key = new IrpUserFile();
        key.setUserfileid(userfileid);
        IrpUserFile record = (IrpUserFile) getSqlMapClientTemplate().queryForObject("IRP_USER_FILE.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USER_FILE
     *
     * @ibatorgenerated Thu May 16 10:06:59 CST 2013
     */
    public int updateByExampleSelective(IrpUserFile record, IrpUserFileExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_USER_FILE.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USER_FILE
     *
     * @ibatorgenerated Thu May 16 10:06:59 CST 2013
     */
    public int updateByExample(IrpUserFile record, IrpUserFileExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_USER_FILE.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USER_FILE
     *
     * @ibatorgenerated Thu May 16 10:06:59 CST 2013
     */
    public int updateByPrimaryKeySelective(IrpUserFile record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_USER_FILE.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_USER_FILE
     *
     * @ibatorgenerated Thu May 16 10:06:59 CST 2013
     */
    public int updateByPrimaryKey(IrpUserFile record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_USER_FILE.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table IRP_USER_FILE
     *
     * @ibatorgenerated Thu May 16 10:06:59 CST 2013
     */
    private static class UpdateByExampleParms extends IrpUserFileExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpUserFileExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}