package com.tfs.irp.examrecord.dao.impl;

import com.tfs.irp.examrecord.dao.IrpExamRecordDAO;
import com.tfs.irp.examrecord.entity.IrpExamRecord;
import com.tfs.irp.examrecord.entity.IrpExamRecordExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpExamRecordDAOImpl  extends SqlMapClientDaoSupport  implements IrpExamRecordDAO {
   
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_exam_record
     *
     * @ibatorgenerated Thu Oct 30 09:59:08 CST 2014
     */
    public int countByExample(IrpExamRecordExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("irp_exam_record.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_exam_record
     *
     * @ibatorgenerated Thu Oct 30 09:59:08 CST 2014
     */
    public int deleteByExample(IrpExamRecordExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("irp_exam_record.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_exam_record
     *
     * @ibatorgenerated Thu Oct 30 09:59:08 CST 2014
     */
    public int deleteByPrimaryKey(Long recordid) throws SQLException {
        IrpExamRecord key = new IrpExamRecord();
        key.setRecordid(recordid);
        int rows = getSqlMapClientTemplate().delete("irp_exam_record.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_exam_record
     *
     * @ibatorgenerated Thu Oct 30 09:59:08 CST 2014
     */
    public void insert(IrpExamRecord record) throws SQLException {
        getSqlMapClientTemplate().insert("irp_exam_record.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_exam_record
     *
     * @ibatorgenerated Thu Oct 30 09:59:08 CST 2014
     */
    public void insertSelective(IrpExamRecord record) throws SQLException {
        getSqlMapClientTemplate().insert("irp_exam_record.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_exam_record
     *
     * @ibatorgenerated Thu Oct 30 09:59:08 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<IrpExamRecord> selectByExample(IrpExamRecordExample example) throws SQLException {
        List<IrpExamRecord> list = getSqlMapClientTemplate().queryForList("irp_exam_record.ibatorgenerated_selectByExample", example);
        return list;
    }
	@Override
	public List<IrpExamRecord> selectByExample(IrpExamRecordExample example,
			PageUtil _pageutil) throws SQLException {
		// TODO Auto-generated method stub
        List<IrpExamRecord> list = getSqlMapClientTemplate().queryForList("irp_exam_record.ibatorgenerated_selectByExample", example,_pageutil.getPageIndex(),_pageutil.getPageSize());
        return list;
	}
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_exam_record
     *
     * @ibatorgenerated Thu Oct 30 09:59:08 CST 2014
     */
    public IrpExamRecord selectByPrimaryKey(Long recordid) throws SQLException {
        IrpExamRecord key = new IrpExamRecord();
        key.setRecordid(recordid);
        IrpExamRecord record = (IrpExamRecord) getSqlMapClientTemplate().queryForObject("irp_exam_record.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_exam_record
     *
     * @ibatorgenerated Thu Oct 30 09:59:08 CST 2014
     */
    public int updateByExampleSelective(IrpExamRecord record, IrpExamRecordExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_exam_record.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_exam_record
     *
     * @ibatorgenerated Thu Oct 30 09:59:08 CST 2014
     */
    public int updateByExample(IrpExamRecord record, IrpExamRecordExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_exam_record.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_exam_record
     *
     * @ibatorgenerated Thu Oct 30 09:59:08 CST 2014
     */
    public int updateByPrimaryKeySelective(IrpExamRecord record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("irp_exam_record.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_exam_record
     *
     * @ibatorgenerated Thu Oct 30 09:59:08 CST 2014
     */
    public int updateByPrimaryKey(IrpExamRecord record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("irp_exam_record.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table irp_exam_record
     *
     * @ibatorgenerated Thu Oct 30 09:59:08 CST 2014
     */
    private static class UpdateByExampleParms extends IrpExamRecordExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpExamRecordExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}