package com.tfs.irp.userapp.dao.impl;

import com.tfs.irp.userapp.dao.IrpUserappDAO;
import com.tfs.irp.userapp.entity.IrpUserapp;
import com.tfs.irp.userapp.entity.IrpUserappExample;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpUserappDAOImpl extends SqlMapClientDaoSupport implements IrpUserappDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_USER_APP
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	public int countByExample(IrpUserappExample example) throws SQLException {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"IRP_USER_APP.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_USER_APP
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	public int deleteByExample(IrpUserappExample example) throws SQLException {
		int rows = getSqlMapClientTemplate().delete(
				"IRP_USER_APP.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_USER_APP
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	public void insert(IrpUserapp record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_USER_APP.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_USER_APP
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	public void insertSelective(IrpUserapp record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_USER_APP.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_USER_APP
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<IrpUserapp> selectByExample(IrpUserappExample example)
			throws SQLException {
		List<IrpUserapp> list = getSqlMapClientTemplate().queryForList(
				"IRP_USER_APP.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_USER_APP
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	public int updateByExampleSelective(IrpUserapp record,
			IrpUserappExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_USER_APP.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_USER_APP
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	public int updateByExample(IrpUserapp record, IrpUserappExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_USER_APP.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table IRP_USER_APP
	 * @ibatorgenerated  Fri Oct 11 11:05:19 CST 2013
	 */
	private static class UpdateByExampleParms extends IrpUserappExample {
		private Object record;

		public UpdateByExampleParms(Object record, IrpUserappExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public void updateAppdisplay(Map<String,Long> map) {
		getSqlMapClientTemplate().update("IRP_USER_APP.ibatorgenerated_updateBydisplay", map);
	}

}