package com.tfs.irp.career.dao.impl;

import com.tfs.irp.career.dao.IrpCareerDAO;
import com.tfs.irp.career.entity.IrpCareer;
import com.tfs.irp.career.entity.IrpCareerExample;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpCareerDAOImpl extends SqlMapClientDaoSupport implements IrpCareerDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    public int countByExample(IrpCareerExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_CAREER.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    public int deleteByExample(IrpCareerExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_CAREER.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    public int deleteByPrimaryKey(Long careerid) throws SQLException {
        IrpCareer key = new IrpCareer();
        key.setCareerid(careerid);
        int rows = getSqlMapClientTemplate().delete("IRP_CAREER.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    public void insert(IrpCareer record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_CAREER.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    public void insertSelective(IrpCareer record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_CAREER.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<IrpCareer> selectByExample(IrpCareerExample example) throws SQLException {
        List<IrpCareer> list = getSqlMapClientTemplate().queryForList("IRP_CAREER.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    public IrpCareer selectByPrimaryKey(Long careerid) throws SQLException {
        IrpCareer key = new IrpCareer();
        key.setCareerid(careerid);
        IrpCareer record = (IrpCareer) getSqlMapClientTemplate().queryForObject("IRP_CAREER.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    public int updateByExampleSelective(IrpCareer record, IrpCareerExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_CAREER.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    public int updateByExample(IrpCareer record, IrpCareerExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_CAREER.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    public int updateByPrimaryKeySelective(IrpCareer record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_CAREER.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    public int updateByPrimaryKey(IrpCareer record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_CAREER.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table IRP_CAREER
     *
     * @ibatorgenerated Mon Apr 22 10:25:13 CST 2013
     */
    private static class UpdateByExampleParms extends IrpCareerExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpCareerExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}