package com.tfs.irp.microblogcollection.dao.impl;

import com.tfs.irp.microblogcollection.dao.IrpMicroblogCollectionDAO;
import com.tfs.irp.microblogcollection.entity.IrpMicroblogCollectionExample;
import com.tfs.irp.microblogcollection.entity.IrpMicroblogCollectionKey;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpMicroblogCollectionDAOImpl extends SqlMapClientDaoSupport implements IrpMicroblogCollectionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    public int countByExample(IrpMicroblogCollectionExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_MICROBLOG_COLLECTION.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    public int deleteByExample(IrpMicroblogCollectionExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_MICROBLOG_COLLECTION.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    public int deleteByPrimaryKey(IrpMicroblogCollectionKey key) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_MICROBLOG_COLLECTION.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    public void insert(IrpMicroblogCollectionKey record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_MICROBLOG_COLLECTION.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    public void insertSelective(IrpMicroblogCollectionKey record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_MICROBLOG_COLLECTION.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<IrpMicroblogCollectionKey> selectByExample(IrpMicroblogCollectionExample example) throws SQLException {
        List<IrpMicroblogCollectionKey> list = getSqlMapClientTemplate().queryForList("IRP_MICROBLOG_COLLECTION.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    public int updateByExampleSelective(IrpMicroblogCollectionKey record, IrpMicroblogCollectionExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_MICROBLOG_COLLECTION.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    public int updateByExample(IrpMicroblogCollectionKey record, IrpMicroblogCollectionExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_MICROBLOG_COLLECTION.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    private static class UpdateByExampleParms extends IrpMicroblogCollectionExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpMicroblogCollectionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
	@Override
	public List selectMicroblogidOfUserid(Long _userid)
			throws SQLException {
		Map map = new HashMap();
		map.put("userid", _userid);
		List microblogcoll = new ArrayList();
		List list = this.getSqlMapClientTemplate().queryForList("IRP_MICROBLOG_COLLECTION.ibatorgenerated_selectByMicroblogIdOfUserid",map);
		for (int i = 0; i < list.size(); i++) {
			Map map1 = (Map) list.get(i);
			microblogcoll.add(map1.values().toString().replace("[","").replace("]",""));
		}
		return microblogcoll;
	}
}