package com.tfs.irp.selectkey.dao.impl;

import com.tfs.irp.selectkey.dao.IrpSelectKeyDAO;
import com.tfs.irp.selectkey.entity.IrpSelectKey;
import com.tfs.irp.selectkey.entity.IrpSelectKeyExample;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpSelectKeyDAOImpl extends SqlMapClientDaoSupport  implements IrpSelectKeyDAO {
	  @Override
	    public List<String> selectTagByUserIdDesc(long _nUserId) throws SQLException {
	        List<String> list = getSqlMapClientTemplate().queryForList("IRP_SELECT_KEY.selectByUserIdDesc", _nUserId);
	        return list;
	    }
	  @Override
	  public List<String> selectByUserIdOrderbyCountDescBetweenTime(Map<String, Object> map)throws SQLException{
		  List<String> list=getSqlMapClientTemplate().queryForList("IRP_SELECT_KEY.selectByUserIdOrderbyCountDescBetweenTime",map);
		  return list;
	  }
 
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_SELECT_KEY
	 * @ibatorgenerated  Thu Aug 15 17:44:44 CST 2013
	 */
	public int countByExample(IrpSelectKeyExample example) throws SQLException {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"IRP_SELECT_KEY.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_SELECT_KEY
	 * @ibatorgenerated  Thu Aug 15 17:44:44 CST 2013
	 */
	public int deleteByExample(IrpSelectKeyExample example) throws SQLException {
		int rows = getSqlMapClientTemplate().delete(
				"IRP_SELECT_KEY.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_SELECT_KEY
	 * @ibatorgenerated  Thu Aug 15 17:44:44 CST 2013
	 */
	public int deleteByPrimaryKey(Long sid) throws SQLException {
		IrpSelectKey key = new IrpSelectKey();
		key.setSid(sid);
		int rows = getSqlMapClientTemplate().delete(
				"IRP_SELECT_KEY.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_SELECT_KEY
	 * @ibatorgenerated  Thu Aug 15 17:44:44 CST 2013
	 */
	public void insert(IrpSelectKey record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_SELECT_KEY.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_SELECT_KEY
	 * @ibatorgenerated  Thu Aug 15 17:44:44 CST 2013
	 */
	public void insertSelective(IrpSelectKey record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_SELECT_KEY.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_SELECT_KEY
	 * @ibatorgenerated  Thu Aug 15 17:44:44 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<IrpSelectKey> selectByExample(IrpSelectKeyExample example)
			throws SQLException {
		List<IrpSelectKey> list = getSqlMapClientTemplate().queryForList(
				"IRP_SELECT_KEY.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_SELECT_KEY
	 * @ibatorgenerated  Thu Aug 15 17:44:44 CST 2013
	 */
	public IrpSelectKey selectByPrimaryKey(Long sid) throws SQLException {
		IrpSelectKey key = new IrpSelectKey();
		key.setSid(sid);
		IrpSelectKey record = (IrpSelectKey) getSqlMapClientTemplate().queryForObject(
				"IRP_SELECT_KEY.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_SELECT_KEY
	 * @ibatorgenerated  Thu Aug 15 17:44:44 CST 2013
	 */
	public int updateByExampleSelective(IrpSelectKey record,
			IrpSelectKeyExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_SELECT_KEY.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_SELECT_KEY
	 * @ibatorgenerated  Thu Aug 15 17:44:44 CST 2013
	 */
	public int updateByExample(IrpSelectKey record, IrpSelectKeyExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_SELECT_KEY.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_SELECT_KEY
	 * @ibatorgenerated  Thu Aug 15 17:44:44 CST 2013
	 */
	public int updateByPrimaryKeySelective(IrpSelectKey record)
			throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"IRP_SELECT_KEY.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_SELECT_KEY
	 * @ibatorgenerated  Thu Aug 15 17:44:44 CST 2013
	 */
	public int updateByPrimaryKey(IrpSelectKey record) throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"IRP_SELECT_KEY.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table IRP_SELECT_KEY
	 * @ibatorgenerated  Thu Aug 15 17:44:44 CST 2013
	 */
	private static class UpdateByExampleParms extends IrpSelectKeyExample {
		private Object record;

		public UpdateByExampleParms(Object record, IrpSelectKeyExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}