package com.tfs.irp.category.dao.impl;

import com.tfs.irp.category.dao.IrpCategoryDAO;
import com.tfs.irp.category.entity.IrpCategory;
import com.tfs.irp.category.entity.IrpCategoryExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpCategoryDAOImpl extends SqlMapClientDaoSupport implements IrpCategoryDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public int countByExample(IrpCategoryExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("irp_category.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public int deleteByExample(IrpCategoryExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("irp_category.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public int deleteByPrimaryKey(Long categoryid) throws SQLException {
        IrpCategory key = new IrpCategory();
        key.setCategoryid(categoryid);
        int rows = getSqlMapClientTemplate().delete("irp_category.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public void insert(IrpCategory record) throws SQLException {
    	getSqlMapClientTemplate().insert("irp_category.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public void insertSelective(IrpCategory record) throws SQLException {
    	getSqlMapClientTemplate().insert("irp_category.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<IrpCategory> selectByExample(IrpCategoryExample example) throws SQLException {
        List<IrpCategory> list = getSqlMapClientTemplate().queryForList("irp_category.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public IrpCategory selectByPrimaryKey(Long categoryid) throws SQLException {
        IrpCategory key = new IrpCategory();
        key.setCategoryid(categoryid);
        IrpCategory record = (IrpCategory) getSqlMapClientTemplate().queryForObject("irp_category.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public int updateByExampleSelective(IrpCategory record, IrpCategoryExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_category.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public int updateByExample(IrpCategory record, IrpCategoryExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_category.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public int updateByPrimaryKeySelective(IrpCategory record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("irp_category.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    public int updateByPrimaryKey(IrpCategory record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("irp_category.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table irp_category
     *
     * @ibatorgenerated Wed Mar 19 09:23:56 CST 2014
     */
    private static class UpdateByExampleParms extends IrpCategoryExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpCategoryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    @Override
	public List<IrpCategory> findCategoryByPage(IrpCategoryExample example,
			PageUtil page) {
		List<IrpCategory> list = getSqlMapClientTemplate().queryForList("irp_category.ibatorgenerated_selectByExample", example, page.getPageIndex(), page.getPageSize());
        return list;
	}
    
    /**
     * 调序
     * @param map
     */
    public void updateCategoryOrder(Map<String , Long> map){
    	getSqlMapClientTemplate().update("irp_category.updateCategoryOrder", map);
    }
    
    @Override
    public List<IrpCategory> findCategoryByExpertId(Long _nExpertId) {
    	List<IrpCategory> list = getSqlMapClientTemplate().queryForList("irp_category.selectCategoryByUserId", _nExpertId);
        return list;
	}

    @Override
    @SuppressWarnings("unchecked")
    public List<IrpCategory> selectChildCategoryList(List<Long> conditionIdList) throws SQLException {
        return getSqlMapClientTemplate().queryForList("irp_category.selectChildCategoryList", conditionIdList);
    }

	@Override
	public List<IrpCategory> findAllCategoryByExpertId(String _sql) {
		 List<IrpCategory> list = null;
		if(_sql!=""&&_sql!=null){
		Map map=new HashMap();
		map.put("sql", _sql);
		list = getSqlMapClientTemplate().queryForList("irp_category.selectCategoryByExpertid", map);
		}
		return list;
	}
}