package com.tfs.irp.questionbank.dao.impl;

import com.tfs.irp.questionbank.dao.IrpQuestionBankDAO;
import com.tfs.irp.questionbank.entity.IrpQuestionBank;
import com.tfs.irp.questionbank.entity.IrpQuestionBankExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpQuestionBankDAOImpl extends SqlMapClientDaoSupport  implements IrpQuestionBankDAO {
  
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_question_bank
     *
     * @ibatorgenerated Fri Sep 05 10:59:05 CST 2014
     */
    public int countByExample(IrpQuestionBankExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("irp_question_bank.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_question_bank
     *
     * @ibatorgenerated Fri Sep 05 10:59:05 CST 2014
     */
    public int deleteByExample(IrpQuestionBankExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("irp_question_bank.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_question_bank
     *
     * @ibatorgenerated Fri Sep 05 10:59:05 CST 2014
     */
    public int deleteByPrimaryKey(Long qbankid) throws SQLException {
        IrpQuestionBank key = new IrpQuestionBank();
        key.setQbankid(qbankid);
        int rows = getSqlMapClientTemplate().delete("irp_question_bank.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_question_bank
     *
     * @ibatorgenerated Fri Sep 05 10:59:05 CST 2014
     */
    public void insert(IrpQuestionBank record) throws SQLException {
        getSqlMapClientTemplate().insert("irp_question_bank.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_question_bank
     *
     * @ibatorgenerated Fri Sep 05 10:59:05 CST 2014
     */
    public void insertSelective(IrpQuestionBank record) throws SQLException {
        getSqlMapClientTemplate().insert("irp_question_bank.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_question_bank
     *
     * @ibatorgenerated Fri Sep 05 10:59:05 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<IrpQuestionBank> selectByExample(IrpQuestionBankExample example) throws SQLException {
        List<IrpQuestionBank> list = getSqlMapClientTemplate().queryForList("irp_question_bank.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_question_bank
     *
     * @ibatorgenerated Fri Sep 05 10:59:05 CST 2014
     */
    public IrpQuestionBank selectByPrimaryKey(Long qbankid) throws SQLException {
        IrpQuestionBank key = new IrpQuestionBank();
        key.setQbankid(qbankid);
        IrpQuestionBank record = (IrpQuestionBank) getSqlMapClientTemplate().queryForObject("irp_question_bank.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_question_bank
     *
     * @ibatorgenerated Fri Sep 05 10:59:05 CST 2014
     */
    public int updateByExampleSelective(IrpQuestionBank record, IrpQuestionBankExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_question_bank.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_question_bank
     *
     * @ibatorgenerated Fri Sep 05 10:59:05 CST 2014
     */
    public int updateByExample(IrpQuestionBank record, IrpQuestionBankExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_question_bank.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_question_bank
     *
     * @ibatorgenerated Fri Sep 05 10:59:05 CST 2014
     */
    public int updateByPrimaryKeySelective(IrpQuestionBank record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("irp_question_bank.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_question_bank
     *
     * @ibatorgenerated Fri Sep 05 10:59:05 CST 2014
     */
    public int updateByPrimaryKey(IrpQuestionBank record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("irp_question_bank.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table irp_question_bank
     *
     * @ibatorgenerated Fri Sep 05 10:59:05 CST 2014
     */
    private static class UpdateByExampleParms extends IrpQuestionBankExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpQuestionBankExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<IrpQuestionBank> selectByExample(
			IrpQuestionBankExample example, PageUtil pageUtil)
			throws SQLException {
		// TODO Auto-generated method stub
		List<IrpQuestionBank> list = null;
		
		list = getSqlMapClientTemplate().queryForList("irp_question_bank.ibatorgenerated_selectByExample", example,pageUtil.getPageIndex(),pageUtil.getPageSize());
		
		return list;
	}

	@Override
	public List<IrpQuestionBank> randomtestpaper(Integer qtype, int num)
			throws SQLException {
		// TODO Auto-generated method stub
		List<IrpQuestionBank> list = null;
		Map map = new HashMap();
		map.put("num", num);
		IrpQuestionBank key = new IrpQuestionBank();
		key.setQbtype(qtype);
		map.put("key", key);
		list = getSqlMapClientTemplate().queryForList("irp_question_bank.ibatorgenerated_selectrandom", map);
		return list;
	}
}