package com.tfs.irp.subscribe.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class IrpSubscribeExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table irp_subscribe
     *
     * @ibatorgenerated Thu Jul 24 15:20:08 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table irp_subscribe
     *
     * @ibatorgenerated Thu Jul 24 15:20:08 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_subscribe
     *
     * @ibatorgenerated Thu Jul 24 15:20:08 CST 2014
     */
    public IrpSubscribeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_subscribe
     *
     * @ibatorgenerated Thu Jul 24 15:20:08 CST 2014
     */
    protected IrpSubscribeExample(IrpSubscribeExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_subscribe
     *
     * @ibatorgenerated Thu Jul 24 15:20:08 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_subscribe
     *
     * @ibatorgenerated Thu Jul 24 15:20:08 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_subscribe
     *
     * @ibatorgenerated Thu Jul 24 15:20:08 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_subscribe
     *
     * @ibatorgenerated Thu Jul 24 15:20:08 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_subscribe
     *
     * @ibatorgenerated Thu Jul 24 15:20:08 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_subscribe
     *
     * @ibatorgenerated Thu Jul 24 15:20:08 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_subscribe
     *
     * @ibatorgenerated Thu Jul 24 15:20:08 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table irp_subscribe
     *
     * @ibatorgenerated Thu Jul 24 15:20:08 CST 2014
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSubscribeidIsNull() {
            addCriterion("SUBSCRIBEID is null");
            return this;
        }

        public Criteria andSubscribeidIsNotNull() {
            addCriterion("SUBSCRIBEID is not null");
            return this;
        }

        public Criteria andSubscribeidEqualTo(Long value) {
            addCriterion("SUBSCRIBEID =", value, "subscribeid");
            return this;
        }

        public Criteria andSubscribeidNotEqualTo(Long value) {
            addCriterion("SUBSCRIBEID <>", value, "subscribeid");
            return this;
        }

        public Criteria andSubscribeidGreaterThan(Long value) {
            addCriterion("SUBSCRIBEID >", value, "subscribeid");
            return this;
        }

        public Criteria andSubscribeidGreaterThanOrEqualTo(Long value) {
            addCriterion("SUBSCRIBEID >=", value, "subscribeid");
            return this;
        }

        public Criteria andSubscribeidLessThan(Long value) {
            addCriterion("SUBSCRIBEID <", value, "subscribeid");
            return this;
        }

        public Criteria andSubscribeidLessThanOrEqualTo(Long value) {
            addCriterion("SUBSCRIBEID <=", value, "subscribeid");
            return this;
        }

        public Criteria andSubscribeidIn(List<Long> values) {
            addCriterion("SUBSCRIBEID in", values, "subscribeid");
            return this;
        }

        public Criteria andSubscribeidNotIn(List<Long> values) {
            addCriterion("SUBSCRIBEID not in", values, "subscribeid");
            return this;
        }

        public Criteria andSubscribeidBetween(Long value1, Long value2) {
            addCriterion("SUBSCRIBEID between", value1, value2, "subscribeid");
            return this;
        }

        public Criteria andSubscribeidNotBetween(Long value1, Long value2) {
            addCriterion("SUBSCRIBEID not between", value1, value2, "subscribeid");
            return this;
        }

        public Criteria andSubscribeuseridIsNull() {
            addCriterion("SUBSCRIBEUSERID is null");
            return this;
        }

        public Criteria andSubscribeuseridIsNotNull() {
            addCriterion("SUBSCRIBEUSERID is not null");
            return this;
        }

        public Criteria andSubscribeuseridEqualTo(Long value) {
            addCriterion("SUBSCRIBEUSERID =", value, "subscribeuserid");
            return this;
        }

        public Criteria andSubscribeuseridNotEqualTo(Long value) {
            addCriterion("SUBSCRIBEUSERID <>", value, "subscribeuserid");
            return this;
        }

        public Criteria andSubscribeuseridGreaterThan(Long value) {
            addCriterion("SUBSCRIBEUSERID >", value, "subscribeuserid");
            return this;
        }

        public Criteria andSubscribeuseridGreaterThanOrEqualTo(Long value) {
            addCriterion("SUBSCRIBEUSERID >=", value, "subscribeuserid");
            return this;
        }

        public Criteria andSubscribeuseridLessThan(Long value) {
            addCriterion("SUBSCRIBEUSERID <", value, "subscribeuserid");
            return this;
        }

        public Criteria andSubscribeuseridLessThanOrEqualTo(Long value) {
            addCriterion("SUBSCRIBEUSERID <=", value, "subscribeuserid");
            return this;
        }

        public Criteria andSubscribeuseridIn(List<Long> values) {
            addCriterion("SUBSCRIBEUSERID in", values, "subscribeuserid");
            return this;
        }

        public Criteria andSubscribeuseridNotIn(List<Long> values) {
            addCriterion("SUBSCRIBEUSERID not in", values, "subscribeuserid");
            return this;
        }

        public Criteria andSubscribeuseridBetween(Long value1, Long value2) {
            addCriterion("SUBSCRIBEUSERID between", value1, value2, "subscribeuserid");
            return this;
        }

        public Criteria andSubscribeuseridNotBetween(Long value1, Long value2) {
            addCriterion("SUBSCRIBEUSERID not between", value1, value2, "subscribeuserid");
            return this;
        }

        public Criteria andSubscribeobjidIsNull() {
            addCriterion("SUBSCRIBEOBJID is null");
            return this;
        }

        public Criteria andSubscribeobjidIsNotNull() {
            addCriterion("SUBSCRIBEOBJID is not null");
            return this;
        }

        public Criteria andSubscribeobjidEqualTo(Long value) {
            addCriterion("SUBSCRIBEOBJID =", value, "subscribeobjid");
            return this;
        }

        public Criteria andSubscribeobjidNotEqualTo(Long value) {
            addCriterion("SUBSCRIBEOBJID <>", value, "subscribeobjid");
            return this;
        }

        public Criteria andSubscribeobjidGreaterThan(Long value) {
            addCriterion("SUBSCRIBEOBJID >", value, "subscribeobjid");
            return this;
        }

        public Criteria andSubscribeobjidGreaterThanOrEqualTo(Long value) {
            addCriterion("SUBSCRIBEOBJID >=", value, "subscribeobjid");
            return this;
        }

        public Criteria andSubscribeobjidLessThan(Long value) {
            addCriterion("SUBSCRIBEOBJID <", value, "subscribeobjid");
            return this;
        }

        public Criteria andSubscribeobjidLessThanOrEqualTo(Long value) {
            addCriterion("SUBSCRIBEOBJID <=", value, "subscribeobjid");
            return this;
        }

        public Criteria andSubscribeobjidIn(List<Long> values) {
            addCriterion("SUBSCRIBEOBJID in", values, "subscribeobjid");
            return this;
        }

        public Criteria andSubscribeobjidNotIn(List<Long> values) {
            addCriterion("SUBSCRIBEOBJID not in", values, "subscribeobjid");
            return this;
        }

        public Criteria andSubscribeobjidBetween(Long value1, Long value2) {
            addCriterion("SUBSCRIBEOBJID between", value1, value2, "subscribeobjid");
            return this;
        }

        public Criteria andSubscribeobjidNotBetween(Long value1, Long value2) {
            addCriterion("SUBSCRIBEOBJID not between", value1, value2, "subscribeobjid");
            return this;
        }

        public Criteria andSubscribeobjtypeIsNull() {
            addCriterion("SUBSCRIBEOBJTYPE is null");
            return this;
        }

        public Criteria andSubscribeobjtypeIsNotNull() {
            addCriterion("SUBSCRIBEOBJTYPE is not null");
            return this;
        }

        public Criteria andSubscribeobjtypeEqualTo(String value) {
            addCriterion("SUBSCRIBEOBJTYPE =", value, "subscribeobjtype");
            return this;
        }

        public Criteria andSubscribeobjtypeNotEqualTo(String value) {
            addCriterion("SUBSCRIBEOBJTYPE <>", value, "subscribeobjtype");
            return this;
        }

        public Criteria andSubscribeobjtypeGreaterThan(String value) {
            addCriterion("SUBSCRIBEOBJTYPE >", value, "subscribeobjtype");
            return this;
        }

        public Criteria andSubscribeobjtypeGreaterThanOrEqualTo(String value) {
            addCriterion("SUBSCRIBEOBJTYPE >=", value, "subscribeobjtype");
            return this;
        }

        public Criteria andSubscribeobjtypeLessThan(String value) {
            addCriterion("SUBSCRIBEOBJTYPE <", value, "subscribeobjtype");
            return this;
        }

        public Criteria andSubscribeobjtypeLessThanOrEqualTo(String value) {
            addCriterion("SUBSCRIBEOBJTYPE <=", value, "subscribeobjtype");
            return this;
        }

        public Criteria andSubscribeobjtypeLike(String value) {
            addCriterion("SUBSCRIBEOBJTYPE like", value, "subscribeobjtype");
            return this;
        }

        public Criteria andSubscribeobjtypeNotLike(String value) {
            addCriterion("SUBSCRIBEOBJTYPE not like", value, "subscribeobjtype");
            return this;
        }

        public Criteria andSubscribeobjtypeIn(List<String> values) {
            addCriterion("SUBSCRIBEOBJTYPE in", values, "subscribeobjtype");
            return this;
        }

        public Criteria andSubscribeobjtypeNotIn(List<String> values) {
            addCriterion("SUBSCRIBEOBJTYPE not in", values, "subscribeobjtype");
            return this;
        }

        public Criteria andSubscribeobjtypeBetween(String value1, String value2) {
            addCriterion("SUBSCRIBEOBJTYPE between", value1, value2, "subscribeobjtype");
            return this;
        }

        public Criteria andSubscribeobjtypeNotBetween(String value1, String value2) {
            addCriterion("SUBSCRIBEOBJTYPE not between", value1, value2, "subscribeobjtype");
            return this;
        }

        public Criteria andCrtimeIsNull() {
            addCriterion("CRTIME is null");
            return this;
        }

        public Criteria andCrtimeIsNotNull() {
            addCriterion("CRTIME is not null");
            return this;
        }

        public Criteria andCrtimeEqualTo(Date value) {
            addCriterion("CRTIME =", value, "crtime");
            return this;
        }

        public Criteria andCrtimeNotEqualTo(Date value) {
            addCriterion("CRTIME <>", value, "crtime");
            return this;
        }

        public Criteria andCrtimeGreaterThan(Date value) {
            addCriterion("CRTIME >", value, "crtime");
            return this;
        }

        public Criteria andCrtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CRTIME >=", value, "crtime");
            return this;
        }

        public Criteria andCrtimeLessThan(Date value) {
            addCriterion("CRTIME <", value, "crtime");
            return this;
        }

        public Criteria andCrtimeLessThanOrEqualTo(Date value) {
            addCriterion("CRTIME <=", value, "crtime");
            return this;
        }

        public Criteria andCrtimeIn(List<Date> values) {
            addCriterion("CRTIME in", values, "crtime");
            return this;
        }

        public Criteria andCrtimeNotIn(List<Date> values) {
            addCriterion("CRTIME not in", values, "crtime");
            return this;
        }

        public Criteria andCrtimeBetween(Date value1, Date value2) {
            addCriterion("CRTIME between", value1, value2, "crtime");
            return this;
        }

        public Criteria andCrtimeNotBetween(Date value1, Date value2) {
            addCriterion("CRTIME not between", value1, value2, "crtime");
            return this;
        }

        public Criteria andCruseridIsNull() {
            addCriterion("CRUSERID is null");
            return this;
        }

        public Criteria andCruseridIsNotNull() {
            addCriterion("CRUSERID is not null");
            return this;
        }

        public Criteria andCruseridEqualTo(Long value) {
            addCriterion("CRUSERID =", value, "cruserid");
            return this;
        }

        public Criteria andCruseridNotEqualTo(Long value) {
            addCriterion("CRUSERID <>", value, "cruserid");
            return this;
        }

        public Criteria andCruseridGreaterThan(Long value) {
            addCriterion("CRUSERID >", value, "cruserid");
            return this;
        }

        public Criteria andCruseridGreaterThanOrEqualTo(Long value) {
            addCriterion("CRUSERID >=", value, "cruserid");
            return this;
        }

        public Criteria andCruseridLessThan(Long value) {
            addCriterion("CRUSERID <", value, "cruserid");
            return this;
        }

        public Criteria andCruseridLessThanOrEqualTo(Long value) {
            addCriterion("CRUSERID <=", value, "cruserid");
            return this;
        }

        public Criteria andCruseridIn(List<Long> values) {
            addCriterion("CRUSERID in", values, "cruserid");
            return this;
        }

        public Criteria andCruseridNotIn(List<Long> values) {
            addCriterion("CRUSERID not in", values, "cruserid");
            return this;
        }

        public Criteria andCruseridBetween(Long value1, Long value2) {
            addCriterion("CRUSERID between", value1, value2, "cruserid");
            return this;
        }

        public Criteria andCruseridNotBetween(Long value1, Long value2) {
            addCriterion("CRUSERID not between", value1, value2, "cruserid");
            return this;
        }
        public Criteria andSubReadStatusIsNull() {
            addCriterion("SUBREADSTATUS is null");
            return this;
        }

        public Criteria andSubReadStatusIsNotNull() {
            addCriterion("SUBREADSTATUS is not null");
            return this;
        }

        public Criteria andSubReadStatusEqualTo(Long value) {
            addCriterion("SUBREADSTATUS =", value, "subReadStatus");
            return this;
        }

        public Criteria andSubReadStatusNotEqualTo(Long value) {
            addCriterion("SUBREADSTATUS <>", value, "subReadStatus");
            return this;
        }

        public Criteria andSubReadStatusGreaterThan(Long value) {
            addCriterion("SUBREADSTATUS >", value, "subReadStatus");
            return this;
        }

        public Criteria andSubReadStatusGreaterThanOrEqualTo(Long value) {
            addCriterion("SUBREADSTATUS >=", value, "subReadStatus");
            return this;
        }

        public Criteria andSubReadStatusLessThan(Long value) {
            addCriterion("SUBREADSTATUS <", value, "subReadStatus");
            return this;
        }

        public Criteria andSubReadStatusLessThanOrEqualTo(Long value) {
            addCriterion("SUBREADSTATUS <=", value, "subReadStatus");
            return this;
        }

        public Criteria andSubReadStatusIn(List<Long> values) {
            addCriterion("SUBREADSTATUS in", values, "subReadStatus");
            return this;
        }

        public Criteria andSubReadStatusNotIn(List<Long> values) {
            addCriterion("SUBREADSTATUS not in", values, "subReadStatus");
            return this;
        }

        public Criteria andSubReadStatusBetween(Long value1, Long value2) {
            addCriterion("SUBREADSTATUS between", value1, value2, "subReadStatus");
            return this;
        }

        public Criteria andSubReadStatusNotBetween(Long value1, Long value2) {
            addCriterion("SUBREADSTATUS not between", value1, value2, "subReadStatus");
            return this;
        }
        
    }
}