package com.tfs.irp.termeditlog.entity;

import java.util.Date;

public class IrpTermeditLog {

    /**
     *  对象表名
     */
    public final static String TABLE_NAME = "IRP_TERMEDIT_LOG";

    /**
     * 主键字段名称
     */
    public final static String ID_FIELD_NAME = "TERMEDITLOGID";

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IRP_TERMEDIT_LOG.TERMEDITLOGID
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    private Long termeditlogid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IRP_TERMEDIT_LOG.TERMEDITUSERID
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    private Long termedituserid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IRP_TERMEDIT_LOG.TERMID
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    private Long termid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IRP_TERMEDIT_LOG.TERMEDITDATE
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    private Date termeditdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IRP_TERMEDIT_LOG.TERMEDITLOGONE
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    private String termeditlogone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IRP_TERMEDIT_LOG.TERMEDITLOGTWO
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    private String termeditlogtwo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IRP_TERMEDIT_LOG.TERMEDITLOGTHREE
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    private String termeditlogthree;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IRP_TERMEDIT_LOG.TERMEDITLOGID
     *
     * @return the value of IRP_TERMEDIT_LOG.TERMEDITLOGID
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public Long getTermeditlogid() {
        return termeditlogid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IRP_TERMEDIT_LOG.TERMEDITLOGID
     *
     * @param termeditlogid the value for IRP_TERMEDIT_LOG.TERMEDITLOGID
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public void setTermeditlogid(Long termeditlogid) {
        this.termeditlogid = termeditlogid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IRP_TERMEDIT_LOG.TERMEDITUSERID
     *
     * @return the value of IRP_TERMEDIT_LOG.TERMEDITUSERID
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public Long getTermedituserid() {
        return termedituserid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IRP_TERMEDIT_LOG.TERMEDITUSERID
     *
     * @param termedituserid the value for IRP_TERMEDIT_LOG.TERMEDITUSERID
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public void setTermedituserid(Long termedituserid) {
        this.termedituserid = termedituserid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IRP_TERMEDIT_LOG.TERMID
     *
     * @return the value of IRP_TERMEDIT_LOG.TERMID
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public Long getTermid() {
        return termid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IRP_TERMEDIT_LOG.TERMID
     *
     * @param termid the value for IRP_TERMEDIT_LOG.TERMID
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public void setTermid(Long termid) {
        this.termid = termid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IRP_TERMEDIT_LOG.TERMEDITDATE
     *
     * @return the value of IRP_TERMEDIT_LOG.TERMEDITDATE
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public Date getTermeditdate() {
        return termeditdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IRP_TERMEDIT_LOG.TERMEDITDATE
     *
     * @param termeditdate the value for IRP_TERMEDIT_LOG.TERMEDITDATE
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public void setTermeditdate(Date termeditdate) {
        this.termeditdate = termeditdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IRP_TERMEDIT_LOG.TERMEDITLOGONE
     *
     * @return the value of IRP_TERMEDIT_LOG.TERMEDITLOGONE
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public String getTermeditlogone() {
        return termeditlogone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IRP_TERMEDIT_LOG.TERMEDITLOGONE
     *
     * @param termeditlogone the value for IRP_TERMEDIT_LOG.TERMEDITLOGONE
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public void setTermeditlogone(String termeditlogone) {
        this.termeditlogone = termeditlogone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IRP_TERMEDIT_LOG.TERMEDITLOGTWO
     *
     * @return the value of IRP_TERMEDIT_LOG.TERMEDITLOGTWO
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public String getTermeditlogtwo() {
        return termeditlogtwo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IRP_TERMEDIT_LOG.TERMEDITLOGTWO
     *
     * @param termeditlogtwo the value for IRP_TERMEDIT_LOG.TERMEDITLOGTWO
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public void setTermeditlogtwo(String termeditlogtwo) {
        this.termeditlogtwo = termeditlogtwo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IRP_TERMEDIT_LOG.TERMEDITLOGTHREE
     *
     * @return the value of IRP_TERMEDIT_LOG.TERMEDITLOGTHREE
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public String getTermeditlogthree() {
        return termeditlogthree;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IRP_TERMEDIT_LOG.TERMEDITLOGTHREE
     *
     * @param termeditlogthree the value for IRP_TERMEDIT_LOG.TERMEDITLOGTHREE
     *
     * @ibatorgenerated Tue Oct 10 17:36:42 CST 2017
     */
    public void setTermeditlogthree(String termeditlogthree) {
        this.termeditlogthree = termeditlogthree;
    }
}