package com.tfs.irp.doc_tag.dao.impl;

import com.tfs.irp.doc_tag.dao.IrpDocTagDAO;
import com.tfs.irp.doc_tag.entity.IrpDocTag;
import com.tfs.irp.doc_tag.entity.IrpDocTagExample;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpDocTagDAOImpl extends SqlMapClientDaoSupport implements IrpDocTagDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_DOC_TAG
     *
     * @ibatorgenerated Mon Apr 22 09:11:56 CST 2013
     */
    public int countByExample(IrpDocTagExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_DOC_TAG.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_DOC_TAG
     *
     * @ibatorgenerated Mon Apr 22 09:11:56 CST 2013
     */
    public int deleteByExample(IrpDocTagExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_DOC_TAG.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_DOC_TAG
     *
     * @ibatorgenerated Mon Apr 22 09:11:56 CST 2013
     */
    public int deleteByPrimaryKey(Long doctagid) throws SQLException {
        IrpDocTag key = new IrpDocTag();
        key.setDoctagid(doctagid);
        int rows = getSqlMapClientTemplate().delete("IRP_DOC_TAG.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_DOC_TAG
     *
     * @ibatorgenerated Mon Apr 22 09:11:56 CST 2013
     */
    public void insert(IrpDocTag record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_DOC_TAG.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_DOC_TAG
     *
     * @ibatorgenerated Mon Apr 22 09:11:56 CST 2013
     */
    public void insertSelective(IrpDocTag record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_DOC_TAG.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_DOC_TAG
     *
     * @ibatorgenerated Mon Apr 22 09:11:56 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<IrpDocTag> selectByExample(IrpDocTagExample example) throws SQLException {
        List<IrpDocTag> list = getSqlMapClientTemplate().queryForList("IRP_DOC_TAG.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_DOC_TAG
     *
     * @ibatorgenerated Mon Apr 22 09:11:56 CST 2013
     */
    public IrpDocTag selectByPrimaryKey(Long doctagid) throws SQLException {
        IrpDocTag key = new IrpDocTag();
        key.setDoctagid(doctagid);
        IrpDocTag record = (IrpDocTag) getSqlMapClientTemplate().queryForObject("IRP_DOC_TAG.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_DOC_TAG
     *
     * @ibatorgenerated Mon Apr 22 09:11:56 CST 2013
     */
    public int updateByExampleSelective(IrpDocTag record, IrpDocTagExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_DOC_TAG.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_DOC_TAG
     *
     * @ibatorgenerated Mon Apr 22 09:11:56 CST 2013
     */
    public int updateByExample(IrpDocTag record, IrpDocTagExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_DOC_TAG.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_DOC_TAG
     *
     * @ibatorgenerated Mon Apr 22 09:11:56 CST 2013
     */
    public int updateByPrimaryKeySelective(IrpDocTag record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_DOC_TAG.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_DOC_TAG
     *
     * @ibatorgenerated Mon Apr 22 09:11:56 CST 2013
     */
    public int updateByPrimaryKey(IrpDocTag record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_DOC_TAG.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table IRP_DOC_TAG
     *
     * @ibatorgenerated Mon Apr 22 09:11:56 CST 2013
     */
    private static class UpdateByExampleParms extends IrpDocTagExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpDocTagExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}