package com.tfs.irp.workflow.dao;

import com.tfs.irp.util.PageUtil;
import com.tfs.irp.workflow.entity.IrpWorkflowObj;
import com.tfs.irp.workflow.entity.IrpWorkflowObjExample;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;

public interface IrpWorkflowObjDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_WORKFLOW_OBJ
	 * @ibatorgenerated  Wed Oct 16 20:08:32 CST 2013
	 */
	int countByExample(IrpWorkflowObjExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_WORKFLOW_OBJ
	 * @ibatorgenerated  Wed Oct 16 20:08:32 CST 2013
	 */
	int deleteByExample(IrpWorkflowObjExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_WORKFLOW_OBJ
	 * @ibatorgenerated  Wed Oct 16 20:08:32 CST 2013
	 */
	int deleteByPrimaryKey(Long flowobjid) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_WORKFLOW_OBJ
	 * @ibatorgenerated  Wed Oct 16 20:08:32 CST 2013
	 */
	void insert(IrpWorkflowObj record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_WORKFLOW_OBJ
	 * @ibatorgenerated  Wed Oct 16 20:08:32 CST 2013
	 */
	void insertSelective(IrpWorkflowObj record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_WORKFLOW_OBJ
	 * @ibatorgenerated  Wed Oct 16 20:08:32 CST 2013
	 */
	List<IrpWorkflowObj> selectByExample(IrpWorkflowObjExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_WORKFLOW_OBJ
	 * @ibatorgenerated  Wed Oct 16 20:08:32 CST 2013
	 */
	IrpWorkflowObj selectByPrimaryKey(Long flowobjid) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_WORKFLOW_OBJ
	 * @ibatorgenerated  Wed Oct 16 20:08:32 CST 2013
	 */
	int updateByExampleSelective(IrpWorkflowObj record,
			IrpWorkflowObjExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_WORKFLOW_OBJ
	 * @ibatorgenerated  Wed Oct 16 20:08:32 CST 2013
	 */
	int updateByExample(IrpWorkflowObj record, IrpWorkflowObjExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_WORKFLOW_OBJ
	 * @ibatorgenerated  Wed Oct 16 20:08:32 CST 2013
	 */
	int updateByPrimaryKeySelective(IrpWorkflowObj record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_WORKFLOW_OBJ
	 * @ibatorgenerated  Wed Oct 16 20:08:32 CST 2013
	 */
	int updateByPrimaryKey(IrpWorkflowObj record) throws SQLException;

	/**
	 * 根据用户ID获得用户的代办信�?
	 * @param _nUserId
	 * @return
	 * @throws SQLException
	 */
	List<Map<String, Object>> selectWorkFlowObjByUserId(Long _nUserId) throws SQLException;
	
	/**
	 * 根据用户ID分页获得用户的代办信�?
	 * @param _nUserId
	 * @param pageUtil
	 * @return
	 * @throws SQLException
	 */
	List<Map<String, Object>> selectWorkFlowObjByUserId(Long _nUserId, PageUtil pageUtil) throws SQLException;
	
	/**
	 * 根据用户ID获得用户的代办信息数�?
	 * @param _nUserId
	 * @return
	 * @throws SQLException
	 */
	int selectWorkFlowObjCountByUserId(Long _nUserId) throws SQLException;

	/**
	 * 根据用户ID获得未签收的用户审核数量
	 * @param _nUserId
	 * @return
	 * @throws SQLException
	 */
	int selectNotSignFlowCountByUserId(Long _nUserId) throws SQLException;
}