package com.tfs.irp.workflow.dao;

import com.tfs.irp.util.PageUtil;
import com.tfs.irp.workflow.entity.IrpWorkflow;
import com.tfs.irp.workflow.entity.IrpWorkflowExample;
import java.sql.SQLException;
import java.util.List;

public interface IrpWorkflowDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_WORKFLOW
     *
     * @ibatorgenerated Sun Apr 28 15:25:36 CST 2013
     */
    int countByExample(IrpWorkflowExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_WORKFLOW
     *
     * @ibatorgenerated Sun Apr 28 15:25:36 CST 2013
     */
    int deleteByExample(IrpWorkflowExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_WORKFLOW
     *
     * @ibatorgenerated Sun Apr 28 15:25:36 CST 2013
     */
    int deleteByPrimaryKey(Long flowid) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_WORKFLOW
     *
     * @ibatorgenerated Sun Apr 28 15:25:36 CST 2013
     */
    void insert(IrpWorkflow record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_WORKFLOW
     *
     * @ibatorgenerated Sun Apr 28 15:25:36 CST 2013
     */
    void insertSelective(IrpWorkflow record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_WORKFLOW
     *
     * @ibatorgenerated Sun Apr 28 15:25:36 CST 2013
     */
    List<IrpWorkflow> selectByExample(IrpWorkflowExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_WORKFLOW
     *
     * @ibatorgenerated Sun Apr 28 15:25:36 CST 2013
     */
    IrpWorkflow selectByPrimaryKey(Long flowid) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_WORKFLOW
     *
     * @ibatorgenerated Sun Apr 28 15:25:36 CST 2013
     */
    int updateByExampleSelective(IrpWorkflow record, IrpWorkflowExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_WORKFLOW
     *
     * @ibatorgenerated Sun Apr 28 15:25:36 CST 2013
     */
    int updateByExample(IrpWorkflow record, IrpWorkflowExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_WORKFLOW
     *
     * @ibatorgenerated Sun Apr 28 15:25:36 CST 2013
     */
    int updateByPrimaryKeySelective(IrpWorkflow record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_WORKFLOW
     *
     * @ibatorgenerated Sun Apr 28 15:25:36 CST 2013
     */
    int updateByPrimaryKey(IrpWorkflow record) throws SQLException;

	List<IrpWorkflow> selectByExample(IrpWorkflowExample example, PageUtil pageUtil) throws SQLException;
}