package com.tfs.irp.usergoodslink.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.tfs.irp.usergoodslink.dao.IrpUserCovertGoodsDAO;
import com.tfs.irp.usergoodslink.entity.IrpUserCovertGoods;
import com.tfs.irp.usergoodslink.entity.IrpUserCovertGoodsExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpUserCovertGoodsDAOImpl extends SqlMapClientDaoSupport implements IrpUserCovertGoodsDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_USER_COVERT_GOODS
     *
     * @abatorgenerated Wed Apr 12 17:15:45 CST 2017
     */
    public void insert(IrpUserCovertGoods record) throws SQLException {
    	getSqlMapClientTemplate().insert("IRP_USER_COVERT_GOODS.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_USER_COVERT_GOODS
     *
     * @abatorgenerated Wed Apr 12 17:15:45 CST 2017
     */
    public int updateByPrimaryKey(IrpUserCovertGoods record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_USER_COVERT_GOODS.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_USER_COVERT_GOODS
     *
     * @abatorgenerated Wed Apr 12 17:15:45 CST 2017
     */
    public int updateByPrimaryKeySelective(IrpUserCovertGoods record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_USER_COVERT_GOODS.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_USER_COVERT_GOODS
     *
     * @abatorgenerated Wed Apr 12 17:15:45 CST 2017
     */
    public List selectByExample(IrpUserCovertGoodsExample example) throws SQLException {
        List list = getSqlMapClientTemplate().queryForList("IRP_USER_COVERT_GOODS.abatorgenerated_selectByExample", example);
        return list;
    }
    public List selectallByExample(PageUtil pageUtil,IrpUserCovertGoodsExample example) throws SQLException {
    	List list = getSqlMapClientTemplate().queryForList("IRP_USER_COVERT_GOODS.abatorgenerated_selectByExample", example,pageUtil.getPageIndex(),pageUtil.getPageSize());
    	return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_USER_COVERT_GOODS
     *
     * @abatorgenerated Wed Apr 12 17:15:45 CST 2017
     */
    public IrpUserCovertGoods selectByPrimaryKey(Long usergoodsid) throws SQLException {
        IrpUserCovertGoods key = new IrpUserCovertGoods();
        key.setUsergoodsid(usergoodsid);
        IrpUserCovertGoods record = (IrpUserCovertGoods) getSqlMapClientTemplate().queryForObject("IRP_USER_COVERT_GOODS.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_USER_COVERT_GOODS
     *
     * @abatorgenerated Wed Apr 12 17:15:45 CST 2017
     */
    public int deleteByExample(IrpUserCovertGoodsExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_USER_COVERT_GOODS.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_USER_COVERT_GOODS
     *
     * @abatorgenerated Wed Apr 12 17:15:45 CST 2017
     */
    public int deleteByPrimaryKey(Long usergoodsid) throws SQLException {
        IrpUserCovertGoods key = new IrpUserCovertGoods();
        key.setUsergoodsid(usergoodsid);
        int rows = getSqlMapClientTemplate().delete("IRP_USER_COVERT_GOODS.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_USER_COVERT_GOODS
     *
     * @abatorgenerated Wed Apr 12 17:15:45 CST 2017
     */
    public int countByExample(IrpUserCovertGoodsExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_USER_COVERT_GOODS.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_USER_COVERT_GOODS
     *
     * @abatorgenerated Wed Apr 12 17:15:45 CST 2017
     */
    public int updateByExampleSelective(IrpUserCovertGoods record, IrpUserCovertGoodsExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_USER_COVERT_GOODS.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_USER_COVERT_GOODS
     *
     * @abatorgenerated Wed Apr 12 17:15:45 CST 2017
     */
    public int updateByExample(IrpUserCovertGoods record, IrpUserCovertGoodsExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_USER_COVERT_GOODS.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table IRP_USER_COVERT_GOODS
     *
     * @abatorgenerated Wed Apr 12 17:15:45 CST 2017
     */
    private static class UpdateByExampleParms extends IrpUserCovertGoodsExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpUserCovertGoodsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}