package com.tfs.irp.microblogatme.dao.impl;

import com.tfs.irp.microblogatme.dao.IrpMicroblogAtmeDAO;
import com.tfs.irp.microblogatme.entity.IrpMicroblogAtmeExample;
import com.tfs.irp.microblogatme.entity.IrpMicroblogAtmeKey;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpMicroblogAtmeDAOImpl extends SqlMapClientDaoSupport implements IrpMicroblogAtmeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MICROBLOG_ATME
	 * @ibatorgenerated  Wed May 15 15:53:49 CST 2013
	 */
	public int countByExample(IrpMicroblogAtmeExample example)
			throws SQLException {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"IRP_MICROBLOG_ATME.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MICROBLOG_ATME
	 * @ibatorgenerated  Wed May 15 15:53:49 CST 2013
	 */
	public int deleteByExample(IrpMicroblogAtmeExample example)
			throws SQLException {
		int rows = getSqlMapClientTemplate().delete(
				"IRP_MICROBLOG_ATME.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MICROBLOG_ATME
	 * @ibatorgenerated  Wed May 15 15:53:49 CST 2013
	 */
	public int deleteByPrimaryKey(IrpMicroblogAtmeKey key) throws SQLException {
		int rows = getSqlMapClientTemplate().delete(
				"IRP_MICROBLOG_ATME.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MICROBLOG_ATME
	 * @ibatorgenerated  Wed May 15 15:53:49 CST 2013
	 */
	public void insert(IrpMicroblogAtmeKey record) throws SQLException {
		getSqlMapClientTemplate()
				.insert("IRP_MICROBLOG_ATME.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MICROBLOG_ATME
	 * @ibatorgenerated  Wed May 15 15:53:49 CST 2013
	 */
	public void insertSelective(IrpMicroblogAtmeKey record) throws SQLException {
		getSqlMapClientTemplate().insert(
				"IRP_MICROBLOG_ATME.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MICROBLOG_ATME
	 * @ibatorgenerated  Wed May 15 15:53:49 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<IrpMicroblogAtmeKey> selectByExample(
			IrpMicroblogAtmeExample example) throws SQLException {
		List<IrpMicroblogAtmeKey> list = getSqlMapClientTemplate().queryForList(
				"IRP_MICROBLOG_ATME.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MICROBLOG_ATME
	 * @ibatorgenerated  Wed May 15 15:53:49 CST 2013
	 */
	public IrpMicroblogAtmeKey selectByPrimaryKey(IrpMicroblogAtmeKey key)
			throws SQLException {
		IrpMicroblogAtmeKey record = (IrpMicroblogAtmeKey) getSqlMapClientTemplate()
				.queryForObject(
						"IRP_MICROBLOG_ATME.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}
	public IrpMicroblogAtmeKey selectAtmeByPrimaryKey(IrpMicroblogAtmeKey key)
			throws SQLException {
		IrpMicroblogAtmeKey record = (IrpMicroblogAtmeKey) getSqlMapClientTemplate()
				.queryForObject(
						"IRP_MICROBLOG_ATME.ibatorgenerated_selectAtmeByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MICROBLOG_ATME
	 * @ibatorgenerated  Wed May 15 15:53:49 CST 2013
	 */
	public int updateByExampleSelective(IrpMicroblogAtmeKey record,
			IrpMicroblogAtmeExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_MICROBLOG_ATME.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MICROBLOG_ATME
	 * @ibatorgenerated  Wed May 15 15:53:49 CST 2013
	 */
	public int updateByExample(IrpMicroblogAtmeKey record,
			IrpMicroblogAtmeExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_MICROBLOG_ATME.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MICROBLOG_ATME
	 * @ibatorgenerated  Wed May 15 15:53:49 CST 2013
	 */
	public int updateByPrimaryKeySelective(IrpMicroblogAtmeKey record)
			throws SQLException {
		int rows = getSqlMapClientTemplate()
				.update("IRP_MICROBLOG_ATME.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_MICROBLOG_ATME
	 * @ibatorgenerated  Wed May 15 15:53:49 CST 2013
	 */
	public int updateByPrimaryKey(IrpMicroblogAtmeKey record) throws SQLException {
		int rows = getSqlMapClientTemplate()
				.update("IRP_MICROBLOG_ATME.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table IRP_MICROBLOG_ATME
	 * @ibatorgenerated  Wed May 15 15:53:49 CST 2013
	 */
	private static class UpdateByExampleParms extends IrpMicroblogAtmeExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				IrpMicroblogAtmeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<IrpMicroblogAtmeKey> selectByExample(
			IrpMicroblogAtmeExample example, PageUtil pageUtil)
			throws SQLException {
		   List<IrpMicroblogAtmeKey> list = getSqlMapClientTemplate().queryForList("IRP_MICROBLOG_ATME.ibatorgenerated_selectByExample", example,pageUtil.getPageIndex(),pageUtil.getPageSize());
	        return list;
	}
	@Override
	public int selectUnReadAtme(Map<String, Object> _mParam) throws SQLException {
		int nReadStatus = (Integer) getSqlMapClientTemplate().queryForObject("IRP_MICROBLOG_ATME.ibatorgenerated_selectUnReadAtme", _mParam);
		return nReadStatus;
	}
}