package com.tfs.irp.personalsearch.dao.impl;

import com.tfs.irp.personalsearch.dao.IrpPersonalSearchDAO;
import com.tfs.irp.personalsearch.entity.IrpPersonalSearch;
import com.tfs.irp.personalsearch.entity.IrpPersonalSearchExample;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpPersonalSearchDAOImpl extends SqlMapClientDaoSupport implements IrpPersonalSearchDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_personal_search
     *
     * @ibatorgenerated Thu Jul 24 09:39:19 CST 2014
     */
    public int countByExample(IrpPersonalSearchExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("irp_personal_search.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_personal_search
     *
     * @ibatorgenerated Thu Jul 24 09:39:19 CST 2014
     */
    public int deleteByExample(IrpPersonalSearchExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("irp_personal_search.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_personal_search
     *
     * @ibatorgenerated Thu Jul 24 09:39:19 CST 2014
     */
    public int deleteByPrimaryKey(Long personalsearchid) throws SQLException {
        IrpPersonalSearch key = new IrpPersonalSearch();
        key.setPersonalsearchid(personalsearchid);
        int rows = getSqlMapClientTemplate().delete("irp_personal_search.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_personal_search
     *
     * @ibatorgenerated Thu Jul 24 09:39:19 CST 2014
     */
    public void insert(IrpPersonalSearch record) throws SQLException {
        getSqlMapClientTemplate().insert("irp_personal_search.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_personal_search
     *
     * @ibatorgenerated Thu Jul 24 09:39:19 CST 2014
     */
    public void insertSelective(IrpPersonalSearch record) throws SQLException {
        getSqlMapClientTemplate().insert("irp_personal_search.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_personal_search
     *
     * @ibatorgenerated Thu Jul 24 09:39:19 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<IrpPersonalSearch> selectByExample(IrpPersonalSearchExample example) throws SQLException {
        List<IrpPersonalSearch> list = getSqlMapClientTemplate().queryForList("irp_personal_search.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_personal_search
     *
     * @ibatorgenerated Thu Jul 24 09:39:19 CST 2014
     */
    public IrpPersonalSearch selectByPrimaryKey(Long personalsearchid) throws SQLException {
        IrpPersonalSearch key = new IrpPersonalSearch();
        key.setPersonalsearchid(personalsearchid);
        IrpPersonalSearch record = (IrpPersonalSearch) getSqlMapClientTemplate().queryForObject("irp_personal_search.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_personal_search
     *
     * @ibatorgenerated Thu Jul 24 09:39:19 CST 2014
     */
    public int updateByExampleSelective(IrpPersonalSearch record, IrpPersonalSearchExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_personal_search.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_personal_search
     *
     * @ibatorgenerated Thu Jul 24 09:39:19 CST 2014
     */
    public int updateByExample(IrpPersonalSearch record, IrpPersonalSearchExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_personal_search.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_personal_search
     *
     * @ibatorgenerated Thu Jul 24 09:39:19 CST 2014
     */
    public int updateByPrimaryKeySelective(IrpPersonalSearch record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("irp_personal_search.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_personal_search
     *
     * @ibatorgenerated Thu Jul 24 09:39:19 CST 2014
     */
    public int updateByPrimaryKey(IrpPersonalSearch record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("irp_personal_search.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table irp_personal_search
     *
     * @ibatorgenerated Thu Jul 24 09:39:19 CST 2014
     */
    private static class UpdateByExampleParms extends IrpPersonalSearchExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpPersonalSearchExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}