package com.tfs.irp.messagecontent.dao.impl;

import com.tfs.irp.messagecontent.dao.IrpMessageContentDAO;
import com.tfs.irp.messagecontent.entity.IrpMessageContent;
import com.tfs.irp.messagecontent.entity.IrpMessageContentExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpMessageContentDAOImpl extends SqlMapClientDaoSupport implements IrpMessageContentDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MESSAGE_CONTENT
     *
     * @ibatorgenerated Sun Jun 09 16:47:42 CST 2013
     */
    public int countByExample(IrpMessageContentExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_MESSAGE_CONTENT.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MESSAGE_CONTENT
     *
     * @ibatorgenerated Sun Jun 09 16:47:42 CST 2013
     */
    public int deleteByExample(IrpMessageContentExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_MESSAGE_CONTENT.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MESSAGE_CONTENT
     *
     * @ibatorgenerated Sun Jun 09 16:47:42 CST 2013
     */
    public int deleteByPrimaryKey(Long messageid) throws SQLException {
        IrpMessageContent key = new IrpMessageContent();
        key.setMessageid(messageid);
        int rows = getSqlMapClientTemplate().delete("IRP_MESSAGE_CONTENT.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MESSAGE_CONTENT
     *
     * @ibatorgenerated Sun Jun 09 16:47:42 CST 2013
     */
    public void insert(IrpMessageContent record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_MESSAGE_CONTENT.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MESSAGE_CONTENT
     *
     * @ibatorgenerated Sun Jun 09 16:47:42 CST 2013
     */
    public void insertSelective(IrpMessageContent record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_MESSAGE_CONTENT.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MESSAGE_CONTENT
     *
     * @ibatorgenerated Sun Jun 09 16:47:42 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<IrpMessageContent> selectByExample(IrpMessageContentExample example) throws SQLException {
        List<IrpMessageContent> list = getSqlMapClientTemplate().queryForList("IRP_MESSAGE_CONTENT.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MESSAGE_CONTENT
     *
     * @ibatorgenerated Sun Jun 09 16:47:42 CST 2013
     */
    public IrpMessageContent selectByPrimaryKey(Long messageid) throws SQLException {
        IrpMessageContent key = new IrpMessageContent();
        key.setMessageid(messageid);
        IrpMessageContent record = (IrpMessageContent) getSqlMapClientTemplate().queryForObject("IRP_MESSAGE_CONTENT.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MESSAGE_CONTENT
     *
     * @ibatorgenerated Sun Jun 09 16:47:42 CST 2013
     */
    public int updateByExampleSelective(IrpMessageContent record, IrpMessageContentExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_MESSAGE_CONTENT.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MESSAGE_CONTENT
     *
     * @ibatorgenerated Sun Jun 09 16:47:42 CST 2013
     */
    public int updateByExample(IrpMessageContent record, IrpMessageContentExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_MESSAGE_CONTENT.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MESSAGE_CONTENT
     *
     * @ibatorgenerated Sun Jun 09 16:47:42 CST 2013
     */
    public int updateByPrimaryKeySelective(IrpMessageContent record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_MESSAGE_CONTENT.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MESSAGE_CONTENT
     *
     * @ibatorgenerated Sun Jun 09 16:47:42 CST 2013
     */
    public int updateByPrimaryKey(IrpMessageContent record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_MESSAGE_CONTENT.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table IRP_MESSAGE_CONTENT
     *
     * @ibatorgenerated Sun Jun 09 16:47:42 CST 2013
     */
    private static class UpdateByExampleParms extends IrpMessageContentExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpMessageContentExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    @Override
   	public List selectGroupByUserid(Long _fromUid,Integer _isdel,Long _crisdel,PageUtil pageUtil) {
   		// TODO Auto-generated method stub
   		List useridlist = null;
   		Map map = new HashMap();
        map.put("fromUid", _fromUid);
        map.put("isdel", _isdel);
        map.put("crisdel", _crisdel);
		useridlist = this.getSqlMapClientTemplate().queryForList("IRP_MESSAGE_CONTENT.ibatorgenerated_selectGroupByFromUid",map,pageUtil.getPageIndex(),pageUtil.getPageSize());
   		return useridlist;
   	}
   	@Override
   	public List<IrpMessageContent> selectByExample(
   			IrpMessageContentExample example, PageUtil pageUtil)
   			throws SQLException {
           List<IrpMessageContent> list = getSqlMapClientTemplate().queryForList("IRP_MESSAGE_CONTENT.ibatorgenerated_selectByExample", example,pageUtil.getPageIndex(),pageUtil.getPageSize());
           return list;
   	}
   	@Override
   	public int selectGroupByUseridCount(Long _fromUid,Integer _isdel,Long _crisdel) {
   		// TODO Auto-generated method stub
   		int nCount = 0;
   		Map map = new HashMap();
        map.put("fromUid", _fromUid);
        map.put("isdel", _isdel);
        map.put("crisdel", _crisdel);
		nCount = this.getSqlMapClientTemplate().queryForList("IRP_MESSAGE_CONTENT.ibatorgenerated_selectGroupByFromUid",map).size();
   		return nCount;
   	}

   	@Override
   	public List selectDetailMessage(Long _cruserid, Integer _isdel, Long fromUid,Long _crisdel,PageUtil pageUtil) {
   		// TODO Auto-generated method stub
   		List detailList = null;
   		Map map = new HashMap();
   		map.put("cruserid", _cruserid);
   		map.put("isdel", _isdel);
   		map.put("fromUid", fromUid);
   		map.put("crisdel", _crisdel);
   		detailList = this.getSqlMapClientTemplate().queryForList("IRP_MESSAGE_CONTENT.ibatorgenerated_selectDetailMessage", map,pageUtil.getPageIndex(),pageUtil.getPageSize());
   		return detailList;
   	}
   	@Override
   	public List selectDetailMessage(IrpMessageContentExample example,PageUtil pageUtil) {
   		// TODO Auto-generated method stub
   		List detailList = null;
   		detailList = this.getSqlMapClientTemplate().queryForList("IRP_MESSAGE_CONTENT.ibatorgenerated_selectByExample", example,pageUtil.getPageIndex(),pageUtil.getPageSize());
   		return detailList;
   	}

   	@Override
   	public int selectDetailMessageCount(Long _cruserid, Integer _isdel,
   			Long fromUid,Long _crisdel) {
   		int nCount = 0;
   		Map map = new HashMap();
   		map.put("cruserid", _cruserid);
   		map.put("isdel", _isdel);
   		map.put("fromUid", fromUid);
   		map.put("crisdel", _crisdel);
   		nCount = this.getSqlMapClientTemplate().queryForList("IRP_MESSAGE_CONTENT.ibatorgenerated_selectDetailMessage", map).size();
   		return nCount;
   	}
   	@Override
   	public int selectDetailMessageCount(IrpMessageContentExample example) {
   		int nCount = 0;
   		nCount = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_MESSAGE_CONTENT.ibatorgenerated_countByExample", example);
   		return nCount;
   	}

	@Override
	public List selectMessageidInCridFrid(Long _cruserid, Long _fromUid) {
		// TODO Auto-generated method stub
		List crfrlist = null;
		Map map = new HashMap();
		map.put("fromUid", _fromUid);
		map.put("cruserid", _cruserid);
		crfrlist =	this.getSqlMapClientTemplate().queryForList("IRP_MESSAGE_CONTENT.ibatorgenerated_selectMessageidOfFrandCr", map);
		return crfrlist;
	}

	@Override
	public List selectMessageidAll(Long _loginid) {
		// TODO Auto-generated method stub
		List  allmicroblogid = null;
		Map map = new HashMap();
		map.put("loginid", _loginid);
		allmicroblogid = this.getSqlMapClientTemplate().queryForList("IRP_MESSAGE_CONTENT.ibatorgenerated_selectMessageidAll", map);
		return allmicroblogid;
	}

	@Override
	public int selectUnReadMessage(Map<String, Object> _mParam) throws SQLException {
		int nReadStatus = (Integer) getSqlMapClientTemplate().queryForObject("IRP_MESSAGE_CONTENT.ibatorgenerated_selectUnReadMessage", _mParam);
		return nReadStatus;
	}
	@Override
	public int selectUnReadMsg(Map<String, Object> _mParam) throws SQLException {
		int nReadStatus = (Integer) getSqlMapClientTemplate().queryForObject("IRP_MESSAGE_CONTENT.ibatorgenerated_selectUnReadMsg", _mParam);
		return nReadStatus;
	}
	@Override
	public int selectUnReadMessage(long _fromUid, Integer _browsestatus, long _cruserid) {
		int nReadStatus = 0;
		Map map = new HashMap();
		map.put("fromUid", _fromUid);
		map.put("browsestatus", _browsestatus);
		map.put("cruserid", _cruserid);
		map.put("del_status_first", IrpMessageContent.BOTHSTATUS);
		map.put("del_status_second", IrpMessageContent.FROMSTATUS);
		nReadStatus =Integer.valueOf(this.getSqlMapClientTemplate().queryForObject("IRP_MESSAGE_CONTENT.ibatorgenerated_selectUnReadMessageDetail",map).toString());
		return nReadStatus;
	}
}