package com.tfs.irp.workflow.entity;

import com.tfs.irp.base.IrpBaseObj;

public class IrpObjWorkflowLink extends IrpBaseObj{

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_OBJ_WORKFLOW_LINK.OBJFLOWID
	 * @ibatorgenerated  Tue May 14 15:40:19 CST 2013
	 */
	private Long objflowid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_OBJ_WORKFLOW_LINK.FLOWID
	 * @ibatorgenerated  Tue May 14 15:40:19 CST 2013
	 */
	private Long flowid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_OBJ_WORKFLOW_LINK.OBJID
	 * @ibatorgenerated  Tue May 14 15:40:19 CST 2013
	 */
	private Long objid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IRP_OBJ_WORKFLOW_LINK.OBJTYPE
	 * @ibatorgenerated  Tue May 14 15:40:19 CST 2013
	 */
	private String objtype;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_OBJ_WORKFLOW_LINK.OBJFLOWID
	 * @return  the value of IRP_OBJ_WORKFLOW_LINK.OBJFLOWID
	 * @ibatorgenerated  Tue May 14 15:40:19 CST 2013
	 */
	public Long getObjflowid() {
		return objflowid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_OBJ_WORKFLOW_LINK.OBJFLOWID
	 * @param objflowid  the value for IRP_OBJ_WORKFLOW_LINK.OBJFLOWID
	 * @ibatorgenerated  Tue May 14 15:40:19 CST 2013
	 */
	public void setObjflowid(Long objflowid) {
		this.objflowid = objflowid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_OBJ_WORKFLOW_LINK.FLOWID
	 * @return  the value of IRP_OBJ_WORKFLOW_LINK.FLOWID
	 * @ibatorgenerated  Tue May 14 15:40:19 CST 2013
	 */
	public Long getFlowid() {
		return flowid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_OBJ_WORKFLOW_LINK.FLOWID
	 * @param flowid  the value for IRP_OBJ_WORKFLOW_LINK.FLOWID
	 * @ibatorgenerated  Tue May 14 15:40:19 CST 2013
	 */
	public void setFlowid(Long flowid) {
		this.flowid = flowid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_OBJ_WORKFLOW_LINK.OBJID
	 * @return  the value of IRP_OBJ_WORKFLOW_LINK.OBJID
	 * @ibatorgenerated  Tue May 14 15:40:19 CST 2013
	 */
	public Long getObjid() {
		return objid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_OBJ_WORKFLOW_LINK.OBJID
	 * @param objid  the value for IRP_OBJ_WORKFLOW_LINK.OBJID
	 * @ibatorgenerated  Tue May 14 15:40:19 CST 2013
	 */
	public void setObjid(Long objid) {
		this.objid = objid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IRP_OBJ_WORKFLOW_LINK.OBJTYPE
	 * @return  the value of IRP_OBJ_WORKFLOW_LINK.OBJTYPE
	 * @ibatorgenerated  Tue May 14 15:40:19 CST 2013
	 */
	public String getObjtype() {
		return objtype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IRP_OBJ_WORKFLOW_LINK.OBJTYPE
	 * @param objtype  the value for IRP_OBJ_WORKFLOW_LINK.OBJTYPE
	 * @ibatorgenerated  Tue May 14 15:40:19 CST 2013
	 */
	public void setObjtype(String objtype) {
		this.objtype = objtype;
	}
	
	/** 对象表名 **/
    public final static String TABLE_NAME = "IRP_OBJ_WORKFLOW_LINK";
    
    /** 主键字段名 **/
    public final static String ID_FIELD_NAME = "OBJFLOWID";

	@Override
	public Long getId() {
		return this.objflowid;
	}

	@Override
	public String getName() {
		return "";
	}

	@Override
	public String getTableName() {
		return TABLE_NAME;
	}

	@Override
	public String getIdFieldName() {
		return ID_FIELD_NAME;
	}
}