package com.tfs.irp.testpaper.dao;

import com.tfs.irp.testpaper.entity.IrpTestpaper;
import com.tfs.irp.testpaper.entity.IrpTestpaperExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.List;

public interface IrpTestpaperDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_testpaper
     *
     * @ibatorgenerated Fri Sep 19 16:19:47 CST 2014
     */
    int countByExample(IrpTestpaperExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_testpaper
     *
     * @ibatorgenerated Fri Sep 19 16:19:47 CST 2014
     */
    int deleteByExample(IrpTestpaperExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_testpaper
     *
     * @ibatorgenerated Fri Sep 19 16:19:47 CST 2014
     */
    int deleteByPrimaryKey(Long paperid) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_testpaper
     *
     * @ibatorgenerated Fri Sep 19 16:19:47 CST 2014
     */
    void insert(IrpTestpaper record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_testpaper
     *
     * @ibatorgenerated Fri Sep 19 16:19:47 CST 2014
     */
    void insertSelective(IrpTestpaper record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_testpaper
     *
     * @ibatorgenerated Fri Sep 19 16:19:47 CST 2014
     */
    List<IrpTestpaper> selectByExample(IrpTestpaperExample example) throws SQLException;
    
    List<IrpTestpaper> selectByExample(IrpTestpaperExample example,PageUtil _pageutil) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_testpaper
     *
     * @ibatorgenerated Fri Sep 19 16:19:47 CST 2014
     */
    IrpTestpaper selectByPrimaryKey(Long paperid) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_testpaper
     *
     * @ibatorgenerated Fri Sep 19 16:19:47 CST 2014
     */
    int updateByExampleSelective(IrpTestpaper record, IrpTestpaperExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_testpaper
     *
     * @ibatorgenerated Fri Sep 19 16:19:47 CST 2014
     */
    int updateByExample(IrpTestpaper record, IrpTestpaperExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_testpaper
     *
     * @ibatorgenerated Fri Sep 19 16:19:47 CST 2014
     */
    int updateByPrimaryKeySelective(IrpTestpaper record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_testpaper
     *
     * @ibatorgenerated Fri Sep 19 16:19:47 CST 2014
     */
    int updateByPrimaryKey(IrpTestpaper record) throws SQLException;
}