package com.tfs.irp.voteoptions.dao.impl;

import com.tfs.irp.vote.entity.IrpVote;
import com.tfs.irp.voteoptions.dao.IrpVoteOptionsDAO;
import com.tfs.irp.voteoptions.entity.IrpVoteOptions;
import com.tfs.irp.voteoptions.entity.IrpVoteOptionsExample;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpVoteOptionsDAOImpl extends SqlMapClientDaoSupport implements IrpVoteOptionsDAO {
    
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_VOTEOPTIONS
     *
     * @ibatorgenerated Wed Nov 13 13:09:32 CST 2013
     */
    public int countByExample(IrpVoteOptionsExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_VOTEOPTIONS.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_VOTEOPTIONS
     *
     * @ibatorgenerated Wed Nov 13 13:09:32 CST 2013
     */
    public int deleteByExample(IrpVoteOptionsExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_VOTEOPTIONS.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_VOTEOPTIONS
     *
     * @ibatorgenerated Wed Nov 13 13:09:32 CST 2013
     */
    public int deleteByPrimaryKey(Long optionid) throws SQLException {
        IrpVoteOptions key = new IrpVoteOptions();
        key.setOptionid(optionid);
        int rows = getSqlMapClientTemplate().delete("IRP_VOTEOPTIONS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_VOTEOPTIONS
     *
     * @ibatorgenerated Wed Nov 13 13:09:32 CST 2013
     */
    public void insert(IrpVoteOptions record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_VOTEOPTIONS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_VOTEOPTIONS
     *
     * @ibatorgenerated Wed Nov 13 13:09:32 CST 2013
     */
    public void insertSelective(IrpVoteOptions record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_VOTEOPTIONS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_VOTEOPTIONS
     *
     * @ibatorgenerated Wed Nov 13 13:09:32 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<IrpVoteOptions> selectByExample(IrpVoteOptionsExample example) throws SQLException {
        List<IrpVoteOptions> list = getSqlMapClientTemplate().queryForList("IRP_VOTEOPTIONS.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_VOTEOPTIONS
     *
     * @ibatorgenerated Wed Nov 13 13:09:32 CST 2013
     */
    public IrpVoteOptions selectByPrimaryKey(Long optionid) throws SQLException {
        IrpVoteOptions key = new IrpVoteOptions();
        key.setOptionid(optionid);
        IrpVoteOptions record = (IrpVoteOptions) getSqlMapClientTemplate().queryForObject("IRP_VOTEOPTIONS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_VOTEOPTIONS
     *
     * @ibatorgenerated Wed Nov 13 13:09:32 CST 2013
     */
    public int updateByExampleSelective(IrpVoteOptions record, IrpVoteOptionsExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_VOTEOPTIONS.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_VOTEOPTIONS
     *
     * @ibatorgenerated Wed Nov 13 13:09:32 CST 2013
     */
    public int updateByExample(IrpVoteOptions record, IrpVoteOptionsExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_VOTEOPTIONS.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_VOTEOPTIONS
     *
     * @ibatorgenerated Wed Nov 13 13:09:32 CST 2013
     */
    public int updateByPrimaryKeySelective(IrpVoteOptions record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_VOTEOPTIONS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_VOTEOPTIONS
     *
     * @ibatorgenerated Wed Nov 13 13:09:32 CST 2013
     */
    public int updateByPrimaryKey(IrpVoteOptions record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_VOTEOPTIONS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table IRP_VOTEOPTIONS
     *
     * @ibatorgenerated Wed Nov 13 13:09:32 CST 2013
     */
    private static class UpdateByExampleParms extends IrpVoteOptionsExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpVoteOptionsExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
    }

}