package com.tfs.irp.projecttaskperson.dao;

import com.tfs.irp.projecttaskperson.entity.IrpProjectTaskPerson;
import com.tfs.irp.projecttaskperson.entity.IrpProjectTaskPersonExample;
import java.sql.SQLException;
import java.util.List;

public interface IrpProjectTaskPersonDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_TASK_PERSON
     *
     * @ibatorgenerated Wed Jun 19 14:52:02 CST 2013
     */
    int countByExample(IrpProjectTaskPersonExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_TASK_PERSON
     *
     * @ibatorgenerated Wed Jun 19 14:52:02 CST 2013
     */
    int deleteByExample(IrpProjectTaskPersonExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_TASK_PERSON
     *
     * @ibatorgenerated Wed Jun 19 14:52:02 CST 2013
     */
    void insert(IrpProjectTaskPerson record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_TASK_PERSON
     *
     * @ibatorgenerated Wed Jun 19 14:52:02 CST 2013
     */
    void insertSelective(IrpProjectTaskPerson record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_TASK_PERSON
     *
     * @ibatorgenerated Wed Jun 19 14:52:02 CST 2013
     */
    List<IrpProjectTaskPerson> selectByExample(IrpProjectTaskPersonExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_TASK_PERSON
     *
     * @ibatorgenerated Wed Jun 19 14:52:02 CST 2013
     */
    int updateByExampleSelective(IrpProjectTaskPerson record, IrpProjectTaskPersonExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_PROJECT_TASK_PERSON
     *
     * @ibatorgenerated Wed Jun 19 14:52:02 CST 2013
     */
    int updateByExample(IrpProjectTaskPerson record, IrpProjectTaskPersonExample example) throws SQLException;
    
    /**
     * 获取登陆者参与的所有任务id
     */
    List<Long> myJoinTaskId(IrpProjectTaskPersonExample example) throws SQLException;
}