package com.tfs.irp.bug.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.tfs.irp.bug.dao.IrpBugDAO;
import com.tfs.irp.bug.entity.IrpBugWithBLOBs;
import com.tfs.irp.bug.entity.IrpBugExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpBugDAOImpl extends SqlMapClientDaoSupport implements IrpBugDAO {
	
	
    public IrpBugDAOImpl() {
    	
	}
    

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table IRP_BUG
     *
     * @ibatorgenerated Tue Jan 05 16:50:18 CST 2016
     */
    

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_BUG
     *
     * @ibatorgenerated Tue Jan 05 16:50:18 CST 2016
     */
  

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_BUG
     *
     * @ibatorgenerated Tue Jan 05 16:50:18 CST 2016
     */
    public int countByExample(IrpBugExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_BUG.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_BUG
     *
     * @ibatorgenerated Tue Jan 05 16:50:18 CST 2016
     */
    public int deleteByExample(IrpBugExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_BUG.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_BUG
     *
     * @ibatorgenerated Tue Jan 05 16:50:18 CST 2016
     */
    public int deleteByPrimaryKey(Long bugid) throws SQLException {
        IrpBugWithBLOBs key = new IrpBugWithBLOBs();
        key.setBugid(bugid);
        int rows = getSqlMapClientTemplate().delete("IRP_BUG.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_BUG
     *
     * @ibatorgenerated Tue Jan 05 16:50:18 CST 2016
     */
    public void insert(IrpBugWithBLOBs record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_BUG.ibatorgenerated_insert_page", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_BUG
     *
     * @ibatorgenerated Tue Jan 05 16:50:18 CST 2016
     */
    public void insertSelective(IrpBugWithBLOBs record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_BUG.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_BUG
     *
     * @ibatorgenerated Tue Jan 05 16:50:18 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<IrpBugWithBLOBs> selectByExample(IrpBugExample example,PageUtil page) throws SQLException {
        List<IrpBugWithBLOBs> list = getSqlMapClientTemplate().queryForList("IRP_BUG.ibatorgenerated_selectByExampleWithBLOBs", example,page.getPageIndex(),page.getPageSize());
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_BUG
     *
     * @ibatorgenerated Tue Jan 05 16:50:18 CST 2016
     */
    public IrpBugWithBLOBs selectByPrimaryKey(Long bugid) throws SQLException {
        IrpBugWithBLOBs key = new IrpBugWithBLOBs();
        key.setBugid(bugid);
        IrpBugWithBLOBs record = (IrpBugWithBLOBs) getSqlMapClientTemplate().queryForObject("IRP_BUG.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_BUG
     *
     * @ibatorgenerated Tue Jan 05 16:50:18 CST 2016
     */
    public int updateByExampleSelective(IrpBugWithBLOBs record, IrpBugExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_BUG.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_BUG
     *
     * @ibatorgenerated Tue Jan 05 16:50:18 CST 2016
     */
    public int updateByExample(IrpBugWithBLOBs record, IrpBugExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_BUG.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_BUG
     *
     * @ibatorgenerated Tue Jan 05 16:50:18 CST 2016
     */
    public int updateByPrimaryKeySelective(IrpBugWithBLOBs record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_BUG.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_BUG
     *
     * @ibatorgenerated Tue Jan 05 16:50:18 CST 2016
     */
    public int updateByPrimaryKey(IrpBugWithBLOBs record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_BUG.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table IRP_BUG
     *
     * @ibatorgenerated Tue Jan 05 16:50:18 CST 2016
     */
    private static class UpdateByExampleParms extends IrpBugExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpBugExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<IrpBugWithBLOBs> selectByExample(IrpBugExample example)
			throws SQLException {
		 List<IrpBugWithBLOBs> list = getSqlMapClientTemplate().queryForList("IRP_BUG.ibatorgenerated_selectByExampleWithBLOBs", example);
		return list;
	}
}