package com.tfs.irp.configType.dao.impl;

import com.tfs.irp.configType.dao.IrpConfigTypeDAO;
import com.tfs.irp.configType.entity.IrpConfigType;
import com.tfs.irp.configType.entity.IrpConfigTypeExample;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpConfigTypeDAOImpl extends SqlMapClientDaoSupport implements IrpConfigTypeDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG_TYPE
     *
     * @ibatorgenerated Fri Mar 22 16:24:53 CST 2013
     */
    public int countByExample(IrpConfigTypeExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_IRP_CONFIG_TYPE.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG_TYPE
     *
     * @ibatorgenerated Fri Mar 22 16:24:53 CST 2013
     */
    public int deleteByExample(IrpConfigTypeExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_IRP_CONFIG_TYPE.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG_TYPE
     *
     * @ibatorgenerated Fri Mar 22 16:24:53 CST 2013
     */
    public int deleteByPrimaryKey(Long configtypeid) throws SQLException {
        IrpConfigType key = new IrpConfigType();
        key.setConfigtypeid(configtypeid);
        int rows = getSqlMapClientTemplate().delete("IRP_IRP_CONFIG_TYPE.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG_TYPE
     *
     * @ibatorgenerated Fri Mar 22 16:24:53 CST 2013
     */
    public void insert(IrpConfigType record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_IRP_CONFIG_TYPE.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG_TYPE
     *
     * @ibatorgenerated Fri Mar 22 16:24:53 CST 2013
     */
    public void insertSelective(IrpConfigType record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_IRP_CONFIG_TYPE.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG_TYPE
     *
     * @ibatorgenerated Fri Mar 22 16:24:53 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<IrpConfigType> selectByExample(IrpConfigTypeExample example) throws SQLException {
        List<IrpConfigType> list = getSqlMapClientTemplate().queryForList("IRP_IRP_CONFIG_TYPE.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG_TYPE
     *
     * @ibatorgenerated Fri Mar 22 16:24:53 CST 2013
     */
    public IrpConfigType selectByPrimaryKey(Long configtypeid) throws SQLException {
        IrpConfigType key = new IrpConfigType();
        key.setConfigtypeid(configtypeid);
        IrpConfigType record = (IrpConfigType) getSqlMapClientTemplate().queryForObject("IRP_IRP_CONFIG_TYPE.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG_TYPE
     *
     * @ibatorgenerated Fri Mar 22 16:24:53 CST 2013
     */
    public int updateByExampleSelective(IrpConfigType record, IrpConfigTypeExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_IRP_CONFIG_TYPE.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG_TYPE
     *
     * @ibatorgenerated Fri Mar 22 16:24:53 CST 2013
     */
    public int updateByExample(IrpConfigType record, IrpConfigTypeExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_IRP_CONFIG_TYPE.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG_TYPE
     *
     * @ibatorgenerated Fri Mar 22 16:24:53 CST 2013
     */
    public int updateByPrimaryKeySelective(IrpConfigType record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_IRP_CONFIG_TYPE.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP.IRP_CONFIG_TYPE
     *
     * @ibatorgenerated Fri Mar 22 16:24:53 CST 2013
     */
    public int updateByPrimaryKey(IrpConfigType record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_IRP_CONFIG_TYPE.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table IRP.IRP_CONFIG_TYPE
     *
     * @ibatorgenerated Fri Mar 22 16:24:53 CST 2013
     */
    private static class UpdateByExampleParms extends IrpConfigTypeExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpConfigTypeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}