package com.tfs.irp.userprivacy.dao;

import com.tfs.irp.userprivacy.entity.IrpUserPrivacy;
import com.tfs.irp.userprivacy.entity.IrpUserPrivacyExample;
import java.sql.SQLException;
import java.util.List;

public interface IrpUserPrivacyDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_USER_PRIVACY
	 * @ibatorgenerated  Mon Aug 05 13:54:27 CST 2013
	 */
	int countByExample(IrpUserPrivacyExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_USER_PRIVACY
	 * @ibatorgenerated  Mon Aug 05 13:54:27 CST 2013
	 */
	int deleteByExample(IrpUserPrivacyExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_USER_PRIVACY
	 * @ibatorgenerated  Mon Aug 05 13:54:27 CST 2013
	 */
	void insert(IrpUserPrivacy record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_USER_PRIVACY
	 * @ibatorgenerated  Mon Aug 05 13:54:27 CST 2013
	 */
	void insertSelective(IrpUserPrivacy record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_USER_PRIVACY
	 * @ibatorgenerated  Mon Aug 05 13:54:27 CST 2013
	 */
	List<IrpUserPrivacy> selectByExample(IrpUserPrivacyExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_USER_PRIVACY
	 * @ibatorgenerated  Mon Aug 05 13:54:27 CST 2013
	 */
	int updateByExampleSelective(IrpUserPrivacy record,
			IrpUserPrivacyExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_USER_PRIVACY
	 * @ibatorgenerated  Mon Aug 05 13:54:27 CST 2013
	 */
	int updateByExample(IrpUserPrivacy record, IrpUserPrivacyExample example)
			throws SQLException;
}