package com.tfs.irp.chnl_doc_link.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.math.BigDecimal;

import com.tfs.irp.channel.entity.IrpChannelExample.Criteria;

public class IrpChnlDocLinkExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table IRP_CHNL_DOC_LINK
	 * @ibatorgenerated  Fri Sep 27 15:45:21 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table IRP_CHNL_DOC_LINK
	 * @ibatorgenerated  Fri Sep 27 15:45:21 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_CHNL_DOC_LINK
	 * @ibatorgenerated  Fri Sep 27 15:45:21 CST 2013
	 */
	public IrpChnlDocLinkExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_CHNL_DOC_LINK
	 * @ibatorgenerated  Fri Sep 27 15:45:21 CST 2013
	 */
	protected IrpChnlDocLinkExample(IrpChnlDocLinkExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_CHNL_DOC_LINK
	 * @ibatorgenerated  Fri Sep 27 15:45:21 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_CHNL_DOC_LINK
	 * @ibatorgenerated  Fri Sep 27 15:45:21 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_CHNL_DOC_LINK
	 * @ibatorgenerated  Fri Sep 27 15:45:21 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_CHNL_DOC_LINK
	 * @ibatorgenerated  Fri Sep 27 15:45:21 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_CHNL_DOC_LINK
	 * @ibatorgenerated  Fri Sep 27 15:45:21 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_CHNL_DOC_LINK
	 * @ibatorgenerated  Fri Sep 27 15:45:21 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_CHNL_DOC_LINK
	 * @ibatorgenerated  Fri Sep 27 15:45:21 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table IRP_CHNL_DOC_LINK
	 * @ibatorgenerated  Fri Sep 27 15:45:21 CST 2013
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andChnldocidIsNull() {
			addCriterion("CHNLDOCID is null");
			return this;
		}

		public Criteria andChnldocidIsNotNull() {
			addCriterion("CHNLDOCID is not null");
			return this;
		}

		public Criteria andChnldocidEqualTo(Long value) {
			addCriterion("CHNLDOCID =", value, "chnldocid");
			return this;
		}

		public Criteria andChnldocidNotEqualTo(Long value) {
			addCriterion("CHNLDOCID <>", value, "chnldocid");
			return this;
		}

		public Criteria andChnldocidGreaterThan(Long value) {
			addCriterion("CHNLDOCID >", value, "chnldocid");
			return this;
		}

		public Criteria andChnldocidGreaterThanOrEqualTo(Long value) {
			addCriterion("CHNLDOCID >=", value, "chnldocid");
			return this;
		}

		public Criteria andChnldocidLessThan(Long value) {
			addCriterion("CHNLDOCID <", value, "chnldocid");
			return this;
		}

		public Criteria andChnldocidLessThanOrEqualTo(Long value) {
			addCriterion("CHNLDOCID <=", value, "chnldocid");
			return this;
		}

		public Criteria andChnldocidIn(List<Long> values) {
			addCriterion("CHNLDOCID in", values, "chnldocid");
			return this;
		}

		public Criteria andChnldocidNotIn(List<Long> values) {
			addCriterion("CHNLDOCID not in", values, "chnldocid");
			return this;
		}

		public Criteria andChnldocidBetween(Long value1, Long value2) {
			addCriterion("CHNLDOCID between", value1, value2, "chnldocid");
			return this;
		}

		public Criteria andChnldocidNotBetween(Long value1, Long value2) {
			addCriterion("CHNLDOCID not between", value1, value2, "chnldocid");
			return this;
		}

		public Criteria andChannelidIsNull() {
			addCriterion("CHANNELID is null");
			return this;
		}

		public Criteria andChannelidIsNotNull() {
			addCriterion("CHANNELID is not null");
			return this;
		}

		public Criteria andChannelidEqualTo(Long value) {
			addCriterion("CHANNELID =", value, "channelid");
			return this;
		}

		public Criteria andChannelidNotEqualTo(Long value) {
			addCriterion("CHANNELID <>", value, "channelid");
			return this;
		}

		public Criteria andChannelidGreaterThan(Long value) {
			addCriterion("CHANNELID >", value, "channelid");
			return this;
		}

		public Criteria andChannelidGreaterThanOrEqualTo(Long value) {
			addCriterion("CHANNELID >=", value, "channelid");
			return this;
		}

		public Criteria andChannelidLessThan(Long value) {
			addCriterion("CHANNELID <", value, "channelid");
			return this;
		}

		public Criteria andChannelidLessThanOrEqualTo(Long value) {
			addCriterion("CHANNELID <=", value, "channelid");
			return this;
		}

		public Criteria andChannelidIn(List<Long> values) {
			addCriterion("CHANNELID in", values, "channelid");
			return this;
		}

		public Criteria andChannelidNotIn(List<Long> values) {
			addCriterion("CHANNELID not in", values, "channelid");
			return this;
		}

		public Criteria andChannelidBetween(Long value1, Long value2) {
			addCriterion("CHANNELID between", value1, value2, "channelid");
			return this;
		}

		public Criteria andChannelidNotBetween(Long value1, Long value2) {
			addCriterion("CHANNELID not between", value1, value2, "channelid");
			return this;
		}

		public Criteria andDocidIsNull() {
			addCriterion("DOCID is null");
			return this;
		}

		public Criteria andDocidIsNotNull() {
			addCriterion("DOCID is not null");
			return this;
		}

		public Criteria andDocidEqualTo(Long value) {
			addCriterion("DOCID =", value, "docid");
			return this;
		}

		public Criteria andDocidNotEqualTo(Long value) {
			addCriterion("DOCID <>", value, "docid");
			return this;
		}

		public Criteria andDocidGreaterThan(Long value) {
			addCriterion("DOCID >", value, "docid");
			return this;
		}

		public Criteria andDocidGreaterThanOrEqualTo(Long value) {
			addCriterion("DOCID >=", value, "docid");
			return this;
		}

		public Criteria andDocidLessThan(Long value) {
			addCriterion("DOCID <", value, "docid");
			return this;
		}

		public Criteria andDocidLessThanOrEqualTo(Long value) {
			addCriterion("DOCID <=", value, "docid");
			return this;
		}

		public Criteria andDocidIn(List<Long> values) {
			addCriterion("DOCID in", values, "docid");
			return this;
		}

		public Criteria andDocidNotIn(List<Long> values) {
			addCriterion("DOCID not in", values, "docid");
			return this;
		}

		public Criteria andDocidBetween(Long value1, Long value2) {
			addCriterion("DOCID between", value1, value2, "docid");
			return this;
		}

		public Criteria andDocidNotBetween(Long value1, Long value2) {
			addCriterion("DOCID not between", value1, value2, "docid");
			return this;
		}

		public Criteria andDoctitleIsNull() {
			addCriterion("DOCTITLE is null");
			return this;
		}

		public Criteria andDoctitleIsNotNull() {
			addCriterion("DOCTITLE is not null");
			return this;
		}

		public Criteria andDoctitleEqualTo(String value) {
			addCriterion("DOCTITLE =", value, "doctitle");
			return this;
		}

		public Criteria andDoctitleNotEqualTo(String value) {
			addCriterion("DOCTITLE <>", value, "doctitle");
			return this;
		}

		public Criteria andDoctitleGreaterThan(String value) {
			addCriterion("DOCTITLE >", value, "doctitle");
			return this;
		}

		public Criteria andDoctitleGreaterThanOrEqualTo(String value) {
			addCriterion("DOCTITLE >=", value, "doctitle");
			return this;
		}

		public Criteria andDoctitleLessThan(String value) {
			addCriterion("DOCTITLE <", value, "doctitle");
			return this;
		}

		public Criteria andDoctitleLessThanOrEqualTo(String value) {
			addCriterion("DOCTITLE <=", value, "doctitle");
			return this;
		}

		public Criteria andDoctitleLike(String value) {
			addCriterion("DOCTITLE like", value, "doctitle");
			return this;
		}

		public Criteria andDoctitleNotLike(String value) {
			addCriterion("DOCTITLE not like", value, "doctitle");
			return this;
		}

		public Criteria andDoctitleIn(List<String> values) {
			addCriterion("DOCTITLE in", values, "doctitle");
			return this;
		}

		public Criteria andDoctitleNotIn(List<String> values) {
			addCriterion("DOCTITLE not in", values, "doctitle");
			return this;
		}

		public Criteria andDoctitleBetween(String value1, String value2) {
			addCriterion("DOCTITLE between", value1, value2, "doctitle");
			return this;
		}

		public Criteria andDoctitleNotBetween(String value1, String value2) {
			addCriterion("DOCTITLE not between", value1, value2, "doctitle");
			return this;
		}

		public Criteria andDocorderIsNull() {
			addCriterion("DOCORDER is null");
			return this;
		}

		public Criteria andDocorderIsNotNull() {
			addCriterion("DOCORDER is not null");
			return this;
		}

		public Criteria andDocorderEqualTo(Long value) {
			addCriterion("DOCORDER =", value, "docorder");
			return this;
		}

		public Criteria andDocorderNotEqualTo(Long value) {
			addCriterion("DOCORDER <>", value, "docorder");
			return this;
		}

		public Criteria andDocorderGreaterThan(Long value) {
			addCriterion("DOCORDER >", value, "docorder");
			return this;
		}

		public Criteria andDocorderGreaterThanOrEqualTo(Long value) {
			addCriterion("DOCORDER >=", value, "docorder");
			return this;
		}

		public Criteria andDocorderLessThan(Long value) {
			addCriterion("DOCORDER <", value, "docorder");
			return this;
		}

		public Criteria andDocorderLessThanOrEqualTo(Long value) {
			addCriterion("DOCORDER <=", value, "docorder");
			return this;
		}

		public Criteria andDocorderIn(List<Long> values) {
			addCriterion("DOCORDER in", values, "docorder");
			return this;
		}

		public Criteria andDocorderNotIn(List<Long> values) {
			addCriterion("DOCORDER not in", values, "docorder");
			return this;
		}

		public Criteria andDocorderBetween(Long value1, Long value2) {
			addCriterion("DOCORDER between", value1, value2, "docorder");
			return this;
		}

		public Criteria andDocorderNotBetween(Long value1, Long value2) {
			addCriterion("DOCORDER not between", value1, value2, "docorder");
			return this;
		}

		public Criteria andDocstatusIsNull() {
			addCriterion("DOCSTATUS is null");
			return this;
		}

		public Criteria andDocstatusIsNotNull() {
			addCriterion("DOCSTATUS is not null");
			return this;
		}

		public Criteria andDocstatusEqualTo(Long value) {
			addCriterion("DOCSTATUS =", value, "docstatus");
			return this;
		}

		public Criteria andDocstatusNotEqualTo(Long value) {
			addCriterion("DOCSTATUS <>", value, "docstatus");
			return this;
		}

		public Criteria andDocstatusGreaterThan(Long value) {
			addCriterion("DOCSTATUS >", value, "docstatus");
			return this;
		}

		public Criteria andDocstatusGreaterThanOrEqualTo(Long value) {
			addCriterion("DOCSTATUS >=", value, "docstatus");
			return this;
		}

		public Criteria andDocstatusLessThan(Long value) {
			addCriterion("DOCSTATUS <", value, "docstatus");
			return this;
		}

		public Criteria andDocstatusLessThanOrEqualTo(Long value) {
			addCriterion("DOCSTATUS <=", value, "docstatus");
			return this;
		}

		public Criteria andDocstatusIn(List<Long> values) {
			addCriterion("DOCSTATUS in", values, "docstatus");
			return this;
		}

		public Criteria andDocstatusNotIn(List<Long> values) {
			addCriterion("DOCSTATUS not in", values, "docstatus");
			return this;
		}

		public Criteria andDocstatusBetween(Long value1, Long value2) {
			addCriterion("DOCSTATUS between", value1, value2, "docstatus");
			return this;
		}

		public Criteria andDocstatusNotBetween(Long value1, Long value2) {
			addCriterion("DOCSTATUS not between", value1, value2, "docstatus");
			return this;
		}

		public Criteria andCruserIsNull() {
			addCriterion("CRUSER is null");
			return this;
		}

		public Criteria andCruserIsNotNull() {
			addCriterion("CRUSER is not null");
			return this;
		}

		public Criteria andCruserEqualTo(String value) {
			addCriterion("CRUSER =", value, "cruser");
			return this;
		}

		public Criteria andCruserNotEqualTo(String value) {
			addCriterion("CRUSER <>", value, "cruser");
			return this;
		}

		public Criteria andCruserGreaterThan(String value) {
			addCriterion("CRUSER >", value, "cruser");
			return this;
		}

		public Criteria andCruserGreaterThanOrEqualTo(String value) {
			addCriterion("CRUSER >=", value, "cruser");
			return this;
		}

		public Criteria andCruserLessThan(String value) {
			addCriterion("CRUSER <", value, "cruser");
			return this;
		}

		public Criteria andCruserLessThanOrEqualTo(String value) {
			addCriterion("CRUSER <=", value, "cruser");
			return this;
		}

		public Criteria andCruserLike(String value) {
			addCriterion("CRUSER like", value, "cruser");
			return this;
		}

		public Criteria andCruserNotLike(String value) {
			addCriterion("CRUSER not like", value, "cruser");
			return this;
		}

		public Criteria andCruserIn(List<String> values) {
			addCriterion("CRUSER in", values, "cruser");
			return this;
		}

		public Criteria andCruserNotIn(List<String> values) {
			addCriterion("CRUSER not in", values, "cruser");
			return this;
		}

		public Criteria andCruserBetween(String value1, String value2) {
			addCriterion("CRUSER between", value1, value2, "cruser");
			return this;
		}

		public Criteria andCruserNotBetween(String value1, String value2) {
			addCriterion("CRUSER not between", value1, value2, "cruser");
			return this;
		}

		public Criteria andCrtimeIsNull() {
			addCriterion("CRTIME is null");
			return this;
		}

		public Criteria andCrtimeIsNotNull() {
			addCriterion("CRTIME is not null");
			return this;
		}

		public Criteria andCrtimeEqualTo(Date value) {
			addCriterionForJDBCDate("CRTIME =", value, "crtime");
			return this;
		}

		public Criteria andCrtimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("CRTIME <>", value, "crtime");
			return this;
		}

		public Criteria andCrtimeGreaterThan(Date value) {
			addCriterionForJDBCDate("CRTIME >", value, "crtime");
			return this;
		}

		public Criteria andCrtimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CRTIME >=", value, "crtime");
			return this;
		}

		public Criteria andCrtimeLessThan(Date value) {
			addCriterionForJDBCDate("CRTIME <", value, "crtime");
			return this;
		}

		public Criteria andCrtimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CRTIME <=", value, "crtime");
			return this;
		}

		public Criteria andCrtimeIn(List<Date> values) {
			addCriterionForJDBCDate("CRTIME in", values, "crtime");
			return this;
		}

		public Criteria andCrtimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("CRTIME not in", values, "crtime");
			return this;
		}

		public Criteria andCrtimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CRTIME between", value1, value2, "crtime");
			return this;
		}

		public Criteria andCrtimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CRTIME not between", value1, value2,
					"crtime");
			return this;
		}

		public Criteria andDocpubtimeIsNull() {
			addCriterion("DOCPUBTIME is null");
			return this;
		}

		public Criteria andDocpubtimeIsNotNull() {
			addCriterion("DOCPUBTIME is not null");
			return this;
		}

		public Criteria andDocpubtimeEqualTo(Date value) {
			addCriterionForJDBCDate("DOCPUBTIME =", value, "docpubtime");
			return this;
		}

		public Criteria andDocpubtimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("DOCPUBTIME <>", value, "docpubtime");
			return this;
		}

		public Criteria andDocpubtimeGreaterThan(Date value) {
			addCriterionForJDBCDate("DOCPUBTIME >", value, "docpubtime");
			return this;
		}

		public Criteria andDocpubtimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("DOCPUBTIME >=", value, "docpubtime");
			return this;
		}

		public Criteria andDocpubtimeLessThan(Date value) {
			addCriterionForJDBCDate("DOCPUBTIME <", value, "docpubtime");
			return this;
		}

		public Criteria andDocpubtimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("DOCPUBTIME <=", value, "docpubtime");
			return this;
		}

		public Criteria andDocpubtimeIn(List<Date> values) {
			addCriterionForJDBCDate("DOCPUBTIME in", values, "docpubtime");
			return this;
		}

		public Criteria andDocpubtimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("DOCPUBTIME not in", values, "docpubtime");
			return this;
		}

		public Criteria andDocpubtimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("DOCPUBTIME between", value1, value2,
					"docpubtime");
			return this;
		}

		public Criteria andDocpubtimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("DOCPUBTIME not between", value1, value2,
					"docpubtime");
			return this;
		}

		public Criteria andDocpuburlIsNull() {
			addCriterion("DOCPUBURL is null");
			return this;
		}

		public Criteria andDocpuburlIsNotNull() {
			addCriterion("DOCPUBURL is not null");
			return this;
		}

		public Criteria andDocpuburlEqualTo(String value) {
			addCriterion("DOCPUBURL =", value, "docpuburl");
			return this;
		}

		public Criteria andDocpuburlNotEqualTo(String value) {
			addCriterion("DOCPUBURL <>", value, "docpuburl");
			return this;
		}

		public Criteria andDocpuburlGreaterThan(String value) {
			addCriterion("DOCPUBURL >", value, "docpuburl");
			return this;
		}

		public Criteria andDocpuburlGreaterThanOrEqualTo(String value) {
			addCriterion("DOCPUBURL >=", value, "docpuburl");
			return this;
		}

		public Criteria andDocpuburlLessThan(String value) {
			addCriterion("DOCPUBURL <", value, "docpuburl");
			return this;
		}

		public Criteria andDocpuburlLessThanOrEqualTo(String value) {
			addCriterion("DOCPUBURL <=", value, "docpuburl");
			return this;
		}

		public Criteria andDocpuburlLike(String value) {
			addCriterion("DOCPUBURL like", value, "docpuburl");
			return this;
		}

		public Criteria andDocpuburlNotLike(String value) {
			addCriterion("DOCPUBURL not like", value, "docpuburl");
			return this;
		}

		public Criteria andDocpuburlIn(List<String> values) {
			addCriterion("DOCPUBURL in", values, "docpuburl");
			return this;
		}

		public Criteria andDocpuburlNotIn(List<String> values) {
			addCriterion("DOCPUBURL not in", values, "docpuburl");
			return this;
		}

		public Criteria andDocpuburlBetween(String value1, String value2) {
			addCriterion("DOCPUBURL between", value1, value2, "docpuburl");
			return this;
		}

		public Criteria andDocpuburlNotBetween(String value1, String value2) {
			addCriterion("DOCPUBURL not between", value1, value2, "docpuburl");
			return this;
		}

		public Criteria andDocorderpriIsNull() {
			addCriterion("DOCORDERPRI is null");
			return this;
		}

		public Criteria andDocorderpriIsNotNull() {
			addCriterion("DOCORDERPRI is not null");
			return this;
		}

		public Criteria andDocorderpriEqualTo(Long value) {
			addCriterion("DOCORDERPRI =", value, "docorderpri");
			return this;
		}

		public Criteria andDocorderpriNotEqualTo(Long value) {
			addCriterion("DOCORDERPRI <>", value, "docorderpri");
			return this;
		}

		public Criteria andDocorderpriGreaterThan(Long value) {
			addCriterion("DOCORDERPRI >", value, "docorderpri");
			return this;
		}

		public Criteria andDocorderpriGreaterThanOrEqualTo(Long value) {
			addCriterion("DOCORDERPRI >=", value, "docorderpri");
			return this;
		}

		public Criteria andDocorderpriLessThan(Long value) {
			addCriterion("DOCORDERPRI <", value, "docorderpri");
			return this;
		}

		public Criteria andDocorderpriLessThanOrEqualTo(Long value) {
			addCriterion("DOCORDERPRI <=", value, "docorderpri");
			return this;
		}

		public Criteria andDocorderpriIn(List<Long> values) {
			addCriterion("DOCORDERPRI in", values, "docorderpri");
			return this;
		}

		public Criteria andDocorderpriNotIn(List<Long> values) {
			addCriterion("DOCORDERPRI not in", values, "docorderpri");
			return this;
		}

		public Criteria andDocorderpriBetween(Long value1, Long value2) {
			addCriterion("DOCORDERPRI between", value1, value2, "docorderpri");
			return this;
		}

		public Criteria andDocorderpriNotBetween(Long value1, Long value2) {
			addCriterion("DOCORDERPRI not between", value1, value2,
					"docorderpri");
			return this;
		}

		public Criteria andInvalidtimeIsNull() {
			addCriterion("INVALIDTIME is null");
			return this;
		}

		public Criteria andInvalidtimeIsNotNull() {
			addCriterion("INVALIDTIME is not null");
			return this;
		}

		public Criteria andInvalidtimeEqualTo(Date value) {
			addCriterionForJDBCDate("INVALIDTIME =", value, "invalidtime");
			return this;
		}

		public Criteria andInvalidtimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("INVALIDTIME <>", value, "invalidtime");
			return this;
		}

		public Criteria andInvalidtimeGreaterThan(Date value) {
			addCriterionForJDBCDate("INVALIDTIME >", value, "invalidtime");
			return this;
		}

		public Criteria andInvalidtimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("INVALIDTIME >=", value, "invalidtime");
			return this;
		}

		public Criteria andInvalidtimeLessThan(Date value) {
			addCriterionForJDBCDate("INVALIDTIME <", value, "invalidtime");
			return this;
		}

		public Criteria andInvalidtimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("INVALIDTIME <=", value, "invalidtime");
			return this;
		}

		public Criteria andInvalidtimeIn(List<Date> values) {
			addCriterionForJDBCDate("INVALIDTIME in", values, "invalidtime");
			return this;
		}

		public Criteria andInvalidtimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("INVALIDTIME not in", values, "invalidtime");
			return this;
		}

		public Criteria andInvalidtimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("INVALIDTIME between", value1, value2,
					"invalidtime");
			return this;
		}

		public Criteria andInvalidtimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("INVALIDTIME not between", value1, value2,
					"invalidtime");
			return this;
		}

		public Criteria andDeluserIsNull() {
			addCriterion("DELUSER is null");
			return this;
		}

		public Criteria andDeluserIsNotNull() {
			addCriterion("DELUSER is not null");
			return this;
		}

		public Criteria andDeluserEqualTo(String value) {
			addCriterion("DELUSER =", value, "deluser");
			return this;
		}

		public Criteria andDeluserNotEqualTo(String value) {
			addCriterion("DELUSER <>", value, "deluser");
			return this;
		}

		public Criteria andDeluserGreaterThan(String value) {
			addCriterion("DELUSER >", value, "deluser");
			return this;
		}

		public Criteria andDeluserGreaterThanOrEqualTo(String value) {
			addCriterion("DELUSER >=", value, "deluser");
			return this;
		}

		public Criteria andDeluserLessThan(String value) {
			addCriterion("DELUSER <", value, "deluser");
			return this;
		}

		public Criteria andDeluserLessThanOrEqualTo(String value) {
			addCriterion("DELUSER <=", value, "deluser");
			return this;
		}

		public Criteria andDeluserLike(String value) {
			addCriterion("DELUSER like", value, "deluser");
			return this;
		}

		public Criteria andDeluserNotLike(String value) {
			addCriterion("DELUSER not like", value, "deluser");
			return this;
		}

		public Criteria andDeluserIn(List<String> values) {
			addCriterion("DELUSER in", values, "deluser");
			return this;
		}

		public Criteria andDeluserNotIn(List<String> values) {
			addCriterion("DELUSER not in", values, "deluser");
			return this;
		}

		public Criteria andDeluserBetween(String value1, String value2) {
			addCriterion("DELUSER between", value1, value2, "deluser");
			return this;
		}

		public Criteria andDeluserNotBetween(String value1, String value2) {
			addCriterion("DELUSER not between", value1, value2, "deluser");
			return this;
		}

		public Criteria andDeltimeIsNull() {
			addCriterion("DELTIME is null");
			return this;
		}

		public Criteria andDeltimeIsNotNull() {
			addCriterion("DELTIME is not null");
			return this;
		}

		public Criteria andDeltimeEqualTo(Date value) {
			addCriterionForJDBCDate("DELTIME =", value, "deltime");
			return this;
		}

		public Criteria andDeltimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("DELTIME <>", value, "deltime");
			return this;
		}

		public Criteria andDeltimeGreaterThan(Date value) {
			addCriterionForJDBCDate("DELTIME >", value, "deltime");
			return this;
		}

		public Criteria andDeltimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("DELTIME >=", value, "deltime");
			return this;
		}

		public Criteria andDeltimeLessThan(Date value) {
			addCriterionForJDBCDate("DELTIME <", value, "deltime");
			return this;
		}

		public Criteria andDeltimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("DELTIME <=", value, "deltime");
			return this;
		}

		public Criteria andDeltimeIn(List<Date> values) {
			addCriterionForJDBCDate("DELTIME in", values, "deltime");
			return this;
		}

		public Criteria andDeltimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("DELTIME not in", values, "deltime");
			return this;
		}

		public Criteria andDeltimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("DELTIME between", value1, value2,
					"deltime");
			return this;
		}

		public Criteria andDeltimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("DELTIME not between", value1, value2,
					"deltime");
			return this;
		}

		public Criteria andModalIsNull() {
			addCriterion("MODAL is null");
			return this;
		}

		public Criteria andModalIsNotNull() {
			addCriterion("MODAL is not null");
			return this;
		}

		public Criteria andModalEqualTo(Integer value) {
			addCriterion("MODAL =", value, "modal");
			return this;
		}

		public Criteria andModalNotEqualTo(Integer value) {
			addCriterion("MODAL <>", value, "modal");
			return this;
		}

		public Criteria andModalGreaterThan(Integer value) {
			addCriterion("MODAL >", value, "modal");
			return this;
		}

		public Criteria andModalGreaterThanOrEqualTo(Integer value) {
			addCriterion("MODAL >=", value, "modal");
			return this;
		}

		public Criteria andModalLessThan(Integer value) {
			addCriterion("MODAL <", value, "modal");
			return this;
		}

		public Criteria andModalLessThanOrEqualTo(Integer value) {
			addCriterion("MODAL <=", value, "modal");
			return this;
		}

		public Criteria andModalIn(List<Integer> values) {
			addCriterion("MODAL in", values, "modal");
			return this;
		}

		public Criteria andModalNotIn(List<Integer> values) {
			addCriterion("MODAL not in", values, "modal");
			return this;
		}

		public Criteria andModalBetween(Integer value1, Integer value2) {
			addCriterion("MODAL between", value1, value2, "modal");
			return this;
		}

		public Criteria andModalNotBetween(Integer value1, Integer value2) {
			addCriterion("MODAL not between", value1, value2, "modal");
			return this;
		}

		public Criteria andDocreltimeIsNull() {
			addCriterion("DOCRELTIME is null");
			return this;
		}

		public Criteria andDocreltimeIsNotNull() {
			addCriterion("DOCRELTIME is not null");
			return this;
		}

		public Criteria andDocreltimeEqualTo(Date value) {
			addCriterionForJDBCDate("DOCRELTIME =", value, "docreltime");
			return this;
		}

		public Criteria andDocreltimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("DOCRELTIME <>", value, "docreltime");
			return this;
		}

		public Criteria andDocreltimeGreaterThan(Date value) {
			addCriterionForJDBCDate("DOCRELTIME >", value, "docreltime");
			return this;
		}

		public Criteria andDocreltimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("DOCRELTIME >=", value, "docreltime");
			return this;
		}

		public Criteria andDocreltimeLessThan(Date value) {
			addCriterionForJDBCDate("DOCRELTIME <", value, "docreltime");
			return this;
		}

		public Criteria andDocreltimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("DOCRELTIME <=", value, "docreltime");
			return this;
		}

		public Criteria andDocreltimeIn(List<Date> values) {
			addCriterionForJDBCDate("DOCRELTIME in", values, "docreltime");
			return this;
		}

		public Criteria andDocreltimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("DOCRELTIME not in", values, "docreltime");
			return this;
		}

		public Criteria andDocreltimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("DOCRELTIME between", value1, value2,
					"docreltime");
			return this;
		}

		public Criteria andDocreltimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("DOCRELTIME not between", value1, value2,
					"docreltime");
			return this;
		}

		public Criteria andDocchannelIsNull() {
			addCriterion("DOCCHANNEL is null");
			return this;
		}

		public Criteria andDocchannelIsNotNull() {
			addCriterion("DOCCHANNEL is not null");
			return this;
		}

		public Criteria andDocchannelEqualTo(Long value) {
			addCriterion("DOCCHANNEL =", value, "docchannel");
			return this;
		}

		public Criteria andDocchannelNotEqualTo(Long value) {
			addCriterion("DOCCHANNEL <>", value, "docchannel");
			return this;
		}

		public Criteria andDocchannelGreaterThan(Long value) {
			addCriterion("DOCCHANNEL >", value, "docchannel");
			return this;
		}

		public Criteria andDocchannelGreaterThanOrEqualTo(Long value) {
			addCriterion("DOCCHANNEL >=", value, "docchannel");
			return this;
		}

		public Criteria andDocchannelLessThan(Long value) {
			addCriterion("DOCCHANNEL <", value, "docchannel");
			return this;
		}

		public Criteria andDocchannelLessThanOrEqualTo(Long value) {
			addCriterion("DOCCHANNEL <=", value, "docchannel");
			return this;
		}

		public Criteria andDocchannelIn(List<Long> values) {
			addCriterion("DOCCHANNEL in", values, "docchannel");
			return this;
		}

		public Criteria andDocchannelNotIn(List<Long> values) {
			addCriterion("DOCCHANNEL not in", values, "docchannel");
			return this;
		}

		public Criteria andDocchannelBetween(Long value1, Long value2) {
			addCriterion("DOCCHANNEL between", value1, value2, "docchannel");
			return this;
		}

		public Criteria andDocchannelNotBetween(Long value1, Long value2) {
			addCriterion("DOCCHANNEL not between", value1, value2, "docchannel");
			return this;
		}

		public Criteria andDocflagIsNull() {
			addCriterion("DOCFLAG is null");
			return this;
		}

		public Criteria andDocflagIsNotNull() {
			addCriterion("DOCFLAG is not null");
			return this;
		}

		public Criteria andDocflagEqualTo(Integer value) {
			addCriterion("DOCFLAG =", value, "docflag");
			return this;
		}

		public Criteria andDocflagNotEqualTo(Integer value) {
			addCriterion("DOCFLAG <>", value, "docflag");
			return this;
		}

		public Criteria andDocflagGreaterThan(Integer value) {
			addCriterion("DOCFLAG >", value, "docflag");
			return this;
		}

		public Criteria andDocflagGreaterThanOrEqualTo(Integer value) {
			addCriterion("DOCFLAG >=", value, "docflag");
			return this;
		}

		public Criteria andDocflagLessThan(Integer value) {
			addCriterion("DOCFLAG <", value, "docflag");
			return this;
		}

		public Criteria andDocflagLessThanOrEqualTo(Integer value) {
			addCriterion("DOCFLAG <=", value, "docflag");
			return this;
		}

		public Criteria andDocflagIn(List<Integer> values) {
			addCriterion("DOCFLAG in", values, "docflag");
			return this;
		}

		public Criteria andDocflagNotIn(List<Integer> values) {
			addCriterion("DOCFLAG not in", values, "docflag");
			return this;
		}

		public Criteria andDocflagBetween(Integer value1, Integer value2) {
			addCriterion("DOCFLAG between", value1, value2, "docflag");
			return this;
		}

		public Criteria andDocflagNotBetween(Integer value1, Integer value2) {
			addCriterion("DOCFLAG not between", value1, value2, "docflag");
			return this;
		}

		public Criteria andDockindIsNull() {
			addCriterion("DOCKIND is null");
			return this;
		}

		public Criteria andDockindIsNotNull() {
			addCriterion("DOCKIND is not null");
			return this;
		}

		public Criteria andDockindEqualTo(Long value) {
			addCriterion("DOCKIND =", value, "dockind");
			return this;
		}

		public Criteria andDockindNotEqualTo(Long value) {
			addCriterion("DOCKIND <>", value, "dockind");
			return this;
		}

		public Criteria andDockindGreaterThan(Long value) {
			addCriterion("DOCKIND >", value, "dockind");
			return this;
		}

		public Criteria andDockindGreaterThanOrEqualTo(Long value) {
			addCriterion("DOCKIND >=", value, "dockind");
			return this;
		}

		public Criteria andDockindLessThan(Long value) {
			addCriterion("DOCKIND <", value, "dockind");
			return this;
		}

		public Criteria andDockindLessThanOrEqualTo(Long value) {
			addCriterion("DOCKIND <=", value, "dockind");
			return this;
		}

		public Criteria andDockindIn(List<Long> values) {
			addCriterion("DOCKIND in", values, "dockind");
			return this;
		}

		public Criteria andDockindNotIn(List<Long> values) {
			addCriterion("DOCKIND not in", values, "dockind");
			return this;
		}

		public Criteria andDockindBetween(Long value1, Long value2) {
			addCriterion("DOCKIND between", value1, value2, "dockind");
			return this;
		}

		public Criteria andDockindNotBetween(Long value1, Long value2) {
			addCriterion("DOCKIND not between", value1, value2, "dockind");
			return this;
		}

		public Criteria andSiteidIsNull() {
			addCriterion("SITEID is null");
			return this;
		}

		public Criteria andSiteidIsNotNull() {
			addCriterion("SITEID is not null");
			return this;
		}

		public Criteria andSiteidEqualTo(Long value) {
			addCriterion("SITEID =", value, "siteid");
			return this;
		}

		public Criteria andSiteidNotEqualTo(Long value) {
			addCriterion("SITEID <>", value, "siteid");
			return this;
		}

		public Criteria andSiteidGreaterThan(Long value) {
			addCriterion("SITEID >", value, "siteid");
			return this;
		}

		public Criteria andSiteidGreaterThanOrEqualTo(Long value) {
			addCriterion("SITEID >=", value, "siteid");
			return this;
		}

		public Criteria andSiteidLessThan(Long value) {
			addCriterion("SITEID <", value, "siteid");
			return this;
		}

		public Criteria andSiteidLessThanOrEqualTo(Long value) {
			addCriterion("SITEID <=", value, "siteid");
			return this;
		}

		public Criteria andSiteidIn(List<Long> values) {
			addCriterion("SITEID in", values, "siteid");
			return this;
		}

		public Criteria andSiteidNotIn(List<Long> values) {
			addCriterion("SITEID not in", values, "siteid");
			return this;
		}

		public Criteria andSiteidBetween(Long value1, Long value2) {
			addCriterion("SITEID between", value1, value2, "siteid");
			return this;
		}

		public Criteria andSiteidNotBetween(Long value1, Long value2) {
			addCriterion("SITEID not between", value1, value2, "siteid");
			return this;
		}

		public Criteria andSrcsiteidIsNull() {
			addCriterion("SRCSITEID is null");
			return this;
		}

		public Criteria andSrcsiteidIsNotNull() {
			addCriterion("SRCSITEID is not null");
			return this;
		}

		public Criteria andSrcsiteidEqualTo(Long value) {
			addCriterion("SRCSITEID =", value, "srcsiteid");
			return this;
		}

		public Criteria andSrcsiteidNotEqualTo(Long value) {
			addCriterion("SRCSITEID <>", value, "srcsiteid");
			return this;
		}

		public Criteria andSrcsiteidGreaterThan(Long value) {
			addCriterion("SRCSITEID >", value, "srcsiteid");
			return this;
		}

		public Criteria andSrcsiteidGreaterThanOrEqualTo(Long value) {
			addCriterion("SRCSITEID >=", value, "srcsiteid");
			return this;
		}

		public Criteria andSrcsiteidLessThan(Long value) {
			addCriterion("SRCSITEID <", value, "srcsiteid");
			return this;
		}

		public Criteria andSrcsiteidLessThanOrEqualTo(Long value) {
			addCriterion("SRCSITEID <=", value, "srcsiteid");
			return this;
		}

		public Criteria andSrcsiteidIn(List<Long> values) {
			addCriterion("SRCSITEID in", values, "srcsiteid");
			return this;
		}

		public Criteria andSrcsiteidNotIn(List<Long> values) {
			addCriterion("SRCSITEID not in", values, "srcsiteid");
			return this;
		}

		public Criteria andSrcsiteidBetween(Long value1, Long value2) {
			addCriterion("SRCSITEID between", value1, value2, "srcsiteid");
			return this;
		}

		public Criteria andSrcsiteidNotBetween(Long value1, Long value2) {
			addCriterion("SRCSITEID not between", value1, value2, "srcsiteid");
			return this;
		}

		public Criteria andLifestatusIsNull() {
			addCriterion("LIFESTATUS is null");
			return this;
		}

		public Criteria andLifestatusIsNotNull() {
			addCriterion("LIFESTATUS is not null");
			return this;
		}

		public Criteria andLifestatusEqualTo(Long value) {
			addCriterion("LIFESTATUS =", value, "lifestatus");
			return this;
		}

		public Criteria andLifestatusNotEqualTo(Long value) {
			addCriterion("LIFESTATUS <>", value, "lifestatus");
			return this;
		}

		public Criteria andLifestatusGreaterThan(Long value) {
			addCriterion("LIFESTATUS >", value, "lifestatus");
			return this;
		}

		public Criteria andLifestatusGreaterThanOrEqualTo(Long value) {
			addCriterion("LIFESTATUS >=", value, "lifestatus");
			return this;
		}

		public Criteria andLifestatusLessThan(Long value) {
			addCriterion("LIFESTATUS <", value, "lifestatus");
			return this;
		}

		public Criteria andLifestatusLessThanOrEqualTo(Long value) {
			addCriterion("LIFESTATUS <=", value, "lifestatus");
			return this;
		}

		public Criteria andLifestatusIn(List<Long> values) {
			addCriterion("LIFESTATUS in", values, "lifestatus");
			return this;
		}

		public Criteria andLifestatusNotIn(List<Long> values) {
			addCriterion("LIFESTATUS not in", values, "lifestatus");
			return this;
		}

		public Criteria andLifestatusBetween(Long value1, Long value2) {
			addCriterion("LIFESTATUS between", value1, value2, "lifestatus");
			return this;
		}

		public Criteria andLifestatusNotBetween(Long value1, Long value2) {
			addCriterion("LIFESTATUS not between", value1, value2, "lifestatus");
			return this;
		}

		public Criteria andDoccruserIsNull() {
			addCriterion("DOCCRUSER is null");
			return this;
		}

		public Criteria andDoccruserIsNotNull() {
			addCriterion("DOCCRUSER is not null");
			return this;
		}

		public Criteria andDoccruserEqualTo(String value) {
			addCriterion("DOCCRUSER =", value, "doccruser");
			return this;
		}

		public Criteria andDoccruserNotEqualTo(String value) {
			addCriterion("DOCCRUSER <>", value, "doccruser");
			return this;
		}

		public Criteria andDoccruserGreaterThan(String value) {
			addCriterion("DOCCRUSER >", value, "doccruser");
			return this;
		}

		public Criteria andDoccruserGreaterThanOrEqualTo(String value) {
			addCriterion("DOCCRUSER >=", value, "doccruser");
			return this;
		}

		public Criteria andDoccruserLessThan(String value) {
			addCriterion("DOCCRUSER <", value, "doccruser");
			return this;
		}

		public Criteria andDoccruserLessThanOrEqualTo(String value) {
			addCriterion("DOCCRUSER <=", value, "doccruser");
			return this;
		}

		public Criteria andDoccruserLike(String value) {
			addCriterion("DOCCRUSER like", value, "doccruser");
			return this;
		}

		public Criteria andDoccruserNotLike(String value) {
			addCriterion("DOCCRUSER not like", value, "doccruser");
			return this;
		}

		public Criteria andDoccruserIn(List<String> values) {
			addCriterion("DOCCRUSER in", values, "doccruser");
			return this;
		}

		public Criteria andDoccruserNotIn(List<String> values) {
			addCriterion("DOCCRUSER not in", values, "doccruser");
			return this;
		}

		public Criteria andDoccruserBetween(String value1, String value2) {
			addCriterion("DOCCRUSER between", value1, value2, "doccruser");
			return this;
		}

		public Criteria andDoccruserNotBetween(String value1, String value2) {
			addCriterion("DOCCRUSER not between", value1, value2, "doccruser");
			return this;
		}

		public Criteria andHitscountIsNull() {
			addCriterion("HITSCOUNT is null");
			return this;
		}

		public Criteria andHitscountIsNotNull() {
			addCriterion("HITSCOUNT is not null");
			return this;
		}

		public Criteria andHitscountEqualTo(Long value) {
			addCriterion("HITSCOUNT =", value, "hitscount");
			return this;
		}

		public Criteria andHitscountNotEqualTo(Long value) {
			addCriterion("HITSCOUNT <>", value, "hitscount");
			return this;
		}

		public Criteria andHitscountGreaterThan(Long value) {
			addCriterion("HITSCOUNT >", value, "hitscount");
			return this;
		}

		public Criteria andHitscountGreaterThanOrEqualTo(Long value) {
			addCriterion("HITSCOUNT >=", value, "hitscount");
			return this;
		}

		public Criteria andHitscountLessThan(Long value) {
			addCriterion("HITSCOUNT <", value, "hitscount");
			return this;
		}

		public Criteria andHitscountLessThanOrEqualTo(Long value) {
			addCriterion("HITSCOUNT <=", value, "hitscount");
			return this;
		}

		public Criteria andHitscountIn(List<Long> values) {
			addCriterion("HITSCOUNT in", values, "hitscount");
			return this;
		}

		public Criteria andHitscountNotIn(List<Long> values) {
			addCriterion("HITSCOUNT not in", values, "hitscount");
			return this;
		}

		public Criteria andHitscountBetween(Long value1, Long value2) {
			addCriterion("HITSCOUNT between", value1, value2, "hitscount");
			return this;
		}

		public Criteria andHitscountNotBetween(Long value1, Long value2) {
			addCriterion("HITSCOUNT not between", value1, value2, "hitscount");
			return this;
		}

		public Criteria andCommentcountIsNull() {
			addCriterion("COMMENTCOUNT is null");
			return this;
		}

		public Criteria andCommentcountIsNotNull() {
			addCriterion("COMMENTCOUNT is not null");
			return this;
		}

		public Criteria andCommentcountEqualTo(Long value) {
			addCriterion("COMMENTCOUNT =", value, "commentcount");
			return this;
		}

		public Criteria andCommentcountNotEqualTo(Long value) {
			addCriterion("COMMENTCOUNT <>", value, "commentcount");
			return this;
		}

		public Criteria andCommentcountGreaterThan(Long value) {
			addCriterion("COMMENTCOUNT >", value, "commentcount");
			return this;
		}

		public Criteria andCommentcountGreaterThanOrEqualTo(Long value) {
			addCriterion("COMMENTCOUNT >=", value, "commentcount");
			return this;
		}

		public Criteria andCommentcountLessThan(Long value) {
			addCriterion("COMMENTCOUNT <", value, "commentcount");
			return this;
		}

		public Criteria andCommentcountLessThanOrEqualTo(Long value) {
			addCriterion("COMMENTCOUNT <=", value, "commentcount");
			return this;
		}

		public Criteria andCommentcountIn(List<Long> values) {
			addCriterion("COMMENTCOUNT in", values, "commentcount");
			return this;
		}

		public Criteria andCommentcountNotIn(List<Long> values) {
			addCriterion("COMMENTCOUNT not in", values, "commentcount");
			return this;
		}

		public Criteria andCommentcountBetween(Long value1, Long value2) {
			addCriterion("COMMENTCOUNT between", value1, value2, "commentcount");
			return this;
		}

		public Criteria andCommentcountNotBetween(Long value1, Long value2) {
			addCriterion("COMMENTCOUNT not between", value1, value2,
					"commentcount");
			return this;
		}

		public Criteria andCollectcountIsNull() {
			addCriterion("COLLECTCOUNT is null");
			return this;
		}

		public Criteria andCollectcountIsNotNull() {
			addCriterion("COLLECTCOUNT is not null");
			return this;
		}

		public Criteria andCollectcountEqualTo(Long value) {
			addCriterion("COLLECTCOUNT =", value, "collectcount");
			return this;
		}

		public Criteria andCollectcountNotEqualTo(Long value) {
			addCriterion("COLLECTCOUNT <>", value, "collectcount");
			return this;
		}

		public Criteria andCollectcountGreaterThan(Long value) {
			addCriterion("COLLECTCOUNT >", value, "collectcount");
			return this;
		}

		public Criteria andCollectcountGreaterThanOrEqualTo(Long value) {
			addCriterion("COLLECTCOUNT >=", value, "collectcount");
			return this;
		}

		public Criteria andCollectcountLessThan(Long value) {
			addCriterion("COLLECTCOUNT <", value, "collectcount");
			return this;
		}

		public Criteria andCollectcountLessThanOrEqualTo(Long value) {
			addCriterion("COLLECTCOUNT <=", value, "collectcount");
			return this;
		}

		public Criteria andCollectcountIn(List<Long> values) {
			addCriterion("COLLECTCOUNT in", values, "collectcount");
			return this;
		}

		public Criteria andCollectcountNotIn(List<Long> values) {
			addCriterion("COLLECTCOUNT not in", values, "collectcount");
			return this;
		}

		public Criteria andCollectcountBetween(Long value1, Long value2) {
			addCriterion("COLLECTCOUNT between", value1, value2, "collectcount");
			return this;
		}

		public Criteria andCollectcountNotBetween(Long value1, Long value2) {
			addCriterion("COLLECTCOUNT not between", value1, value2,
					"collectcount");
			return this;
		}

		public Criteria andCruseridIsNull() {
			addCriterion("CRUSERID is null");
			return this;
		}

		public Criteria andCruseridIsNotNull() {
			addCriterion("CRUSERID is not null");
			return this;
		}

		public Criteria andCruseridEqualTo(Long value) {
			addCriterion("CRUSERID =", value, "cruserid");
			return this;
		}

		public Criteria andCruseridNotEqualTo(Long value) {
			addCriterion("CRUSERID <>", value, "cruserid");
			return this;
		}

		public Criteria andCruseridGreaterThan(Long value) {
			addCriterion("CRUSERID >", value, "cruserid");
			return this;
		}

		public Criteria andCruseridGreaterThanOrEqualTo(Long value) {
			addCriterion("CRUSERID >=", value, "cruserid");
			return this;
		}

		public Criteria andCruseridLessThan(Long value) {
			addCriterion("CRUSERID <", value, "cruserid");
			return this;
		}

		public Criteria andCruseridLessThanOrEqualTo(Long value) {
			addCriterion("CRUSERID <=", value, "cruserid");
			return this;
		}

		public Criteria andCruseridIn(List<Long> values) {
			addCriterion("CRUSERID in", values, "cruserid");
			return this;
		}

		public Criteria andCruseridNotIn(List<Long> values) {
			addCriterion("CRUSERID not in", values, "cruserid");
			return this;
		}

		public Criteria andCruseridBetween(Long value1, Long value2) {
			addCriterion("CRUSERID between", value1, value2, "cruserid");
			return this;
		}

		public Criteria andCruseridNotBetween(Long value1, Long value2) {
			addCriterion("CRUSERID not between", value1, value2, "cruserid");
			return this;
		}

		public Criteria andCompletescoreIsNull() {
			addCriterion("COMPLETESCORE is null");
			return this;
		}

		public Criteria andCompletescoreIsNotNull() {
			addCriterion("COMPLETESCORE is not null");
			return this;
		}

		public Criteria andCompletescoreEqualTo(Long value) {
			addCriterion("COMPLETESCORE =", value, "completescore");
			return this;
		}

		public Criteria andCompletescoreNotEqualTo(Long value) {
			addCriterion("COMPLETESCORE <>", value, "completescore");
			return this;
		}

		public Criteria andCompletescoreGreaterThan(Long value) {
			addCriterion("COMPLETESCORE >", value, "completescore");
			return this;
		}

		public Criteria andCompletescoreGreaterThanOrEqualTo(Long value) {
			addCriterion("COMPLETESCORE >=", value, "completescore");
			return this;
		}

		public Criteria andCompletescoreLessThan(Long value) {
			addCriterion("COMPLETESCORE <", value, "completescore");
			return this;
		}

		public Criteria andCompletescoreLessThanOrEqualTo(Long value) {
			addCriterion("COMPLETESCORE <=", value, "completescore");
			return this;
		}

		public Criteria andCompletescoreIn(List<Long> values) {
			addCriterion("COMPLETESCORE in", values, "completescore");
			return this;
		}

		public Criteria andCompletescoreNotIn(List<Long> values) {
			addCriterion("COMPLETESCORE not in", values, "completescore");
			return this;
		}

		public Criteria andCompletescoreBetween(Long value1, Long value2) {
			addCriterion("COMPLETESCORE between", value1, value2,
					"completescore");
			return this;
		}

		public Criteria andCompletescoreNotBetween(Long value1, Long value2) {
			addCriterion("COMPLETESCORE not between", value1, value2,
					"completescore");
			return this;
		}

		public Criteria andCryscoreIsNull() {
			addCriterion("CRYSCORE is null");
			return this;
		}

		public Criteria andCryscoreIsNotNull() {
			addCriterion("CRYSCORE is not null");
			return this;
		}

		public Criteria andCryscoreEqualTo(Long value) {
			addCriterion("CRYSCORE =", value, "cryscore");
			return this;
		}

		public Criteria andCryscoreNotEqualTo(Long value) {
			addCriterion("CRYSCORE <>", value, "cryscore");
			return this;
		}

		public Criteria andCryscoreGreaterThan(Long value) {
			addCriterion("CRYSCORE >", value, "cryscore");
			return this;
		}

		public Criteria andCryscoreGreaterThanOrEqualTo(Long value) {
			addCriterion("CRYSCORE >=", value, "cryscore");
			return this;
		}

		public Criteria andCryscoreLessThan(Long value) {
			addCriterion("CRYSCORE <", value, "cryscore");
			return this;
		}

		public Criteria andCryscoreLessThanOrEqualTo(Long value) {
			addCriterion("CRYSCORE <=", value, "cryscore");
			return this;
		}

		public Criteria andCryscoreIn(List<Long> values) {
			addCriterion("CRYSCORE in", values, "cryscore");
			return this;
		}

		public Criteria andCryscoreNotIn(List<Long> values) {
			addCriterion("CRYSCORE not in", values, "cryscore");
			return this;
		}

		public Criteria andCryscoreBetween(Long value1, Long value2) {
			addCriterion("CRYSCORE between", value1, value2, "cryscore");
			return this;
		}

		public Criteria andCryscoreNotBetween(Long value1, Long value2) {
			addCriterion("CRYSCORE not between", value1, value2, "cryscore");
			return this;
		}

		public Criteria andAllscoreIsNull() {
			addCriterion("ALLSCORE is null");
			return this;
		}

		public Criteria andAllscoreIsNotNull() {
			addCriterion("ALLSCORE is not null");
			return this;
		}

		public Criteria andAllscoreEqualTo(Long value) {
			addCriterion("ALLSCORE =", value, "allscore");
			return this;
		}

		public Criteria andAllscoreNotEqualTo(Long value) {
			addCriterion("ALLSCORE <>", value, "allscore");
			return this;
		}

		public Criteria andAllscoreGreaterThan(Long value) {
			addCriterion("ALLSCORE >", value, "allscore");
			return this;
		}

		public Criteria andAllscoreGreaterThanOrEqualTo(Long value) {
			addCriterion("ALLSCORE >=", value, "allscore");
			return this;
		}

		public Criteria andAllscoreLessThan(Long value) {
			addCriterion("ALLSCORE <", value, "allscore");
			return this;
		}

		public Criteria andAllscoreLessThanOrEqualTo(Long value) {
			addCriterion("ALLSCORE <=", value, "allscore");
			return this;
		}

		public Criteria andAllscoreIn(List<Long> values) {
			addCriterion("ALLSCORE in", values, "allscore");
			return this;
		}

		public Criteria andAllscoreNotIn(List<Long> values) {
			addCriterion("ALLSCORE not in", values, "allscore");
			return this;
		}

		public Criteria andAllscoreBetween(Long value1, Long value2) {
			addCriterion("ALLSCORE between", value1, value2, "allscore");
			return this;
		}

		public Criteria andAllscoreNotBetween(Long value1, Long value2) {
			addCriterion("ALLSCORE not between", value1, value2, "allscore");
			return this;
		}

		public Criteria andTranscountIsNull() {
			addCriterion("TRANSCOUNT is null");
			return this;
		}

		public Criteria andTranscountIsNotNull() {
			addCriterion("TRANSCOUNT is not null");
			return this;
		}

		public Criteria andTranscountEqualTo(Long value) {
			addCriterion("TRANSCOUNT =", value, "transcount");
			return this;
		}

		public Criteria andTranscountNotEqualTo(Long value) {
			addCriterion("TRANSCOUNT <>", value, "transcount");
			return this;
		}

		public Criteria andTranscountGreaterThan(Long value) {
			addCriterion("TRANSCOUNT >", value, "transcount");
			return this;
		}

		public Criteria andTranscountGreaterThanOrEqualTo(Long value) {
			addCriterion("TRANSCOUNT >=", value, "transcount");
			return this;
		}

		public Criteria andTranscountLessThan(Long value) {
			addCriterion("TRANSCOUNT <", value, "transcount");
			return this;
		}

		public Criteria andTranscountLessThanOrEqualTo(Long value) {
			addCriterion("TRANSCOUNT <=", value, "transcount");
			return this;
		}

		public Criteria andTranscountIn(List<Long> values) {
			addCriterion("TRANSCOUNT in", values, "transcount");
			return this;
		}

		public Criteria andTranscountNotIn(List<Long> values) {
			addCriterion("TRANSCOUNT not in", values, "transcount");
			return this;
		}

		public Criteria andTranscountBetween(Long value1, Long value2) {
			addCriterion("TRANSCOUNT between", value1, value2, "transcount");
			return this;
		}

		public Criteria andTranscountNotBetween(Long value1, Long value2) {
			addCriterion("TRANSCOUNT not between", value1, value2, "transcount");
			return this;
		}

		public Criteria andInformtypeIsNull() {
			addCriterion("INFORMTYPE is null");
			return this;
		}

		public Criteria andInformtypeIsNotNull() {
			addCriterion("INFORMTYPE is not null");
			return this;
		}

		public Criteria andInformtypeEqualTo(Long value) {
			addCriterion("INFORMTYPE =", value, "informtype");
			return this;
		}

		public Criteria andInformtypeNotEqualTo(Long value) {
			addCriterion("INFORMTYPE <>", value, "informtype");
			return this;
		}

		public Criteria andInformtypeGreaterThan(Long value) {
			addCriterion("INFORMTYPE >", value, "informtype");
			return this;
		}

		public Criteria andInformtypeGreaterThanOrEqualTo(Long value) {
			addCriterion("INFORMTYPE >=", value, "informtype");
			return this;
		}

		public Criteria andInformtypeLessThan(Long value) {
			addCriterion("INFORMTYPE <", value, "informtype");
			return this;
		}

		public Criteria andInformtypeLessThanOrEqualTo(Long value) {
			addCriterion("INFORMTYPE <=", value, "informtype");
			return this;
		}

		public Criteria andInformtypeIn(List<Long> values) {
			addCriterion("INFORMTYPE in", values, "informtype");
			return this;
		}

		public Criteria andInformtypeNotIn(List<Long> values) {
			addCriterion("INFORMTYPE not in", values, "informtype");
			return this;
		}

		public Criteria andInformtypeBetween(Long value1, Long value2) {
			addCriterion("INFORMTYPE between", value1, value2, "informtype");
			return this;
		}

		public Criteria andInformtypeNotBetween(Long value1, Long value2) {
			addCriterion("INFORMTYPE not between", value1, value2, "informtype");
			return this;
		}
		
		public Criteria andDocscoreIsNull() {
			addCriterion("DOCSCORE is null");
			return this;
		}

		public Criteria andDocscoreIsNotNull() {
			addCriterion("DOCSCORE is not null");
			return this;
		}
		

		public Criteria andDocscoreEqualTo(Long value) {
			addCriterion("DOCSCORE =", value, "docscore");
			return this;
		}

		public Criteria andDocscoreNotEqualTo(Long value) {
			addCriterion("DOCSCORE <>", value, "docscore");
			return this;
		}

		public Criteria andDocscoreGreaterThan(Long value) {
			addCriterion("DOCSCORE >", value, "docscore");
			return this;
		}

		public Criteria andDocscoreGreaterThanOrEqualTo(Long value) {
			addCriterion("DOCSCORE >=", value, "docscore");
			return this;
		}

		public Criteria andDocscoreLessThan(Long value) {
			addCriterion("DOCSCORE <", value, "docscore");
			return this;
		}

		public Criteria andDocscoreLessThanOrEqualTo(Long value) {
			addCriterion("DOCSCORE <=", value, "docscore");
			return this;
		}

		public Criteria andDocscoreIn(List<Long> values) {
			addCriterion("DOCSCORE in", values, "docscore");
			return this;
		}

		public Criteria andDocscoreNotIn(List<Long> values) {
			addCriterion("DOCSCORE not in", values, "docscore");
			return this;
		}

		public Criteria andDocscoreBetween(Long value1, Long value2) {
			addCriterion("DOCSCORE between", value1, value2, "docscore");
			return this;
		}

		public Criteria andDocscoreNotBetween(Long value1, Long value2) {
			addCriterion("DOCSCORE not between", value1, value2, "docscore");
			return this;
		}
		
		public Criteria extSQL( String sSql) {
			addCriterion(sSql);
			return this;
		}
	}
}