package com.tfs.irp.asseroomsblink.dao.impl;

import com.tfs.irp.asseroomsblink.dao.IrpAsseroomsblinkDAO;
import com.tfs.irp.asseroomsblink.entity.IrpAsseroomsblink;
import com.tfs.irp.asseroomsblink.entity.IrpAsseroomsblinkExample;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;


public class IrpAsseroomsblinkDAOImpl extends SqlMapClientDaoSupport implements IrpAsseroomsblinkDAO {


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_ASSEROOMSBLINK
	 * @ibatorgenerated  Mon Aug 22 10:46:46 CST 2016
	 */
	public IrpAsseroomsblinkDAOImpl() {
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_ASSEROOMSBLINK
	 * @ibatorgenerated  Mon Aug 22 10:46:46 CST 2016
	 */
	public int countByExample(IrpAsseroomsblinkExample example)
			throws SQLException {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"IRP_ASSEROOMSBLINK.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_ASSEROOMSBLINK
	 * @ibatorgenerated  Mon Aug 22 10:46:46 CST 2016
	 */
	public int deleteByExample(IrpAsseroomsblinkExample example)
			throws SQLException {
		int rows = getSqlMapClientTemplate().delete(
				"IRP_ASSEROOMSBLINK.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_ASSEROOMSBLINK
	 * @ibatorgenerated  Mon Aug 22 10:46:46 CST 2016
	 */
	public int deleteByPrimaryKey(Long asseroomsblinkid) throws SQLException {
		IrpAsseroomsblink key = new IrpAsseroomsblink();
		key.setAsseroomsblinkid(asseroomsblinkid);
		int rows = getSqlMapClientTemplate().delete(
				"IRP_ASSEROOMSBLINK.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_ASSEROOMSBLINK
	 * @ibatorgenerated  Mon Aug 22 10:46:46 CST 2016
	 */
	public void insert(IrpAsseroomsblink record) throws SQLException {
		getSqlMapClientTemplate()
				.insert("IRP_ASSEROOMSBLINK.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_ASSEROOMSBLINK
	 * @ibatorgenerated  Mon Aug 22 10:46:46 CST 2016
	 */
	public void insertSelective(IrpAsseroomsblink record) throws SQLException {
		getSqlMapClientTemplate().insert(
				"IRP_ASSEROOMSBLINK.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_ASSEROOMSBLINK
	 * @ibatorgenerated  Mon Aug 22 10:46:46 CST 2016
	 */
	@SuppressWarnings("unchecked")
	public List<IrpAsseroomsblink> selectByExample(
			IrpAsseroomsblinkExample example) throws SQLException {
		List<IrpAsseroomsblink> list = getSqlMapClientTemplate().queryForList(
				"IRP_ASSEROOMSBLINK.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_ASSEROOMSBLINK
	 * @ibatorgenerated  Mon Aug 22 10:46:46 CST 2016
	 */
	public IrpAsseroomsblink selectByPrimaryKey(Long asseroomsblinkid)
			throws SQLException {
		IrpAsseroomsblink key = new IrpAsseroomsblink();
		key.setAsseroomsblinkid(asseroomsblinkid);
		IrpAsseroomsblink record = (IrpAsseroomsblink) getSqlMapClientTemplate()
				.queryForObject(
						"IRP_ASSEROOMSBLINK.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_ASSEROOMSBLINK
	 * @ibatorgenerated  Mon Aug 22 10:46:46 CST 2016
	 */
	public int updateByExampleSelective(IrpAsseroomsblink record,
			IrpAsseroomsblinkExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_ASSEROOMSBLINK.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_ASSEROOMSBLINK
	 * @ibatorgenerated  Mon Aug 22 10:46:46 CST 2016
	 */
	public int updateByExample(IrpAsseroomsblink record,
			IrpAsseroomsblinkExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_ASSEROOMSBLINK.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_ASSEROOMSBLINK
	 * @ibatorgenerated  Mon Aug 22 10:46:46 CST 2016
	 */
	public int updateByPrimaryKeySelective(IrpAsseroomsblink record)
			throws SQLException {
		int rows = getSqlMapClientTemplate()
				.update("IRP_ASSEROOMSBLINK.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_ASSEROOMSBLINK
	 * @ibatorgenerated  Mon Aug 22 10:46:46 CST 2016
	 */
	public int updateByPrimaryKey(IrpAsseroomsblink record) throws SQLException {
		int rows = getSqlMapClientTemplate()
				.update("IRP_ASSEROOMSBLINK.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table IRP_ASSEROOMSBLINK
	 * @ibatorgenerated  Mon Aug 22 10:46:46 CST 2016
	 */
	private static class UpdateByExampleParms extends IrpAsseroomsblinkExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				IrpAsseroomsblinkExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}