package com.tfs.irp.valuesetting.dao.impl;

import com.tfs.irp.util.PageUtil;
import com.tfs.irp.valuesetting.dao.IrpValueSettingDAO;
import com.tfs.irp.valuesetting.entity.IrpValueSetting;
import com.tfs.irp.valuesetting.entity.IrpValueSettingExample;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpValueSettingDAOImpl extends SqlMapClientDaoSupport implements IrpValueSettingDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_SETTING
	 * @ibatorgenerated  Thu Jul 11 15:59:28 CST 2013
	 */
	public int countByExample(IrpValueSettingExample example)
			throws SQLException {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"IRP_VALUE_SETTING.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_SETTING
	 * @ibatorgenerated  Thu Jul 11 15:59:28 CST 2013
	 */
	public int deleteByExample(IrpValueSettingExample example)
			throws SQLException {
		int rows = getSqlMapClientTemplate().delete(
				"IRP_VALUE_SETTING.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_SETTING
	 * @ibatorgenerated  Thu Jul 11 15:59:28 CST 2013
	 */
	public int deleteByPrimaryKey(Long settingid) throws SQLException {
		IrpValueSetting key = new IrpValueSetting();
		key.setSettingid(settingid);
		int rows = getSqlMapClientTemplate().delete(
				"IRP_VALUE_SETTING.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_SETTING
	 * @ibatorgenerated  Thu Jul 11 15:59:28 CST 2013
	 */
	public void insert(IrpValueSetting record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_VALUE_SETTING.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_SETTING
	 * @ibatorgenerated  Thu Jul 11 15:59:28 CST 2013
	 */
	public void insertSelective(IrpValueSetting record) throws SQLException {
		getSqlMapClientTemplate().insert(
				"IRP_VALUE_SETTING.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_SETTING
	 * @ibatorgenerated  Thu Jul 11 15:59:28 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<IrpValueSetting> selectByExample(IrpValueSettingExample example)
			throws SQLException {
		List<IrpValueSetting> list = getSqlMapClientTemplate().queryForList(
				"IRP_VALUE_SETTING.ibatorgenerated_selectByExample", example);
		return list;
	}
	
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_SETTING
	 * @ibatorgenerated  Thu Jul 11 15:59:28 CST 2013
	 */
	public IrpValueSetting selectByPrimaryKey(Long settingid)
			throws SQLException {
		IrpValueSetting key = new IrpValueSetting();
		key.setSettingid(settingid);
		IrpValueSetting record = (IrpValueSetting) getSqlMapClientTemplate().queryForObject(
				"IRP_VALUE_SETTING.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_SETTING
	 * @ibatorgenerated  Thu Jul 11 15:59:28 CST 2013
	 */
	public int updateByExampleSelective(IrpValueSetting record,
			IrpValueSettingExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_VALUE_SETTING.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_SETTING
	 * @ibatorgenerated  Thu Jul 11 15:59:28 CST 2013
	 */
	public int updateByExample(IrpValueSetting record,
			IrpValueSettingExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_VALUE_SETTING.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_SETTING
	 * @ibatorgenerated  Thu Jul 11 15:59:28 CST 2013
	 */
	public int updateByPrimaryKeySelective(IrpValueSetting record)
			throws SQLException {
		int rows = getSqlMapClientTemplate()
				.update("IRP_VALUE_SETTING.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_SETTING
	 * @ibatorgenerated  Thu Jul 11 15:59:28 CST 2013
	 */
	public int updateByPrimaryKey(IrpValueSetting record) throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"IRP_VALUE_SETTING.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table IRP_VALUE_SETTING
	 * @ibatorgenerated  Thu Jul 11 15:59:28 CST 2013
	 */
	private static class UpdateByExampleParms extends IrpValueSettingExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				IrpValueSettingExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public String findRankNameBySumScore(long _sumscore) throws SQLException {
		// TODO Auto-generated method stub
		String rankname = "";
		rankname = this.getSqlMapClientTemplate().queryForObject("IRP_VALUE_SETTING.ibatorgenerated_selectRankNameBySumScore", _sumscore).toString();
		return rankname;
	}
	@Override
	public List<IrpValueSetting> selectByExample(
			IrpValueSettingExample example, PageUtil pageUtil)
			throws SQLException {
		List<IrpValueSetting> list = getSqlMapClientTemplate().queryForList(
				"IRP_VALUE_SETTING.ibatorgenerated_selectByExample", example,pageUtil.getPageIndex(),pageUtil.getPageSize());
		return list;
	}

	@Override
	public String findDescNameBySumScore(long _sumscore) throws SQLException {
		// TODO Auto-generated method stub
		String rankdesc = "";
		rankdesc = this.getSqlMapClientTemplate().queryForObject("IRP_VALUE_SETTING.ibatorgenerated_selectDescBySumScore", _sumscore).toString();
		return rankdesc;
	}
}