package com.tfs.irp.inform.dao.impl;

import com.tfs.irp.inform.dao.IrpInformDAO;
import com.tfs.irp.inform.entity.IrpInform;
import com.tfs.irp.inform.entity.IrpInformExample;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpInformDAOImpl extends SqlMapClientDaoSupport implements IrpInformDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_INFORM
     *
     * @ibatorgenerated Mon Sep 02 15:59:38 CST 2013
     */
    public int countByExample(IrpInformExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_INFORM.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_INFORM
     *
     * @ibatorgenerated Mon Sep 02 15:59:38 CST 2013
     */
    public int deleteByExample(IrpInformExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_INFORM.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_INFORM
     *
     * @ibatorgenerated Mon Sep 02 15:59:38 CST 2013
     */
    public int deleteByPrimaryKey(Long informid) throws SQLException {
        IrpInform key = new IrpInform();
        key.setInformid(informid);
        int rows = getSqlMapClientTemplate().delete("IRP_INFORM.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_INFORM
     *
     * @ibatorgenerated Mon Sep 02 15:59:38 CST 2013
     */
    public void insert(IrpInform record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_INFORM.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_INFORM
     *
     * @ibatorgenerated Mon Sep 02 15:59:38 CST 2013
     */
    public void insertSelective(IrpInform record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_INFORM.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_INFORM
     *
     * @ibatorgenerated Mon Sep 02 15:59:38 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<IrpInform> selectByExample(IrpInformExample example) throws SQLException {
        List<IrpInform> list = getSqlMapClientTemplate().queryForList("IRP_INFORM.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_INFORM
     *
     * @ibatorgenerated Mon Sep 02 15:59:38 CST 2013
     */
    public IrpInform selectByPrimaryKey(Long informid) throws SQLException {
        IrpInform key = new IrpInform();
        key.setInformid(informid);
        IrpInform record = (IrpInform) getSqlMapClientTemplate().queryForObject("IRP_INFORM.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_INFORM
     *
     * @ibatorgenerated Mon Sep 02 15:59:38 CST 2013
     */
    public int updateByExampleSelective(IrpInform record, IrpInformExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_INFORM.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_INFORM
     *
     * @ibatorgenerated Mon Sep 02 15:59:38 CST 2013
     */
    public int updateByExample(IrpInform record, IrpInformExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_INFORM.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_INFORM
     *
     * @ibatorgenerated Mon Sep 02 15:59:38 CST 2013
     */
    public int updateByPrimaryKeySelective(IrpInform record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_INFORM.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_INFORM
     *
     * @ibatorgenerated Mon Sep 02 15:59:38 CST 2013
     */
    public int updateByPrimaryKey(IrpInform record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_INFORM.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table IRP_INFORM
     *
     * @ibatorgenerated Mon Sep 02 15:59:38 CST 2013
     */
    private static class UpdateByExampleParms extends IrpInformExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpInformExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    @Override
    public List<Long> findAllUserIdsByExample(IrpInformExample example)
    		throws SQLException {
    	// TODO Auto-generated method stub
    	List<Long> userIds=(List<Long>) getSqlMapClientTemplate().queryForList("IRP_INFORM.userIdsByExample", example);
    	return userIds;
    }
}