package com.tfs.irp.examrecord.dao;

import java.sql.SQLException;
import java.util.List;

import com.tfs.irp.examrecord.entity.IrpExamRecord;
import com.tfs.irp.examrecord.entity.IrpExamRecordExample;
import com.tfs.irp.util.PageUtil;

public interface IrpExamRecordDAO {
    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_exam_record
	 * @ibatorgenerated  Thu Oct 30 09:59:08 CST 2014
	 */
	int countByExample(IrpExamRecordExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_exam_record
	 * @ibatorgenerated  Thu Oct 30 09:59:08 CST 2014
	 */
	int deleteByExample(IrpExamRecordExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_exam_record
	 * @ibatorgenerated  Thu Oct 30 09:59:08 CST 2014
	 */
	int deleteByPrimaryKey(Long recordid) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_exam_record
	 * @ibatorgenerated  Thu Oct 30 09:59:08 CST 2014
	 */
	void insert(IrpExamRecord record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_exam_record
	 * @ibatorgenerated  Thu Oct 30 09:59:08 CST 2014
	 */
	void insertSelective(IrpExamRecord record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_exam_record
	 * @ibatorgenerated  Thu Oct 30 09:59:08 CST 2014
	 */
	List<IrpExamRecord> selectByExample(IrpExamRecordExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_exam_record
	 * @ibatorgenerated  Thu Oct 30 09:59:08 CST 2014
	 */
	IrpExamRecord selectByPrimaryKey(Long recordid) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_exam_record
	 * @ibatorgenerated  Thu Oct 30 09:59:08 CST 2014
	 */
	int updateByExampleSelective(IrpExamRecord record,
			IrpExamRecordExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_exam_record
	 * @ibatorgenerated  Thu Oct 30 09:59:08 CST 2014
	 */
	int updateByExample(IrpExamRecord record, IrpExamRecordExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_exam_record
	 * @ibatorgenerated  Thu Oct 30 09:59:08 CST 2014
	 */
	int updateByPrimaryKeySelective(IrpExamRecord record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table irp_exam_record
	 * @ibatorgenerated  Thu Oct 30 09:59:08 CST 2014
	 */
	int updateByPrimaryKey(IrpExamRecord record) throws SQLException;

	List<IrpExamRecord> selectByExample(IrpExamRecordExample example,PageUtil _pageutil) throws SQLException;
}