package com.tfs.irp.dbupdate.dao.impl;

import com.tfs.irp.dbupdate.dao.IrpDbupdateDAO;
import com.tfs.irp.dbupdate.entity.IrpDbupdate;
import com.tfs.irp.dbupdate.entity.IrpDbupdateExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpDbupdateDAOImpl extends SqlMapClientDaoSupport implements IrpDbupdateDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DBUPDATE
	 * @ibatorgenerated  Wed Sep 11 13:03:13 CST 2013
	 */
	public int countByExample(IrpDbupdateExample example) throws SQLException {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"IRP_DBUPDATE.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DBUPDATE
	 * @ibatorgenerated  Wed Sep 11 13:03:13 CST 2013
	 */
	public int deleteByExample(IrpDbupdateExample example) throws SQLException {
		int rows = getSqlMapClientTemplate().delete(
				"IRP_DBUPDATE.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DBUPDATE
	 * @ibatorgenerated  Wed Sep 11 13:03:13 CST 2013
	 */
	public int deleteByPrimaryKey(Long dbupid) throws SQLException {
		IrpDbupdate key = new IrpDbupdate();
		key.setDbupid(dbupid);
		int rows = getSqlMapClientTemplate().delete(
				"IRP_DBUPDATE.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DBUPDATE
	 * @ibatorgenerated  Wed Sep 11 13:03:13 CST 2013
	 */
	public void insert(IrpDbupdate record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_DBUPDATE.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DBUPDATE
	 * @ibatorgenerated  Wed Sep 11 13:03:13 CST 2013
	 */
	public void insertSelective(IrpDbupdate record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_DBUPDATE.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DBUPDATE
	 * @ibatorgenerated  Wed Sep 11 13:03:13 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<IrpDbupdate> selectByExample(IrpDbupdateExample example)
			throws SQLException {
		List<IrpDbupdate> list = getSqlMapClientTemplate().queryForList(
				"IRP_DBUPDATE.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DBUPDATE
	 * @ibatorgenerated  Wed Sep 11 13:03:13 CST 2013
	 */
	public IrpDbupdate selectByPrimaryKey(Long dbupid) throws SQLException {
		IrpDbupdate key = new IrpDbupdate();
		key.setDbupid(dbupid);
		IrpDbupdate record = (IrpDbupdate) getSqlMapClientTemplate().queryForObject(
				"IRP_DBUPDATE.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DBUPDATE
	 * @ibatorgenerated  Wed Sep 11 13:03:13 CST 2013
	 */
	public int updateByExampleSelective(IrpDbupdate record,
			IrpDbupdateExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_DBUPDATE.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DBUPDATE
	 * @ibatorgenerated  Wed Sep 11 13:03:13 CST 2013
	 */
	public int updateByExample(IrpDbupdate record, IrpDbupdateExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_DBUPDATE.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DBUPDATE
	 * @ibatorgenerated  Wed Sep 11 13:03:13 CST 2013
	 */
	public int updateByPrimaryKeySelective(IrpDbupdate record)
			throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"IRP_DBUPDATE.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_DBUPDATE
	 * @ibatorgenerated  Wed Sep 11 13:03:13 CST 2013
	 */
	public int updateByPrimaryKey(IrpDbupdate record) throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"IRP_DBUPDATE.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table IRP_DBUPDATE
	 * @ibatorgenerated  Wed Sep 11 13:03:13 CST 2013
	 */
	private static class UpdateByExampleParms extends IrpDbupdateExample {
		private Object record;

		public UpdateByExampleParms(Object record, IrpDbupdateExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<IrpDbupdate> selectByExample(IrpDbupdateExample example,
			PageUtil pageUtil) throws SQLException {
		// TODO Auto-generated method stub
		List<IrpDbupdate> list = getSqlMapClientTemplate().queryForList(
				"IRP_DBUPDATE.ibatorgenerated_selectByExample", example,pageUtil.getPageIndex(),pageUtil.getPageSize());
		return list;
	}
}