package com.tfs.irp.logtype.dao.impl;

import com.tfs.irp.logtype.dao.IrpLogtypeDAO;
import com.tfs.irp.logtype.entity.IrpLogtype;
import com.tfs.irp.logtype.entity.IrpLogtypeExample;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpLogtypeDAOImpl extends SqlMapClientDaoSupport implements IrpLogtypeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGTYPE
	 * @ibatorgenerated  Fri Mar 08 12:50:39 CST 2013
	 */
	public int countByExample(IrpLogtypeExample example) throws SQLException {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"IRP_LOGTYPE.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGTYPE
	 * @ibatorgenerated  Fri Mar 08 12:50:39 CST 2013
	 */
	public int deleteByExample(IrpLogtypeExample example) throws SQLException {
		int rows = getSqlMapClientTemplate().delete(
				"IRP_LOGTYPE.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGTYPE
	 * @ibatorgenerated  Fri Mar 08 12:50:39 CST 2013
	 */
	public int deleteByPrimaryKey(Integer logtypeid) throws SQLException {
		IrpLogtype key = new IrpLogtype();
		key.setLogtypeid(logtypeid);
		int rows = getSqlMapClientTemplate().delete(
				"IRP_LOGTYPE.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGTYPE
	 * @ibatorgenerated  Fri Mar 08 12:50:39 CST 2013
	 */
	public void insert(IrpLogtype record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_LOGTYPE.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGTYPE
	 * @ibatorgenerated  Fri Mar 08 12:50:39 CST 2013
	 */
	public void insertSelective(IrpLogtype record) throws SQLException {
		getSqlMapClientTemplate().insert("IRP_LOGTYPE.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGTYPE
	 * @ibatorgenerated  Fri Mar 08 12:50:39 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<IrpLogtype> selectByExample(IrpLogtypeExample example)
			throws SQLException {
		List<IrpLogtype> list = getSqlMapClientTemplate().queryForList(
				"IRP_LOGTYPE.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGTYPE
	 * @ibatorgenerated  Fri Mar 08 12:50:39 CST 2013
	 */
	public IrpLogtype selectByPrimaryKey(Integer logtypeid) throws SQLException {
		IrpLogtype key = new IrpLogtype();
		key.setLogtypeid(logtypeid);
		IrpLogtype record = (IrpLogtype) getSqlMapClientTemplate().queryForObject(
				"IRP_LOGTYPE.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGTYPE
	 * @ibatorgenerated  Fri Mar 08 12:50:39 CST 2013
	 */
	public int updateByExampleSelective(IrpLogtype record,
			IrpLogtypeExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_LOGTYPE.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGTYPE
	 * @ibatorgenerated  Fri Mar 08 12:50:39 CST 2013
	 */
	public int updateByExample(IrpLogtype record, IrpLogtypeExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"IRP_LOGTYPE.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGTYPE
	 * @ibatorgenerated  Fri Mar 08 12:50:39 CST 2013
	 */
	public int updateByPrimaryKeySelective(IrpLogtype record)
			throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"IRP_LOGTYPE.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_LOGTYPE
	 * @ibatorgenerated  Fri Mar 08 12:50:39 CST 2013
	 */
	public int updateByPrimaryKey(IrpLogtype record) throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"IRP_LOGTYPE.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table IRP_LOGTYPE
	 * @ibatorgenerated  Fri Mar 08 12:50:39 CST 2013
	 */
	private static class UpdateByExampleParms extends IrpLogtypeExample {
		private Object record;

		public UpdateByExampleParms(Object record, IrpLogtypeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}