package com.tfs.irp.value.dao;

import java.sql.SQLException;
import java.util.List;

import com.tfs.irp.util.PageUtil;
import com.tfs.irp.value.entity.IrpValueConfig;
import com.tfs.irp.value.entity.IrpValueConfigExample;

public interface IrpValueConfigDAO {
    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_CONFIG
	 * @ibatorgenerated  Wed Jul 17 11:13:57 CST 2013
	 */
	int countByExample(IrpValueConfigExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_CONFIG
	 * @ibatorgenerated  Wed Jul 17 11:13:57 CST 2013
	 */
	int deleteByExample(IrpValueConfigExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_CONFIG
	 * @ibatorgenerated  Wed Jul 17 11:13:57 CST 2013
	 */
	int deleteByPrimaryKey(Long valueid) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_CONFIG
	 * @ibatorgenerated  Wed Jul 17 11:13:57 CST 2013
	 */
	void insert(IrpValueConfig record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_CONFIG
	 * @ibatorgenerated  Wed Jul 17 11:13:57 CST 2013
	 */
	void insertSelective(IrpValueConfig record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_CONFIG
	 * @ibatorgenerated  Wed Jul 17 11:13:57 CST 2013
	 */
	List<IrpValueConfig> selectByExample(IrpValueConfigExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_CONFIG
	 * @ibatorgenerated  Wed Jul 17 11:13:57 CST 2013
	 */
	IrpValueConfig selectByPrimaryKey(Long valueid) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_CONFIG
	 * @ibatorgenerated  Wed Jul 17 11:13:57 CST 2013
	 */
	int updateByExampleSelective(IrpValueConfig record,
			IrpValueConfigExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_CONFIG
	 * @ibatorgenerated  Wed Jul 17 11:13:57 CST 2013
	 */
	int updateByExample(IrpValueConfig record, IrpValueConfigExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_CONFIG
	 * @ibatorgenerated  Wed Jul 17 11:13:57 CST 2013
	 */
	int updateByPrimaryKeySelective(IrpValueConfig record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IRP_VALUE_CONFIG
	 * @ibatorgenerated  Wed Jul 17 11:13:57 CST 2013
	 */
	int updateByPrimaryKey(IrpValueConfig record) throws SQLException;

	List<IrpValueConfig> selectByExample(IrpValueConfigExample example,PageUtil pageUtil) throws SQLException;
}