package com.tfs.irp.category_file_link.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.tfs.irp.category_file_link.dao.IrpCategoryFileLinkDAO;
import com.tfs.irp.category_file_link.entity.IrpCategoryFileLink;
import com.tfs.irp.category_file_link.entity.IrpCategoryFileLinkExample;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpCategoryFileLinkDAOImpl extends SqlMapClientDaoSupport implements IrpCategoryFileLinkDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category_file_link
     *
     * @ibatorgenerated Mon Mar 17 10:23:17 CST 2014
     */
    public int countByExample(IrpCategoryFileLinkExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("irp_category_file_link.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category_file_link
     *
     * @ibatorgenerated Mon Mar 17 10:23:17 CST 2014
     */
    public int deleteByExample(IrpCategoryFileLinkExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("irp_category_file_link.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category_file_link
     *
     * @ibatorgenerated Mon Mar 17 10:23:17 CST 2014
     */
    public int deleteByPrimaryKey(Long categoryfileid) throws SQLException {
        IrpCategoryFileLink key = new IrpCategoryFileLink();
        key.setCategoryfileid(categoryfileid);
        int rows = getSqlMapClientTemplate().delete("irp_category_file_link.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category_file_link
     *
     * @ibatorgenerated Mon Mar 17 10:23:17 CST 2014
     */
    public void insert(IrpCategoryFileLink record) throws SQLException {
    	getSqlMapClientTemplate().insert("irp_category_file_link.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category_file_link
     *
     * @ibatorgenerated Mon Mar 17 10:23:17 CST 2014
     */
    public void insertSelective(IrpCategoryFileLink record) throws SQLException {
    	getSqlMapClientTemplate().insert("irp_category_file_link.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category_file_link
     *
     * @ibatorgenerated Mon Mar 17 10:23:17 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<IrpCategoryFileLink> selectByExample(IrpCategoryFileLinkExample example) throws SQLException {
        List<IrpCategoryFileLink> list = getSqlMapClientTemplate().queryForList("irp_category_file_link.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category_file_link
     *
     * @ibatorgenerated Mon Mar 17 10:23:17 CST 2014
     */
    public IrpCategoryFileLink selectByPrimaryKey(Long categoryfileid) throws SQLException {
        IrpCategoryFileLink key = new IrpCategoryFileLink();
        key.setCategoryfileid(categoryfileid);
        IrpCategoryFileLink record = (IrpCategoryFileLink) getSqlMapClientTemplate().queryForObject("irp_category_file_link.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category_file_link
     *
     * @ibatorgenerated Mon Mar 17 10:23:17 CST 2014
     */
    public int updateByExampleSelective(IrpCategoryFileLink record, IrpCategoryFileLinkExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_category_file_link.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category_file_link
     *
     * @ibatorgenerated Mon Mar 17 10:23:17 CST 2014
     */
    public int updateByExample(IrpCategoryFileLink record, IrpCategoryFileLinkExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_category_file_link.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category_file_link
     *
     * @ibatorgenerated Mon Mar 17 10:23:17 CST 2014
     */
    public int updateByPrimaryKeySelective(IrpCategoryFileLink record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("irp_category_file_link.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_category_file_link
     *
     * @ibatorgenerated Mon Mar 17 10:23:17 CST 2014
     */
    public int updateByPrimaryKey(IrpCategoryFileLink record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("irp_category_file_link.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table irp_category_file_link
     *
     * @ibatorgenerated Mon Mar 17 10:23:17 CST 2014
     */
    private static class UpdateByExampleParms extends IrpCategoryFileLinkExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpCategoryFileLinkExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}