package com.tfs.irp.microblogcollection.dao;

import com.tfs.irp.microblogcollection.entity.IrpMicroblogCollectionExample;
import com.tfs.irp.microblogcollection.entity.IrpMicroblogCollectionKey;
import java.sql.SQLException;
import java.util.List;

public interface IrpMicroblogCollectionDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    int countByExample(IrpMicroblogCollectionExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    int deleteByExample(IrpMicroblogCollectionExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    int deleteByPrimaryKey(IrpMicroblogCollectionKey key) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    void insert(IrpMicroblogCollectionKey record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    void insertSelective(IrpMicroblogCollectionKey record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    List<IrpMicroblogCollectionKey> selectByExample(IrpMicroblogCollectionExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    int updateByExampleSelective(IrpMicroblogCollectionKey record, IrpMicroblogCollectionExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table IRP_MICROBLOG_COLLECTION
     *
     * @ibatorgenerated Tue Apr 23 12:56:24 CST 2013
     */
    int updateByExample(IrpMicroblogCollectionKey record, IrpMicroblogCollectionExample example) throws SQLException;
    /**
	 * 通过当前登录的id取出所收藏微知的id
	 * @return
	 */
	List selectMicroblogidOfUserid(Long _userid)throws SQLException;
}