package com.tfs.irp.advice.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.tfs.irp.advice.dao.IrpSuggestionDAO;
import com.tfs.irp.advice.entity.IrpSuggestion;
import com.tfs.irp.advice.entity.IrpSuggestionExample;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpSuggestionDAOImpl extends SqlMapClientDaoSupport implements IrpSuggestionDAO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table IRP_SUGGESTION
     *
     * @abatorgenerated Thu Aug 03 15:59:48 CST 2017
     */
    

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_SUGGESTION
     *
     * @abatorgenerated Thu Aug 03 15:59:48 CST 2017
     */
    public void insert(IrpSuggestion record) throws SQLException {
        getSqlMapClientTemplate().insert("IRP_SUGGESTION.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_SUGGESTION
     *
     * @abatorgenerated Thu Aug 03 15:59:48 CST 2017
     */
    public int updateByPrimaryKeyWithoutBLOBs(IrpSuggestion record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_SUGGESTION.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_SUGGESTION
     *
     * @abatorgenerated Thu Aug 03 15:59:48 CST 2017
     */
    public int updateByPrimaryKeyWithBLOBs(IrpSuggestion record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_SUGGESTION.abatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_SUGGESTION
     *
     * @abatorgenerated Thu Aug 03 15:59:48 CST 2017
     */
    public int updateByPrimaryKeySelective(IrpSuggestion record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("IRP_SUGGESTION.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_SUGGESTION
     *
     * @abatorgenerated Thu Aug 03 15:59:48 CST 2017
     */
    public List selectByExampleWithoutBLOBs(IrpSuggestionExample example) throws SQLException {
        List list = getSqlMapClientTemplate().queryForList("IRP_SUGGESTION.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_SUGGESTION
     *
     * @abatorgenerated Thu Aug 03 15:59:48 CST 2017
     */
    public List selectByExampleWithBLOBs(IrpSuggestionExample example) throws SQLException {
        List list = getSqlMapClientTemplate().queryForList("IRP_SUGGESTION.abatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_SUGGESTION
     *
     * @abatorgenerated Thu Aug 03 15:59:48 CST 2017
     */
    public IrpSuggestion selectByPrimaryKey(Long suggestionid) throws SQLException {
        IrpSuggestion key = new IrpSuggestion();
        key.setSuggestionid(suggestionid);
        IrpSuggestion record = (IrpSuggestion) getSqlMapClientTemplate().queryForObject("IRP_SUGGESTION.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_SUGGESTION
     *
     * @abatorgenerated Thu Aug 03 15:59:48 CST 2017
     */
    public int deleteByExample(IrpSuggestionExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("IRP_SUGGESTION.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_SUGGESTION
     *
     * @abatorgenerated Thu Aug 03 15:59:48 CST 2017
     */
    public int deleteByPrimaryKey(Long suggestionid) throws SQLException {
        IrpSuggestion key = new IrpSuggestion();
        key.setSuggestionid(suggestionid);
        int rows = getSqlMapClientTemplate().delete("IRP_SUGGESTION.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_SUGGESTION
     *
     * @abatorgenerated Thu Aug 03 15:59:48 CST 2017
     */
    public int countByExample(IrpSuggestionExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("IRP_SUGGESTION.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_SUGGESTION
     *
     * @abatorgenerated Thu Aug 03 15:59:48 CST 2017
     */
    public int updateByExampleSelective(IrpSuggestion record, IrpSuggestionExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_SUGGESTION.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_SUGGESTION
     *
     * @abatorgenerated Thu Aug 03 15:59:48 CST 2017
     */
    public int updateByExampleWithBLOBs(IrpSuggestion record, IrpSuggestionExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_SUGGESTION.abatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table IRP_SUGGESTION
     *
     * @abatorgenerated Thu Aug 03 15:59:48 CST 2017
     */
    public int updateByExampleWithoutBLOBs(IrpSuggestion record, IrpSuggestionExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("IRP_SUGGESTION.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table IRP_SUGGESTION
     *
     * @abatorgenerated Thu Aug 03 15:59:48 CST 2017
     */
    private static class UpdateByExampleParms extends IrpSuggestionExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpSuggestionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}