package com.tfs.irp.randar.dao.impl;

import com.tfs.irp.randar.dao.IrpRandarDAO;
import com.tfs.irp.randar.entity.IrpRandar;
import com.tfs.irp.randar.entity.IrpRandarExample;
import com.tfs.irp.util.PageUtil;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IrpRandarDAOImpl extends SqlMapClientDaoSupport implements IrpRandarDAO {


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_randar
     *
     * @ibatorgenerated Mon Aug 11 11:45:48 CST 2014
     */
    public int countByExample(IrpRandarExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("irp_randar.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_randar
     *
     * @ibatorgenerated Mon Aug 11 11:45:48 CST 2014
     */
    public int deleteByExample(IrpRandarExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("irp_randar.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_randar
     *
     * @ibatorgenerated Mon Aug 11 11:45:48 CST 2014
     */
    public void insert(IrpRandar record) throws SQLException {
    	getSqlMapClientTemplate().insert("irp_randar.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_randar
     *
     * @ibatorgenerated Mon Aug 11 11:45:48 CST 2014
     */
    public void insertSelective(IrpRandar record) throws SQLException {
    	getSqlMapClientTemplate().insert("irp_randar.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_randar
     *
     * @ibatorgenerated Mon Aug 11 11:45:48 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<IrpRandar> selectByExampleWithBLOBs(IrpRandarExample example) throws SQLException {
        List<IrpRandar> list = getSqlMapClientTemplate().queryForList("irp_randar.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_randar
     *
     * @ibatorgenerated Mon Aug 11 11:45:48 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<IrpRandar> selectByExampleWithoutBLOBs(IrpRandarExample example) throws SQLException {
        List<IrpRandar> list = getSqlMapClientTemplate().queryForList("irp_randar.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_randar
     *
     * @ibatorgenerated Mon Aug 11 11:45:48 CST 2014
     */
    public int updateByExampleSelective(IrpRandar record, IrpRandarExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_randar.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_randar
     *
     * @ibatorgenerated Mon Aug 11 11:45:48 CST 2014
     */
    public int updateByExampleWithBLOBs(IrpRandar record, IrpRandarExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_randar.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table irp_randar
     *
     * @ibatorgenerated Mon Aug 11 11:45:48 CST 2014
     */
    public int updateByExampleWithoutBLOBs(IrpRandar record, IrpRandarExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("irp_randar.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table irp_randar
     *
     * @ibatorgenerated Mon Aug 11 11:45:48 CST 2014
     */
    private static class UpdateByExampleParms extends IrpRandarExample {
        private Object record;

        public UpdateByExampleParms(Object record, IrpRandarExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
    }

	@SuppressWarnings("unchecked")
	@Override
	public List<IrpRandar> selectByExampleWithBLOBs(IrpRandarExample example,
			PageUtil pageUtil) throws SQLException {
		  	List<IrpRandar> list = getSqlMapClientTemplate().queryForList("irp_randar.ibatorgenerated_selectByExampleWithBLOBs", example,pageUtil.getPageIndex(), pageUtil.getPageSize());
	        return list;
	}

	@SuppressWarnings({ "unchecked", "unused" })
	@Override
	public List<String> findBySite(IrpRandarExample example)
			throws SQLException {
		List<String> sites=getSqlMapClientTemplate().queryForList("irp_randar.find_site", example);
		return sites;
	}

	@Override
	public List<Object> selectTablecolumn(String _sql) {
		List<Object> list = null;
		if(_sql!=""&&_sql!=null){
		Map map=new HashMap();
		map.put("sql", _sql);
		list = getSqlMapClientTemplate().queryForList("irp_randar.selectTableColumn", map);
		}
		return list;
	}
}